"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Miscellaneous.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Miscellaneous_Selection"
			{
				"ControlName"							"CScrollableList"
				"FieldName"								"HUD_Miscellaneous_Selection"
				"XPos"									"cs-0.5"
				"YPos"									"cs-0.5"
				"ZPos"									"0"
				"Wide"									"f0"
				"Tall"									"f0"
				"Visible"								"0"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"PaintBackground"						"0"
				"paintBackgroundType"					"0"
				"BGColor_Override"						"Black"

				"Scrollbar"
				{
					"XPos"								"rs1+1"
					"YPos"								"0"
					"Wide"								"6"
					"Tall"								"f0"
					"ZPos"								"1000"
					"ProportionalToParent"				"1"

					"Slider"
					{
						"PaintBackgroundType"			"0"
						"FGColor_Override"				"Gray"
					}

					"nobuttons"							"1"
				}
//===============================================================================================================
// SCOREBOARDS
//===============================================================================================================
				"Scoreboards_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Scoreboards_Icon"
					"XPos"								"4"
					"YPos"								"2"
					"ZPos"								"0"
					"Wide"								"20"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"'"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Scoreboard_Label"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Scoreboard_Label"
					"XPos"								"30"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"Scoreboard"
					"Font"								"HudFontMediumbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_1"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_1"
					"XPos"								"3"
					"YPos"								"26"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
// SCOREBOARD STYLES -------------------------------------------------------------------------------------------------------
				"Scoreboard_Styles"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Scoreboard_Styles"
					"XPos"								"4"
					"YPos"								"31"
					"ZPos"								"20"
					"Wide"								"250"
					"Tall"								"110"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Style_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Style_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"Scoreboard Style"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Style_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Scoreboard_Simple"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Scoreboard_Simple"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"82"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Scoreboard_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Scoreboard_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-6"
							"ZPos"						"0"
							"Wide"						"120"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/scoreboard/scoreboard_simple"
						}
						"Scoreboard_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Scoreboard_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Simple"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Scoreboard_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Scoreboard_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_scoreboard_detailed_off"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Scoreboard_Detailed"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Scoreboard_Detailed"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"82"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Scoreboard_Simple"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Scoreboard_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Scoreboard_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-6"
							"ZPos"						"0"
							"Wide"						"120"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/scoreboard/scoreboard_detailed"
						}
						"Scoreboard_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Scoreboard_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Detailed"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Scoreboard_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Scoreboard_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_scoreboard_detailed_on"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
// SCOREBOARD SETTINGS -------------------------------------------------------------------------------------------------------
				"Scoreboard_Settings"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Scoreboard_Settings"
					"XPos"								"266"
					"YPos"								"31"
					"ZPos"								"20"
					"Wide"								"160"
					"Tall"								"60"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Settings_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Settings_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"Scoreboard Settings"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Settings_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Scoreboard_Mouse_Input"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Scoreboard_Mouse_Input"
						"XPos"							"-2"
						"YPos"							"4"
						"ZPos"							"1"
						"Wide"							"130"
						"Tall"							"16"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Toggle_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"20"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"ActionSignalLevel"			"6"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"Command"					"engine toggle tf_scoreboard_mouse_mode 0 2"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"PaintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"DefaultBGColor_Override"	"Blank"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"FieldName"					"Setting_Checkbox"
							"XPos"						"-2"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"19"
							"Tall"						"f0"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"SmallCheckImage"			"1"
							"button_activation_type"	"1"
							"cvar_name"					"tf_scoreboard_mouse_mode"
							"MouseInputEnabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Setting_Label"
							"XPos"						"19"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"f24"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"HudFontSmallest"
							"LabelText"					"Allow Mouse Input"
							"TextAlignment"				"west"
							"Wrap"						"0"
							"FGColor"					"White"
						}
					}
					"Scoreboard_Ping_Style"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Scoreboard_Ping_Style"
						"XPos"							"0"
						"YPos"							"4"
						"ZPos"							"1"
						"Wide"							"130"
						"Tall"							"16"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Scoreboard_Mouse_Input"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Toggle_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"20"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"ActionSignalLevel"			"6"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"Command"					"engine toggle tf_scoreboard_ping_as_text"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"PaintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"DefaultBGColor_Override"	"Blank"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"FieldName"					"Setting_Checkbox"
							"XPos"						"-2"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"19"
							"Tall"						"f0"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"SmallCheckImage"			"1"
							"button_activation_type"	"1"
							"cvar_name"					"tf_scoreboard_ping_as_text"
							"MouseInputEnabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Setting_Label"
							"XPos"						"19"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"f24"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"HudFontSmallest"
							"LabelText"					"Show Ping As Text"
							"TextAlignment"				"west"
							"Wrap"						"0"
							"FGColor"					"White"
						}
					}
				}
//===============================================================================================================
// VIEWMODELS
//===============================================================================================================
				"Viewmodel_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Viewmodel_Icon"
					"XPos"								"4"
					"YPos"								"146"
					"ZPos"								"0"
					"Wide"								"22"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"@"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Viewmodel_Label"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Viewmodel_Label"
					"XPos"								"32"
					"YPos"								"145"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"Viewmodels"
					"Font"								"HudFontMediumbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_2"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_2"
					"XPos"								"3"
					"YPos"								"172"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
// TRANSPARENT VIEWMODELS ----------------------------------------------------------------------------------------
				"Transparent_Viewmodels"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Transparent_Viewmodels"
					"XPos"								"4"
					"YPos"								"178"
					"ZPos"								"20"
					"Wide"								"200"
					"Tall"								"100"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Style_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Style_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"Viewmodels Style"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Style_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Style_Normal"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Normal"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"80"
						"Tall"							"70"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Normal"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"60"
							"Tall"						"60"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/transparent_viewmodels/transparent_viewmodels_off"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_trans_vmodels_off"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Style_Transparent"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Transparent"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"80"
						"Tall"							"70"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Style_Normal"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Transparent"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"60"
							"Tall"						"60"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/transparent_viewmodels/transparent_viewmodels_on"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_trans_vmodels_on"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
// VIEWMODEL SETTINGS ----------------------------------------------------------------------------------------
				"Viewmodel_Settings"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Viewmodel_Settings"
					"XPos"								"200"
					"YPos"								"178"
					"ZPos"								"20"
					"Wide"								"250"
					"Tall"								"100"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Settings_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Settings_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"Viewmodels Settings"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Settings_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Viewmodel_Toggle"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Viewmodel_Toggle"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"110"
						"Tall"							"22"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Toggle_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"20"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"ActionSignalLevel"			"6"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"Command"					"engine toggle r_drawviewmodel"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"PaintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"DefaultBGColor_Override"	"Blank"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"FieldName"					"Setting_Checkbox"
							"XPos"						"-2"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"22"
							"Tall"						"22"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"SmallCheckImage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"r_drawviewmodel"
							"MouseInputEnabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Setting_Label"
							"XPos"						"24"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"f24"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"HudFontSmallest"
							"LabelText"					"Show Viewmodels"
							"TextAlignment"				"west"
							"Wrap"						"0"
							"FGColor"					"White"
						}
					}
					"Viewmodel_Minimal"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Viewmodel_Minimal"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"115"
						"Tall"							"22"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Viewmodel_Toggle"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Toggle_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"20"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"ActionSignalLevel"			"6"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"Command"					"engine toggle tf_use_min_viewmodels"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"PaintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"DefaultBGColor_Override"	"Blank"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"FieldName"					"Setting_Checkbox"
							"XPos"						"-2"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"22"
							"Tall"						"22"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"SmallCheckImage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"tf_use_min_viewmodels"
							"MouseInputEnabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Setting_Label"
							"XPos"						"24"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"f24"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"HudFontSmallest"
							"LabelText"					"Minimal Viewmodels"
							"TextAlignment"				"west"
							"Wrap"						"0"
							"FGColor"					"White"
						}
					}
					"Viewmodel_Flip"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Viewmodel_Flip"
						"XPos"							"0"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"111"
						"Tall"							"22"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Viewmodel_Toggle"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Toggle_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"20"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"ActionSignalLevel"			"6"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"Command"					"engine toggle cl_flipviewmodels"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"PaintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"DefaultBGColor_Override"	"Blank"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"FieldName"					"Setting_Checkbox"
							"XPos"						"-2"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"22"
							"Tall"						"22"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"SmallCheckImage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"cl_flipviewmodels"
							"MouseInputEnabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Setting_Label"
							"XPos"						"24"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"f24"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"HudFontSmallest"
							"LabelText"					"Flip Viewmodels"
							"TextAlignment"				"west"
							"Wrap"						"0"
							"FGColor"					"White"
						}
					}
					"FOV_Slider"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"FOV_Slider"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"115"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Viewmodel_Flip"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Setting_Label"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"30"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"HudFontMediumSmallBold"
							"LabelText"					"FOV:"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Setting_Slider"
						{
							"ControlName"				"CCvarSlider"
							"FieldName"					"Setting_Slider"
							"XPos"						"rs1"
							"YPos"						"0"
							"ZPos"						"2"
							"Wide"						"80"
							"Tall"						"30"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"minvalue"					"0"
							"maxvalue"					"150"
							"cvar_name"					"viewmodel_fov"
						}
					}
				}
//===============================================================================================================
// AMMO COUNT
//===============================================================================================================
                "Ammo_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Ammo_Icon"
					"XPos"								"4"
					"YPos"								"146+132"
					"ZPos"								"0"
					"Wide"								"22"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"#"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Ammo_Label"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Ammo_Label"
					"XPos"								"32"
					"YPos"								"145+132"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"Ammo"
					"Font"								"HudFontMediumbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_3"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_3"
					"XPos"								"3"
					"YPos"								"172+132"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
                "Ammo"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Ammo"
					"XPos"								"4"
					"YPos"								"178+100+30"
					"ZPos"								"20"
					"Wide"								"180"
					"Tall"								"80"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Ammo_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Ammo_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"Ammo Count (Jump Mode)"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
                        "YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Ammo_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Ammo_On"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Ammo_On"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"50"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Ammo_Icon"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Icon"
							"XPos"						"cs-0.5-1"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"Ingame_Large"
							"LabelText"					"4"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
                        "Ammo_Icon_Shadow"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Icon_Shadow"
							"XPos"						"cs-0.5-1+1"
							"YPos"						"1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"Ingame_Large"
							"LabelText"					"4"
							"TextAlignment"				"center"
							"FGColor"					"Main_Shadow_Transparent"
						}
						"Ammo_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Enabled"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Ammo_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Ammo_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_ammo_enable"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Ammo_Off"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Ammo_Off"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"50"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Ammo_On"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Ammo_Icon"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Icon"
							"XPos"						"cs-0.5-1"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"Ingame_Large"
							"LabelText"					"4"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
                        "Ammo_Icon_Shadow"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Icon_Shadow"
							"XPos"						"cs-0.5-1+1"
							"YPos"						"1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"Ingame_Large"
							"LabelText"					"4"
							"TextAlignment"				"center"
							"FGColor"					"Main_Shadow_Transparent"
						}
                        "Ammo_Disabled"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Ammo_Disabled"
							"XPos"						"cs-0.5"
							"YPos"						"1"
							"ZPos"						"3"
							"Wide"						"64"
							"Tall"						"36"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/general/disabled_cross"
							"ScaleImage"				"1"
							"Drawcolor"					"Red"
							"Alpha"						"200"
						}
						"Ammo_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Disabled"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Ammo_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Ammo_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_ammo_disable"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
            }
		}
	}
}