"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Frame.res"
{
	"SafeMode"
	{
		"ControlName"									"EditablePanel"
		"FieldName"										"SafeMode"
		"XPos"											"cs-0.5"
		"YPos"											"cs-0.5+15"
		"Wide"											"600"
		"Tall"											"302"
		"ZPos"											"50"
		"Visible"										"1"
		"Enabled"										"1"
		"ProportionalToParent"							"1"
		"PaintBackground"								"1"
		"PaintBackgroundType"							"0"
		"BGcolor_Override"								"blank"

        "Background"    // background excluding the scroll bar and header
        {
        "ControlName"									"Panel"
		"FieldName"										"Background"
		"XPos"											"150"
		"YPos"											"22"
		"Wide"											"f0-150"
		"Tall"											"f0-22"
		"ZPos"											"-2"
		"Visible"										"1"
		"Enabled"										"1"
		"ProportionalToParent"							"1"
		"PaintBackground"								"1"
		"PaintBackgroundType"							"0"
		"BGcolor_Override"								"IsItTransparentBlack"
        }
//==============================================================================================================================
// TITLE BAR
//==============================================================================================================================
		"Title"
		{
			"ControlName"								"CExLabel"
			"FieldName"									"Title"
			"XPos"										"cs-0.5"
			"YPos"										"0"
			"ZPos"										"-1"
			"Wide"										"f0"
			"Tall"										"22"
			"Visible"									"1"
			"Enabled"									"1"
			"ProportionalToParent"						"1"
			"Use_Proportional_Insets"					"1"
			"AllCaps"									"1"
			"LabelText"									"HUD Customization"
			"Font"										"HudFontSmallBold"
			"TextAlignment"								"west"
			"TextInsetX"								"5"
			"FGColor"									"White"
			"PaintBackground"							"1"
			"paintBackgroundtype"						"0"
			"RoundedCorners"							"0"
			"BGColor_Override"							"TransparentBlack"
		}
		"CloseButton"
		{
			"ControlName"								"CExButton"
			"FieldName"									"CloseButton"
			"XPos"										"rs1-2"
			"YPos"										"2"
			"ZPos"										"20"
			"Wide"										"18"
			"Tall"										"18"
			"Visible"									"1"
			"Enabled"									"1"
			"ProportionalToParent"						"1"
			"LabelText"									"X"
			"Font"										"Symbols16"
			"TextAlignment"								"center"
			"Command"									"engine cl_mainmenu_safemode 0; mat_queue_mode -1; gameui_allowescape"
			"ActionSignalLevel"							"2"
			"Sound_Depressed"							"UI/buttonclick.wav"
			"PaintBackground"							"1"

			"DefaultFGColor_Override"					"White"
			"ArmedFGColor_Override"						"White"
			"DepressedFGColor_Override"					"White"

			"DefaultBGColor_Override"					"Button_Red"
			"ArmedBGColor_Override"						"Button_Red_Hover"
			"DepressedBGColor_Override"					"Button_Red_Hover"
		}
		"GitHubWiki"
		{
			"ControlName"								"CExButton"
			"FieldName"									"GitHubWiki"
			"XPos"										"2"
			"YPos"										"0"
			"ZPos"										"20"
			"Wide"										"60"
			"Tall"										"18"
			"Visible"									"1"
			"Enabled"									"1"
			"ProportionalToParent"						"1"
			"LabelText"									"HUD WIKI"
			"Font"										"FontStorePrice"
			"TextAlignment"								"center"
			"Command"									"url https://github.com/Hypnootize/m0rehud/wiki/CUSTOMIZATIONS"
			"PaintBackground"							"1"

			"DefaultBGColor_Override"					"Button_Dark"
			"ArmedBGColor_Override"						"Button_Hover"
			"DepressedBGColor_Override"					"Button_Hover"

			"Pin_To_Sibling"							"CloseButton"
			"Pin_Corner_To_Sibling"						"PIN_TOPRIGHT"
			"Pin_To_Sibling_Corner"						"PIN_TOPLEFT"
		}
		"ResetAllButton"
		{
			"ControlName"								"CExButton"
			"FieldName"									"ResetAllButton"
			"XPos"										"2"
			"YPos"										"0"
			"ZPos"										"20"
			"Wide"										"100"
			"Tall"										"18"
			"Visible"									"1"
			"Enabled"									"1"
			"ProportionalToParent"						"1"
			"AllCaps"									"1"
			"LabelText"									"Reset HUD To Default"
			"Font"										"FontStorePrice"
			"TextAlignment"								"center"
			"Command"									"engine jh_customization_reset"
			"ActionSignalLevel"							"2"
			"Sound_Depressed"							"UI/buttonclick.wav"

			"DefaultBGColor_Override"					"200 170 65 255"
			"ArmedBGColor_Override"						"150 120 50 255"
			"DepressedBGColor_Override"					"150 120 50 255"

			"Pin_To_Sibling"							"GitHubWiki"
			"Pin_Corner_To_Sibling"						"PIN_TOPRIGHT"
			"Pin_To_Sibling_Corner"						"PIN_TOPLEFT"
		}
		"ReloadGameButton"
		{
			"ControlName"								"CExButton"
			"FieldName"									"ReloadGameButton"
			"XPos"										"2"
			"YPos"										"0"
			"ZPos"										"20"
			"Wide"										"80"
			"Tall"										"18"
			"Visible"									"1"
			"Enabled"									"1"
			"ProportionalToParent"						"1"
			"AllCaps"									"1"
			"LabelText"									"Restart TF2"
			"Font"										"FontStorePrice"
			"TextAlignment"								"center"
			"Command"									"engine gameui_allowescape; mat_queue_mode -1; gamemenucommand RestartWithNewLanguage"
			"ActionSignalLevel"							"2"
			"Sound_Depressed"							"UI/buttonclick.wav"

			"DefaultBGColor_Override"					"Button_Red"
			"ArmedBGColor_Override"						"Button_Red_Hover"
			"DepressedBGColor_Override"					"Button_Red_Hover"

			"Pin_To_Sibling"							"ResetAllButton"
			"Pin_Corner_To_Sibling"						"PIN_TOPRIGHT"
			"Pin_To_Sibling_Corner"						"PIN_TOPLEFT"
		}
//==============================================================================================================================
// MAIN SCROLLER LIST
//==============================================================================================================================
		"Categories_Navigation"
		{
			"ControlName"								"EditablePanel"
			"FieldName"									"Categories_Navigation"
			"XPos"										"0"
			"YPos"										"cs-0.5"
			"Wide"										"150"
			"Tall"										"f44"
			"ZPos"										"50"
			"Visible"									"1"
			"Enabled"									"1"
			"ProportionalToParent"						"1"
			"PaintBackground"							"1"
			"PaintBackgroundType"						"0"
			"BGcolor_Override"							"TransparentBlack"

			"Title"
			{
				"ControlName"							"CExLabel"
				"FieldName"								"Title"
				"XPos"									"cs-0.5"
				"YPos"									"0"
				"ZPos"									"0"
				"Wide"									"f0"
				"Tall"									"20"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"AllCaps"								"1"
				"LabelText"								"Select a Category:"
				"Font"									"HudFontSmallBold"
				"TextAlignment"							"center"
				"FGColor"								"Highlight_Color_Dark"
				"PaintBackground"						"1"
				"paintBackgroundtype"					"0"
				"RoundedCorners"						"0"
				"BGColor_Override"						"blank"
			}
			"Home_Button"
			{
				"ControlName"							"CExButton"
				"FieldName"								"Home_Button"
				"XPos"									"cs-0.5"
				"YPos"									"18"
				"ZPos"									"20"
				"Wide"									"f4"
				"Tall"									"22"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"AllCaps"								"0"
				"LabelText"								"HOME"
				"Font"									"Menu_Small"
				"TextAlignment"							"center"
				"Command"								"engine jh_custom_home; hud_reloadscheme"
				"ActionSignalLevel"						"3"
				"Sound_Depressed"						"UI/buttonclick.wav"

                "DefaultBGColor_Override"				"Background_Dark"
                
			}
			"Speedos_Soldier"
			{
				"ControlName"							"CExButton"
				"FieldName"								"Speedos_Soldier"
				"XPos"									"0"
				"YPos"									"2"
				"ZPos"									"20"
				"Wide"									"f4"
				"Tall"									"22"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"AllCaps"								"1"
				"LabelText"								"Soldier Speedos"
				"Font"									"Menu_Small"
				"TextAlignment"							"center"
				"Command"								"engine jh_custom_speedos_soldier; hud_reloadscheme"
				"ActionSignalLevel"						"3"
				"Sound_Depressed"						"UI/buttonclick.wav"

                "DefaultBGColor_Override"				"Background_Dark"
                

				"Pin_To_Sibling"						"Home_Button"
				"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
				"Pin_To_Sibling_Corner"					"PIN_BOTTOMLEFT"
			}
			"Speedos_Demo"
			{
				"ControlName"							"CExButton"
				"FieldName"								"Speedos_Demo"
				"XPos"									"0"
				"YPos"									"2"
				"ZPos"									"20"
				"Wide"									"f4"
				"Tall"									"22"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"AllCaps"								"1"
				"LabelText"								"Demo Speedos"
				"Font"									"Menu_Small"
				"TextAlignment"							"center"
				"Command"								"engine jh_custom_speedos_demo; hud_reloadscheme"
				"ActionSignalLevel"						"3"
				"Sound_Depressed"						"UI/buttonclick.wav"

                "DefaultBGColor_Override"				"Background_Dark"
                

				"Pin_To_Sibling"						"Speedos_Soldier"
				"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
				"Pin_To_Sibling_Corner"					"PIN_BOTTOMLEFT"
			}
			"Crosshairs"
			{
				"ControlName"							"CExButton"
				"FieldName"								"Crosshairs"
				"XPos"									"0"
				"YPos"									"2"
				"ZPos"									"20"
				"Wide"									"f4"
				"Tall"									"22"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"AllCaps"								"1"
				"LabelText"								"Crosshair"
				"Font"									"Menu_Small"
				"TextAlignment"							"center"
				"Command"								"engine jh_custom_crosshairs; hud_reloadscheme"
				"ActionSignalLevel"						"3"
				"Sound_Depressed"						"UI/buttonclick.wav"

                "DefaultBGColor_Override"				"Background_Dark"
                

				"Pin_To_Sibling"						"Speedos_Demo"
				"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
				"Pin_To_Sibling_Corner"					"PIN_BOTTOMLEFT"
			}
			"Resolutions"
			{
				"ControlName"							"CExButton"
				"FieldName"								"Resolutions"
				"XPos"									"0"
				"YPos"									"2"
				"ZPos"									"20"
				"Wide"									"f4"
				"Tall"									"22"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"AllCaps"								"1"
				"LabelText"								"Resolution"
				"Font"									"Menu_Small"
				"TextAlignment"							"center"
				"Command"								"engine jh_custom_resolutions; hud_reloadscheme"
				"ActionSignalLevel"						"3"
				"Sound_Depressed"						"UI/buttonclick.wav"

                "DefaultBGColor_Override"				"Background_Dark"
                

				"Pin_To_Sibling"						"Crosshairs"
				"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
				"Pin_To_Sibling_Corner"					"PIN_BOTTOMLEFT"
			}
			"Fonts_Primary"
			{
				"ControlName"							"CExButton"
				"FieldName"								"Fonts_Primary"
				"XPos"									"0"
				"YPos"									"2"
				"ZPos"									"20"
				"Wide"									"f4"
				"Tall"									"22"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"AllCaps"								"1"
				"LabelText"								"Primary Font"
				"Font"									"Menu_Small"
				"TextAlignment"							"center"
				"Command"								"engine jh_custom_fonts_primary; hud_reloadscheme"
				"ActionSignalLevel"						"3"
				"Sound_Depressed"						"UI/buttonclick.wav"

                "DefaultBGColor_Override"				"Background_Dark"
                

				"Pin_To_Sibling"						"Resolutions"
				"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
				"Pin_To_Sibling_Corner"					"PIN_BOTTOMLEFT"
			}
            "Fonts_Secondary"
			{
				"ControlName"							"CExButton"
				"FieldName"								"Fonts_Secondary"
				"XPos"									"0"
				"YPos"									"2"
				"ZPos"									"20"
				"Wide"									"f4"
				"Tall"									"22"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"AllCaps"								"1"
				"LabelText"								"Secondary Font"
				"Font"									"Menu_Small"
				"TextAlignment"							"center"
				"Command"								"engine jh_custom_fonts_secondary; hud_reloadscheme"
				"ActionSignalLevel"						"3"
				"Sound_Depressed"						"UI/buttonclick.wav"

                "DefaultBGColor_Override"				"Background_Dark"
                

				"Pin_To_Sibling"						"Fonts_Primary"
				"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
				"Pin_To_Sibling_Corner"					"PIN_BOTTOMLEFT"
			}
			"Miscellaneous"
			{
				"ControlName"							"CExButton"
				"FieldName"								"Miscellaneous"
				"XPos"									"0"
				"YPos"									"2"
				"ZPos"									"20"
				"Wide"									"f4"
				"Tall"									"22"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"AllCaps"								"1"
				"LabelText"								"Miscellaneous"
				"Font"									"Menu_Small"
				"TextAlignment"							"center"
				"Command"								"engine jh_custom_miscellaneous; hud_reloadscheme"
				"ActionSignalLevel"						"3"
				"Sound_Depressed"						"UI/buttonclick.wav"

                "DefaultBGColor_Override"				"Background_Dark"
                

				"Pin_To_Sibling"						"Fonts_Secondary"
				"Pin_Corner_To_Sibling"					"PIN_TOPLEFT"
				"Pin_To_Sibling_Corner"					"PIN_BOTTOMLEFT"
			}
		}
//==============================================================================================================================
// MAIN CUSTOMIZATION PANEL
//==============================================================================================================================
		"Customizations_Panel"
		{
			"ControlName"								"EditablePanel"
			"FieldName"									"Customizations_Panel"
			"XPos"										"rs1-2"
			"YPos"										"cs-0.5"
			"ZPos"										"-1"
			"Wide"										"f154"
			"Tall"										"f48"
			"Visible"									"1"
			"Enabled"									"1"
			"ProportionalToParent"						"1"
			"PaintBackground"							"0"
			"BGColor_Override"							"Gray"
		}
//==============================================================================================================================
// OK/APPLY BUTTON
//==============================================================================================================================
		"ApplyButton"
		{
			"ControlName"								"CExButton"
			"FieldName"									"ApplyButton"
			"XPos"										"cs-0.5"
			"YPos"										"rs1"
			"ZPos"										"20"
			"Wide"										"f0"
			"Tall"										"22"
			"Visible"									"1"
			"Enabled"									"1"
			"ProportionalToParent"						"1"
			"AllCaps"									"1"
			"LabelText"									"Reload to Apply Changes"
			"Font"										"HudFontSmallBold"
			"TextAlignment"								"center"
			"Command"									"engine cl_mainmenu_safemode 0; gameui_allowescape; mat_queue_mode -1; hud_reloadscheme"
			"ActionSignalLevel"							"2"
			"Sound_Depressed"							"UI/buttonclick.wav"

			"PaintBackground"							"1"
			"PaintBorder"								"0"
			"RoundedCorners"							"0"

			"DefaultBGColor_Override"					"Button_Green"
			"ArmedBGColor_Override"						"Button_Green_Hover"
			"DepressedBGColor_Override"					"Button_Green_Hover"
		}
	}
}