"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Miscellaneous.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_JumpSettings_Selection"
			{
				"ControlName"							"CScrollableList"
				"FieldName"								"HUD_JumpSettings_Selection"
				"XPos"									"cs-0.5"
				"YPos"									"cs-0.5"
				"ZPos"									"0"
				"Wide"									"f0"
				"Tall"									"f0"
				"Visible"								"0"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"PaintBackground"						"0"
				"paintBackgroundType"					"0"
				"BGColor_Override"						"Black"

				"Scrollbar"
				{
					"XPos"								"rs1+1"
					"YPos"								"0"
					"Wide"								"6"
					"Tall"								"f0"
					"ZPos"								"1000"
					"ProportionalToParent"				"1"

					"Slider"
					{
						"PaintBackgroundType"			"0"
						"FGColor_Override"				"Gray"
					}

					"nobuttons"							"1"
				}
//===============================================================================================================
// AMMO COUNT
//===============================================================================================================
                "Ammo_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Ammo_Icon"
					"XPos"								"4"
					"YPos"								"1"
					"ZPos"								"0"
					"Wide"								"22"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"#"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Ammo_Label"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Ammo_Label"
					"XPos"								"32"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"Ammo"
					"Font"								"HudFontMediumbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
                "Jump_Warning"
                {
                    "ControlName"					"CExLabel"
                    "FieldName"						"Jump_Warning"
                    "XPos"							"96"
                    "YPos"							"3"
                    "ZPos"							"0"
                    "Wide"							"20"
                    "Tall"							"24"
                    "Visible"						"1"
                    "Enabled"						"1"
                    "ProportionalToParent"			"1"
                    "LabelText"						"l"
                    "Font"							"Symbols24"
                    "TextAlignment"					"center"
                    "FGColor"						"Highlight_Color_Dark"
                }
				"Separator_3"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_3"
					"XPos"								"3"
					"YPos"								"26"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
                "Ammo"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Ammo"
					"XPos"								"4"
					"YPos"								"31"
					"ZPos"								"20"
					"Wide"								"160"
					"Tall"								"80"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Ammo_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Ammo_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"Ammo Count"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
                        "YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Ammo_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Ammo_On"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Ammo_On"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"50"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Ammo_Icon"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Icon"
							"XPos"						"cs-0.5-1"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"Ingame_Large"
							"LabelText"					"4"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
                        "Ammo_Icon_Shadow"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Icon_Shadow"
							"XPos"						"cs-0.5-1+1"
							"YPos"						"1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"Ingame_Large"
							"LabelText"					"4"
							"TextAlignment"				"center"
							"FGColor"					"Main_Shadow_Transparent"
						}
						"Ammo_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Enabled"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Ammo_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Ammo_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_ammo_enable"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Ammo_Off"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Ammo_Off"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"50"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Ammo_On"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Ammo_Icon"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Icon"
							"XPos"						"cs-0.5-1"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"Ingame_Large"
							"LabelText"					"4"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
                        "Ammo_Icon_Shadow"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Icon_Shadow"
							"XPos"						"cs-0.5-1+1"
							"YPos"						"1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"Ingame_Large"
							"LabelText"					"4"
							"TextAlignment"				"center"
							"FGColor"					"Main_Shadow_Transparent"
						}
                        "Ammo_Disabled"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Ammo_Disabled"
							"XPos"						"cs-0.5"
							"YPos"						"1"
							"ZPos"						"3"
							"Wide"						"64"
							"Tall"						"36"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/general/disabled_cross"
							"ScaleImage"				"1"
							"Drawcolor"					"Red"
							"Alpha"						"200"
						}
						"Ammo_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Disabled"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Ammo_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Ammo_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_ammo_disable"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
                "Pipes"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Pipes"
					"XPos"								"160"
					"YPos"								"31"
					"ZPos"								"20"
					"Wide"								"180"
					"Tall"								"80"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Ammo_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Ammo_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"Sticky Count"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
                        "YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Ammo_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Ammo_On"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Ammo_On"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"50"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Ammo_Icon"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Icon"
							"XPos"						"cs-0.5-1"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"Ingame_Medium"
							"LabelText"					"1"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
                        "Ammo_Icon_Shadow"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Icon_Shadow"
							"XPos"						"cs-0.5-1+1"
							"YPos"						"1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"Ingame_Medium"
							"LabelText"					"1"
							"TextAlignment"				"center"
							"FGColor"					"Main_Shadow_Transparent"
						}
						"Ammo_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Enabled"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Ammo_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Ammo_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_pipes_enable"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Ammo_Off"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Ammo_Off"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"50"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Ammo_On"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Ammo_Icon"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Icon"
							"XPos"						"cs-0.5-1"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"Ingame_Medium"
							"LabelText"					"1"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
                        "Ammo_Icon_Shadow"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Icon_Shadow"
							"XPos"						"cs-0.5-1+1"
							"YPos"						"1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"Ingame_Medium"
							"LabelText"					"1"
							"TextAlignment"				"center"
							"FGColor"					"Main_Shadow_Transparent"
						}
                        "Ammo_Disabled"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Ammo_Disabled"
							"XPos"						"cs-0.5"
							"YPos"						"1"
							"ZPos"						"3"
							"Wide"						"64"
							"Tall"						"36"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/general/disabled_cross"
							"ScaleImage"				"1"
							"Drawcolor"					"Red"
							"Alpha"						"200"
						}
						"Ammo_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Ammo_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Disabled"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Ammo_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Ammo_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_pipes_disable"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
//===============================================================================================================
// TEMPUS BG
//===============================================================================================================
				"TempusBG_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"TempusBG_Icon"
					"XPos"								"4"
					"YPos"								"1+110"
					"ZPos"								"0"
					"Wide"								"20"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"'"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"TempusBG_Label"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"TempusBG_Label"
					"XPos"								"30"
					"YPos"								"110"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"Tempus Panels"
					"Font"								"HudFontMediumbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
                "Jump_Warning2"
                {
                    "ControlName"					"CExLabel"
                    "FieldName"						"Jump_Warning2"
                    "XPos"							"179"
                    "YPos"							"2+110"
                    "ZPos"							"0"
                    "Wide"							"20"
                    "Tall"							"24"
                    "Visible"						"1"
                    "Enabled"						"1"
                    "ProportionalToParent"			"1"
                    "LabelText"						"l"
                    "Font"							"Symbols24"
                    "TextAlignment"					"center"
                    "FGColor"						"Highlight_Color_Dark"
                }
                "Restart_Warning"
                {
                    "ControlName"					"CExLabel"
                    "FieldName"						"Restart_Warning"
                    "XPos"							"179+24"
                    "YPos"							"2+110"
                    "ZPos"							"0"
                    "Wide"							"20"
                    "Tall"							"24"
                    "Visible"						"1"
                    "Enabled"						"1"
                    "ProportionalToParent"			"1"
                    "LabelText"						"C"
                    "Font"							"Symbols24"
                    "TextAlignment"					"center"
                    "FGColor"						"Red"
                }
				"Separator_4"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_4"
					"XPos"								"3"
					"YPos"								"26+110"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
// TempusBG STYLES -------------------------------------------------------------------------------------------------------
				"TempusBG_Styles"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"TempusBG_Styles"
					"XPos"								"4"
					"YPos"								"31+110"
					"ZPos"								"20"
					"Wide"								"250"
					"Tall"								"110"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Style_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Style_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"Background Style"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Style_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"TempusBG_Off"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"TempusBG_Off"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"82"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"TempusBG_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"TempusBG_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-6"
							"ZPos"						"0"
							"Wide"						"120"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/tempusbg/tempusbg_off"
						}
						"TempusBG_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"TempusBG_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Disabled"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"TempusBG_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"TempusBG_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_tempusbg_disable"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"TempusBG_On"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"TempusBG_On"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"82"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"TempusBG_Off"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"TempusBG_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"TempusBG_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-6"
							"ZPos"						"0"
							"Wide"						"120"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/tempusbg/tempusbg_on"
						}
						"TempusBG_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"TempusBG_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Enabled"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"TempusBG_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"TempusBG_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_tempusbg_enable"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
//===============================================================================================================
// LUXELS
//===============================================================================================================
				"Luxels_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Luxels_Icon"
					"XPos"								"4"
					"YPos"								"1+130+120"
					"ZPos"								"0"
					"Wide"								"20"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"@"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Luxels_Label"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Luxels_Label"
					"XPos"								"30"
					"YPos"								"130+120"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"Luxels"
					"Font"								"HudFontMediumbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
                "Jump_Warning3"
                {
                    "ControlName"					"CExLabel"
                    "FieldName"						"Jump_Warning3"
                    "XPos"							"100"
                    "YPos"							"2+130+120"
                    "ZPos"							"0"
                    "Wide"							"20"
                    "Tall"							"24"
                    "Visible"						"1"
                    "Enabled"						"1"
                    "ProportionalToParent"			"1"
                    "LabelText"						"l"
                    "Font"							"Symbols24"
                    "TextAlignment"					"center"
                    "FGColor"						"Highlight_Color_Dark"
                }
				"Separator_6"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_6"
					"XPos"								"3"
					"YPos"								"26+130+120"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
// Luxels STYLES -------------------------------------------------------------------------------------------------------
				"Luxels_Styles"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Luxels_Styles"
					"XPos"								"4"
					"YPos"								"31+130+120"
					"ZPos"								"20"
					"Wide"								"f0"
					"Tall"								"110"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Style_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Style_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"Luxels Style"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Style_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Luxels_Grid"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Luxels_Grid"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"82"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Luxels_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Luxels_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-6"
							"ZPos"						"0"
							"Wide"						"125"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/luxels/debugluxels_default"
						}
						"Luxels_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Luxels_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Grid"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Luxels_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Luxels_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_luxels_default"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Luxels_Glass"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Luxels_Glass"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"82"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Luxels_Grid"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Luxels_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Luxels_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-6"
							"ZPos"						"0"
							"Wide"						"125"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/luxels/debugluxels_glass"
						}
						"Luxels_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Luxels_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Glass"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Luxels_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Luxels_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_luxels_glass"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Luxels_GlassClear"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Luxels_GlassClear"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"82"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Luxels_Glass"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Luxels_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Luxels_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-6"
							"ZPos"						"0"
							"Wide"						"125"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/luxels/debugluxels_glassclear"
						}
						"Luxels_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Luxels_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Clear"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Luxels_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Luxels_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_luxels_glassclear"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
            }
		}
	}
}