"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Home.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Customization_Home_Panel"
			{
				"ControlName"							"EditablePanel"
				"FieldName"								"HUD_Customization_Home_Panel"
				"XPos"									"0"
				"YPos"									"0"
				"ZPos"									"0"
				"Wide"									"f0"
				"Tall"									"f0"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"PaintBackground"						"0"
				"paintBackgroundType"					"0"
				"BGColor_Override"						"Black"

				"Title"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title"
					"XPos"								"3"
					"YPos"								"3"
					"ZPos"								"0"
					"Wide"								"f6"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"Use_Proportional_Insets"			"1"
					"AllCaps"							"1"
					"LabelText"							"Welcome to JumpHUD"
					"Font"								"TitleFont"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Description"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Description"
					"XPos"								"3"
					"YPos"								"30"
					"ZPos"								"0"
					"Wide"								"f6"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"Use_Proportional_Insets"			"1"
					"AllCaps"							"1"
					"LabelText"							"Select a category to navigate and apply the customizations"
					"Font"								"HudFontSmallbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_1"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_1"
					"XPos"								"3"
					"YPos"								"50"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"Warning_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Warning_Icon"
					"XPos"								"2"
					"YPos"								"61"
					"ZPos"								"0"
					"Wide"								"24"
					"Tall"								"30"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"C"
					"Font"								"Symbols28"
					"TextAlignment"						"center"
					"FGColor"							"Red"
				}
				"Warning_1"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Warning_1"
					"XPos"								"28+2"
					"YPos"								"62"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"30"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"Use_Proportional_Insets"			"1"
					"AllCaps"							"1"
					"Wrap"								"1"
					"LabelText"							"Certain customizations will require a game restart in order to be fully applied, this will be indicated by the reload symbol!"
					"Font"								"HudFontSmallbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_2"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_2"
					"XPos"								"3"
					"YPos"								"102"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"Jump_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Jump_Icon"
					"XPos"								"2"
					"YPos"								"113"
					"ZPos"								"0"
					"Wide"								"24"
					"Tall"								"30"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"l"
					"Font"								"Symbols28"
					"TextAlignment"						"center"
					"FGColor"							"Highlight_Color_Dark"
				}
				"Jump_1"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Jump_1"
					"XPos"								"28+2"
					"YPos"								"114"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"30"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"Use_Proportional_Insets"			"1"
					"AllCaps"							"1"
					"Wrap"								"1"
					"LabelText"							"Some customization options will only affect the HUD while in Jump Mode, these will be indicated by the explosion symbol."
					"Font"								"HudFontSmallbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_3"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_3"
					"XPos"								"3"
					"YPos"								"154"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"TF_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"TF_Icon"
					"XPos"								"2"
					"YPos"								"165"
					"ZPos"								"0"
					"Wide"								"24"
					"Tall"								"30"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"0"
					"Font"								"Symbols28"
					"TextAlignment"						"center"
					"FGColor"							"Orange"
				}
				"TF_1"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"TF_1"
					"XPos"								"28+2"
					"YPos"								"166"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"30"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"Use_Proportional_Insets"			"1"
					"AllCaps"							"1"
					"Wrap"								"1"
					"LabelText"							"Some customization options will only affect the HUD while in Casual Mode, these will be indicated by the TF2 logo."
					"Font"								"HudFontSmallbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_4"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_4"
					"XPos"								"3"
					"YPos"								"206"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"Links_Desc"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Links_Desc"
					"XPos"								"5"
					"YPos"								"254"
					"ZPos"								"0"
					"Wide"								"140"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"Check out JumpHUD on:"
					"Font"								"HudFontSmallbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"GitHub_Link"
				{
					"ControlName"						"CExButton"
					"FieldName"							"GitHub_Link"
					"XPos"								"10"
					"YPos"								"3"
					"ZPos"								"20"
					"Wide"								"20"
					"Tall"								"20"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"^"
					"Font"								"Symbols20"
					"TextAlignment"						"center"
					"Command"							"url https://github.com/itsmmarc/jumphud"
					"PaintBackground"					"0"

					"DefaultFGColor_Override"			"White"
					"ArmedFGColor_Override"				"145 145 145 255"
					"DepressedFGColor_Override"			"White"

					"Pin_To_Sibling"					"Links_Desc"
					"Pin_Corner_To_Sibling"				"PIN_TOPLEFT"
					"Pin_To_Sibling_Corner"				"PIN_TOPRIGHT"
				}
                "Discord_Link"
				{
					"ControlName"						"CExButton"
					"FieldName"							"Discord_Link"
					"XPos"								"3"
					"YPos"								"-3"
					"ZPos"								"20"
					"Wide"								"20"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"c"
					"Font"								"HypnotizeIcons18"
					"TextAlignment"						"center"
					"Command"							"url https://discord.gg/s6yJMGecMZ"
					"PaintBackground"					"0"

					"DefaultFGColor_Override"			"114 137 218 255"
					"ArmedFGColor_Override"				"59 72 114 255"
					"DepressedFGColor_Override"			"114 137 218 255"

					"Pin_To_Sibling"					"GitHub_Link"
					"Pin_Corner_To_Sibling"				"PIN_TOPLEFT"
					"Pin_To_Sibling_Corner"				"PIN_TOPRIGHT"
				}
                "GameBanana_Link"
				{
					"ControlName"						"CExButton"
					"FieldName"							"GameBanana_Link"
					"XPos"								"3"
					"YPos"								"0"
					"ZPos"								"20"
					"Wide"								"20"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"]"
					"Font"								"Symbols18"
					"TextAlignment"						"center"
					"Command"							"url https://gamebanana.com/mods/625862"
					"PaintBackground"					"0"

					"DefaultFGColor_Override"			"255 200 0 255"
					"ArmedFGColor_Override"				"160 125 0 255"
					"DepressedFGColor_Override"			"255 200 0 255"

					"Pin_To_Sibling"					"Discord_Link"
					"Pin_Corner_To_Sibling"				"PIN_TOPLEFT"
					"Pin_To_Sibling_Corner"				"PIN_TOPRIGHT"
				}
                "TF2HUDs_Link"
				{
					"ControlName"						"CExButton"
					"FieldName"							"TF2HUDs_Link"
					"XPos"								"3"
					"YPos"								"0"
					"ZPos"								"20"
					"Wide"								"20"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"0"
					"Font"								"Symbols18"
					"TextAlignment"						"center"
					"Command"							"url https://tf2huds.dev/hud/jumphud"
					"PaintBackground"					"0"

					"DefaultFGColor_Override"			"255 85 0 255"
					"ArmedFGColor_Override"				"145 50 0 255"
					"DepressedFGColor_Override"			"255 85 0 255"

					"Pin_To_Sibling"					"GameBanana_Link"
					"Pin_Corner_To_Sibling"				"PIN_TOPLEFT"
					"Pin_To_Sibling_Corner"				"PIN_TOPRIGHT"
				}
				"ComfigHUDs_Link"
				{
					"ControlName"						"CExButton"
					"FieldName"							"ComfigHUDs_Link"
					"XPos"								"3"
					"YPos"								"0"
					"ZPos"								"20"
					"Wide"								"20"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"n"
					"Font"								"Symbols18"
					"TextAlignment"						"center"
					"Command"							"url https://comfig.app/huds/page/jumphud/"
					"PaintBackground"					"0"

					"DefaultFGColor_Override"			"0 150 135 255"
					"ArmedFGColor_Override"				"0 100 90 255"
					"DepressedFGColor_Override"			"0 150 135 255"

					"Pin_To_Sibling"					"TF2HUDs_Link"
					"Pin_Corner_To_Sibling"				"PIN_TOPLEFT"
					"Pin_To_Sibling_Corner"				"PIN_TOPRIGHT"
				}
			}
		}
	}
}