"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Fonts_Primary.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Font_Primary_Selection"
			{
				"ControlName"							"CScrollableList"
				"FieldName"								"HUD_Font_Primary_Selection"
				"XPos"									"cs-0.5"
				"YPos"									"cs-0.5"
				"ZPos"									"0"
				"Wide"									"f0"
				"Tall"									"f0"
				"Visible"								"0"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"PaintBackground"						"0"
				"paintBackgroundType"					"0"
				"BGColor_Override"						"Black"

				"Scrollbar"
				{
					"XPos"								"rs1+1"
					"YPos"								"0"
					"Wide"								"6"
					"Tall"								"f0"
					"ZPos"								"1000"
					"ProportionalToParent"				"1"

					"Slider"
					{
						"PaintBackgroundType"			"0"
						"FGColor_Override"				"Gray"
					}

					"nobuttons"							"1"
				}
				"Title_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title_Icon"
					"XPos"								"4"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"20"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"5"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Title"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title"
					"XPos"								"30"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"HUD FONTS"
					"Font"								"HudFontMediumBold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Restart_Warning"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Restart_Warning"
					"XPos"								"-100"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"25"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"C"
					"Font"								"Symbols20"
					"TextAlignment"						"center"
					"FGColor"							"Red"

					"Pin_To_Sibling"					"Title"
					"Pin_Corner_To_Sibling"				"PIN_CENTER_LEFT"
					"Pin_To_Sibling_Corner"				"PIN_CENTER_LEFT"
				}
				"Separator_1"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_1"
					"XPos"								"3"
					"YPos"								"25"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"Primary"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Primary"
					"XPos"								"5"
					"YPos"								"35"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"15"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"Primary"
					"Font"								"HudFontSmallBold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_2"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_2"
					"XPos"								"3"
					"YPos"								"50"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"1"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"Font_Picker"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Font_Picker"
					"XPos"								"0"
					"YPos"								"53"
					"ZPos"								"20"
					"Wide"								"f7"
					"Tall"								"528"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Coolvetica_Italic"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Coolvetica_Italic"
						"XPos"							"4"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f0"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"

						"Font_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Font_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_font_prim_cool_italic"
							"LabelText"					""
							"TextAlignment"				"center"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"1"

							"DefaultBGColor_Override"	"TransparentLightestBlack"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Font_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Name"
							"XPos"						"3"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"AllCaps"					"1"
							"LabelText"					"Default - Coolvetica Italic"
							"Font"						"HudFontSmall"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Font_Showcase"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Showcase"
							"XPos"						"3"
							"YPos"						"rs1-3"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"24"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"LabelText"					"1234567890 - The quick brown fox jumps over the lazy dog"
							"Font"						"Showcase_Coolvetica_Italic"
							"TextAlignment"				"west"
							"FGColor"					"Gray"
						}
						"Separator"
						{
							"ControlName"				"EditablePanel"
							"FieldName"					"Separator"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"1"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"paintBackground"			"1"
							"paintBackgroundtype"		"3"
							"BGcolor_Override"			"Gray"
						}
					}
                    "Coolvetica_Rg_Bold"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Coolvetica_Rg_Bold"
						"XPos"							"0"
						"YPos"							"3"
						"ZPos"							"0"
						"Wide"							"f0"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"

                        "Pin_To_Sibling"				"Coolvetica_Italic"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Font_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Font_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_font_prim_cool_rgbold"
							"LabelText"					""
							"TextAlignment"				"center"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"1"

							"DefaultBGColor_Override"	"TransparentLightestBlack"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Font_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Name"
							"XPos"						"3"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"AllCaps"					"1"
							"LabelText"					"Coolvetica Regular Bold"
							"Font"						"HudFontSmall"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Font_Showcase"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Showcase"
							"XPos"						"3"
							"YPos"						"rs1-3"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"24"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"LabelText"					"1234567890 - The quick brown fox jumps over the lazy dog"
							"Font"						"Showcase_Coolvetica_Rg_Bold"
							"TextAlignment"				"west"
							"FGColor"					"Gray"
						}
						"Separator"
						{
							"ControlName"				"EditablePanel"
							"FieldName"					"Separator"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"1"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"paintBackground"			"1"
							"paintBackgroundtype"		"3"
							"BGcolor_Override"			"Gray"
						}
					}
                    "Poppins"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Poppins"
						"XPos"							"0"
						"YPos"							"3"
						"ZPos"							"0"
						"Wide"							"f0"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"

						"Pin_To_Sibling"				"Coolvetica_Rg_Bold"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Font_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Font_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_font_prim_poppins"
							"LabelText"					""
							"TextAlignment"				"center"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"1"

							"DefaultBGColor_Override"	"TransparentLightestBlack"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Font_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Name"
							"XPos"						"3"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"AllCaps"					"1"
							"LabelText"					"Poppins"
							"Font"						"HudFontSmall"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Font_Showcase"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Showcase"
							"XPos"						"3"
							"YPos"						"rs1-3"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"24"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"LabelText"					"1234567890 - The quick brown fox jumps over the lazy dog"
							"Font"						"Showcase_Poppins"
							"TextAlignment"				"west"
							"FGColor"					"Gray"
						}
						"Separator"
						{
							"ControlName"				"EditablePanel"
							"FieldName"					"Separator"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"1"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"paintBackground"			"1"
							"paintBackgroundtype"		"3"
							"BGcolor_Override"			"Gray"
						}
					}
					"Renogare"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Renogare"
						"XPos"							"0"
						"YPos"							"3"
						"ZPos"							"0"
						"Wide"							"f0"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"

						"Pin_To_Sibling"				"Poppins"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Font_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Font_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_font_prim_renogare"
							"LabelText"					""
							"TextAlignment"				"center"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"1"

							"DefaultBGColor_Override"	"TransparentLightestBlack"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Font_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Name"
							"XPos"						"3"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"AllCaps"					"1"
							"LabelText"					"Renogare"
							"Font"						"HudFontSmall"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Font_Showcase"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Showcase"
							"XPos"						"3"
							"YPos"						"rs1-3"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"24"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"LabelText"					"1234567890 - The quick brown fox jumps over the lazy dog"
							"Font"						"Showcase_Renogare"
							"TextAlignment"				"west"
							"FGColor"					"Gray"
						}
						"Separator"
						{
							"ControlName"				"EditablePanel"
							"FieldName"					"Separator"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"1"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"paintBackground"			"1"
							"paintBackgroundtype"		"3"
							"BGcolor_Override"			"Gray"
						}
					}
                    "Steelfish"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Steelfish"
						"XPos"							"0"
						"YPos"							"3"
						"ZPos"							"0"
						"Wide"							"f0"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"

						"Pin_To_Sibling"				"Renogare"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Font_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Font_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_font_prim_steelfish"
							"LabelText"					""
							"TextAlignment"				"center"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"1"

							"DefaultBGColor_Override"	"TransparentLightestBlack"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Font_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Name"
							"XPos"						"3"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"AllCaps"					"1"
							"LabelText"					"Steelfish"
							"Font"						"HudFontSmall"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Font_Showcase"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Showcase"
							"XPos"						"3"
							"YPos"						"rs1-3"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"24"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"LabelText"					"1234567890 - The quick brown fox jumps over the lazy dog"
							"Font"						"Showcase_Steelfish"
							"TextAlignment"				"west"
							"FGColor"					"Gray"
						}
						"Separator"
						{
							"ControlName"				"EditablePanel"
							"FieldName"					"Separator"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"1"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"paintBackground"			"1"
							"paintBackgroundtype"		"3"
							"BGcolor_Override"			"Gray"
						}
					}
                    "NK57"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"NK57"
						"XPos"							"0"
						"YPos"							"3"
						"ZPos"							"0"
						"Wide"							"f0"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"

						"Pin_To_Sibling"				"Steelfish"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Font_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Font_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_font_prim_nk57"
							"LabelText"					""
							"TextAlignment"				"center"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"1"

							"DefaultBGColor_Override"	"TransparentLightestBlack"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Font_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Name"
							"XPos"						"3"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"AllCaps"					"1"
							"LabelText"					"NK57"
							"Font"						"HudFontSmall"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Font_Showcase"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Showcase"
							"XPos"						"3"
							"YPos"						"rs1-3"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"24"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"LabelText"					"1234567890 - The quick brown fox jumps over the lazy dog"
							"Font"						"Showcase_NK57"
							"TextAlignment"				"west"
							"FGColor"					"Gray"
						}
						"Separator"
						{
							"ControlName"				"EditablePanel"
							"FieldName"					"Separator"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"1"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"paintBackground"			"1"
							"paintBackgroundtype"		"3"
							"BGcolor_Override"			"Gray"
						}
					}
                    "Bahnschrift"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Bahnschrift"
						"XPos"							"0"
						"YPos"							"3"
						"ZPos"							"0"
						"Wide"							"f0"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"

						"Pin_To_Sibling"				"NK57"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Font_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Font_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_font_prim_bahnschrift"
							"LabelText"					""
							"TextAlignment"				"center"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"1"

							"DefaultBGColor_Override"	"TransparentLightestBlack"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Font_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Name"
							"XPos"						"3"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"AllCaps"					"1"
							"LabelText"					"Bahnschrift"
							"Font"						"HudFontSmall"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Font_Showcase"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Showcase"
							"XPos"						"3"
							"YPos"						"rs1-3"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"24"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"LabelText"					"1234567890 - The quick brown fox jumps over the lazy dog"
							"Font"						"Showcase_Bahnschrift"
							"TextAlignment"				"west"
							"FGColor"					"Gray"
						}
						"Separator"
						{
							"ControlName"				"EditablePanel"
							"FieldName"					"Separator"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"1"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"paintBackground"			"1"
							"paintBackgroundtype"		"3"
							"BGcolor_Override"			"Gray"
						}
					}
                    "Montserrat"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Montserrat"
						"XPos"							"0"
						"YPos"							"3"
						"ZPos"							"0"
						"Wide"							"f0"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"

						"Pin_To_Sibling"				"Bahnschrift"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Font_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Font_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_font_prim_montserrat"
							"LabelText"					""
							"TextAlignment"				"center"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"1"

							"DefaultBGColor_Override"	"TransparentLightestBlack"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Font_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Name"
							"XPos"						"3"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"AllCaps"					"1"
							"LabelText"					"Montserrat"
							"Font"						"HudFontSmall"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Font_Showcase"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Showcase"
							"XPos"						"3"
							"YPos"						"rs1-3"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"24"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"LabelText"					"1234567890 - The quick brown fox jumps over the lazy dog"
							"Font"						"Showcase_Montserrat"
							"TextAlignment"				"west"
							"FGColor"					"Gray"
						}
						"Separator"
						{
							"ControlName"				"EditablePanel"
							"FieldName"					"Separator"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"1"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"paintBackground"			"1"
							"paintBackgroundtype"		"3"
							"BGcolor_Override"			"Gray"
						}
					}
                    "Square"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Square"
						"XPos"							"0"
						"YPos"							"3"
						"ZPos"							"0"
						"Wide"							"f0"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"

						"Pin_To_Sibling"				"Montserrat"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Font_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Font_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_font_prim_square"
							"LabelText"					""
							"TextAlignment"				"center"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"1"

							"DefaultBGColor_Override"	"TransparentLightestBlack"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Font_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Name"
							"XPos"						"3"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"AllCaps"					"1"
							"LabelText"					"Square"
							"Font"						"HudFontSmall"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Font_Showcase"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Showcase"
							"XPos"						"3"
							"YPos"						"rs1-3"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"24"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"LabelText"					"1234567890 - The quick brown fox jumps over the lazy dog"
							"Font"						"Showcase_Square"
							"TextAlignment"				"west"
							"FGColor"					"Gray"
						}
						"Separator"
						{
							"ControlName"				"EditablePanel"
							"FieldName"					"Separator"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"1"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"paintBackground"			"1"
							"paintBackgroundtype"		"3"
							"BGcolor_Override"			"Gray"
						}
					}
                    "Eternal"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Eternal"
						"XPos"							"0"
						"YPos"							"3"
						"ZPos"							"0"
						"Wide"							"f0"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"

						"Pin_To_Sibling"				"Square"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Font_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Font_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_font_prim_eternal"
							"LabelText"					""
							"TextAlignment"				"center"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"1"

							"DefaultBGColor_Override"	"TransparentLightestBlack"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Font_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Name"
							"XPos"						"3"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"AllCaps"					"1"
							"LabelText"					"Eternal"
							"Font"						"HudFontSmall"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Font_Showcase"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Showcase"
							"XPos"						"3"
							"YPos"						"rs1-3"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"24"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"LabelText"					"1234567890 - The quick brown fox jumps over the lazy dog"
							"Font"						"Showcase_Eternal"
							"TextAlignment"				"west"
							"FGColor"					"Gray"
						}
						"Separator"
						{
							"ControlName"				"EditablePanel"
							"FieldName"					"Separator"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"1"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"paintBackground"			"1"
							"paintBackgroundtype"		"3"
							"BGcolor_Override"			"Gray"
						}
					}
                    "Roboto"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Roboto"
						"XPos"							"0"
						"YPos"							"3"
						"ZPos"							"0"
						"Wide"							"f0"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"

						"Pin_To_Sibling"				"Eternal"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Font_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Font_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_font_prim_roboto"
							"LabelText"					""
							"TextAlignment"				"center"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"1"

							"DefaultBGColor_Override"	"TransparentLightestBlack"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Font_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Name"
							"XPos"						"3"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"AllCaps"					"1"
							"LabelText"					"Roboto"
							"Font"						"HudFontSmall"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Font_Showcase"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Font_Showcase"
							"XPos"						"3"
							"YPos"						"rs1-3"
							"ZPos"						"1"
							"Wide"						"f25"
							"Tall"						"24"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"LabelText"					"1234567890 - The quick brown fox jumps over the lazy dog"
							"Font"						"Showcase_Roboto"
							"TextAlignment"				"west"
							"FGColor"					"Gray"
						}
						"Separator"
						{
							"ControlName"				"EditablePanel"
							"FieldName"					"Separator"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"0"
							"Wide"						"f0"
							"Tall"						"1"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"mouseinputenabled"			"0"
							"paintBackground"			"1"
							"paintBackgroundtype"		"3"
							"BGcolor_Override"			"Gray"
						}
					}
                }
			}
		}
	}
}