"Resource\OptionsSubVideo.res"
{
    // MARK: Additional Gamma/TV Mode Options
    "GammaSlider"
    {
        "ControlName"           "CCvarSlider"
        "fieldName"             "GammaSlider"
        "xpos"                  "17"
        "ypos"                  "160"
        "wide"                  "200"
        "tall"                  "40"
        "visible"               "1"
        "enabled"               "1"
        "tabPosition"           "1"
        "leftText"              "#GameUI_LIGHT"
        "rightText"             "#GameUI_DARK"
        "cvar_name"             "mat_monitorgamma"
        "minvalue"              "0"
        "maxvalue"              "3"
    }
    "GammaLabel"
    {
        "ControlName"                   "Label"
        "fieldName"                     "GammaLabel"
        "xpos"                          "-1"
        "ypos"                          "18"
        "wide"                          "108"
        "tall"                          "24"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "#GameUI_Gamma"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "wrap"                          "0"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "GammaSlider"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "TVExpSlider"
    {
        "ControlName"                   "CCvarSlider"
        "fieldName"                     "TVExpSlider"
        "xpos"                          "0"
        "ypos"                          "20"
        "wide"                          "200"
        "tall"                          "40"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "1"
        "leftText"                      "#GameUI_LIGHT"
        "rightText"                     "#GameUI_DARK"
        "cvar_name"                     "mat_monitorgamma_tv_exp"
        "minvalue"                      "0"
        "maxvalue"                      "100"
        "pin_to_sibling"                "GammaSlider"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
    }
    "TvExpLabel"
    {
        "ControlName"                   "Label"
        "fieldName"                     "TvExpLabel"
        "xpos"                          "-1"
        "ypos"                          "18"
        "wide"                          "108"
        "tall"                          "24"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "TV exponent"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "wrap"                          "0"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "TVExpSlider"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "TVEnabledLabel"
    {
        "ControlName"                   "Label"
        "fieldName"                     "TVEnabledLabel"
        "xpos"                          "-1"
        "ypos"                          "10"
        "wide"                          "218"
        "tall"                          "48"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "TV options require mat_monitorgamma_tv_enabled 1"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "wrap"                          "1"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "TVExpSlider"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
    }
    "TVRangeMinSlider"
    {
        "ControlName"                   "CCvarSlider"
        "fieldName"                     "TVRangeMinSlider"
        "xpos"                          "0"
        "ypos"                          "20"
        "wide"                          "200"
        "tall"                          "40"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "1"
        "leftText"                      "#GameUI_LIGHT"
        "rightText"                     "#GameUI_DARK"
        "cvar_name"                     "mat_monitorgamma_tv_range_min"
        "minvalue"                      "0"
        "maxvalue"                      "255"
        "pin_to_sibling"                "TVRangeMaxSlider"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "TvRangeMinLabel"
    {
        "ControlName"                   "Label"
        "fieldName"                     "TvRangeMinLabel"
        "xpos"                          "-1"
        "ypos"                          "18"
        "wide"                          "108"
        "tall"                          "24"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "TV range min"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "wrap"                          "0"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "TVRangeMinSlider"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "TVRangeMaxSlider"
    {
        "ControlName"                   "CCvarSlider"
        "fieldName"                     "TVRangeMaxSlider"
        "xpos"                          "30"
        "ypos"                          "0"
        "wide"                          "200"
        "tall"                          "40"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "1"
        "leftText"                      "#GameUI_LIGHT"
        "rightText"                     "#GameUI_DARK"
        "cvar_name"                     "mat_monitorgamma_tv_range_max"
        "minvalue"                      "0"
        "maxvalue"                      "255"
        "pin_to_sibling"                "TVExpSlider"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPRIGHT"
    }
    "TvRangeMaxLabel"
    {
        "ControlName"                   "Label"
        "fieldName"                     "TvRangeMaxLabel"
        "xpos"                          "-1"
        "ypos"                          "18"
        "wide"                          "108"
        "tall"                          "24"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "TV range max"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "wrap"                          "0"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "TVRangeMaxSlider"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    // MARK: Normal Menu
    "Label1"	// resolution label
    {
        "ControlName"           "Label"
        "fieldName"             "Label1"
        "xpos"                  "36"
        "ypos"                  "24"
        "wide"                  "160"
        "tall"                  "24"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "tabPosition"           "0"
        "labelText"             "#GameUI_Resolution"
        "textAlignment"         "west"
        "associate"             "Resolution"
        "dulltext"              "0"
        "brighttext"            "0"
        "wrap"                  "0"
    }
    "Resolution"
    {
        "ControlName"               "ComboBox"
        "fieldName"                 "Resolution"
        "xpos"                      "36"
        "ypos"                      "50"
        "wide"                      "160"
        "tall"                      "24"
        "autoResize"                "0"
        "pinCorner"                 "0"
        "visible"                   "1"
        "enabled"                   "1"
        "tabPosition"               "1"
        "textHidden"                "0"
        "editable"                  "0"
        "maxchars"                  "-1"
        "NumericInputOnly"          "0"
        "unicode"                   "0"
    }
    "Label4"	// display mode label
    {
        "ControlName"           "Label"
        "fieldName"             "Label4"
        "xpos"                  "254"
        "ypos"                  "24"
        "wide"                  "160"
        "tall"                  "24"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "tabPosition"           "0"
        "labelText"             "#GameUI_DisplayMode"
        "textAlignment"         "west"
        "associate"             "DisplayModeCombo"
        "dulltext"              "0"
        "brighttext"            "0"
        "wrap"                  "0"
    }
    "DisplayModeCombo"
    {
        "ControlName"               "ComboBox"
        "fieldName"                 "DisplayModeCombo"
        "xpos"                      "254"
        "ypos"                      "50"
        "wide"                      "182"
        "tall"                      "24"
        "autoResize"                "0"
        "pinCorner"                 "0"
        "visible"                   "1"
        "enabled"                   "1"
        "tabPosition"               "2"
        "textHidden"                "0"
        "editable"                  "0"
        "maxchars"                  "-1"
        "NumericInputOnly"          "0"
        "unicode"                   "0"
    }
    "AspectRatioLabel"
    {
        "ControlName"           "Label"
        "fieldName"             "AspectRatioLabel"
        "xpos"                  "36"
        "ypos"                  "100-23"
        "wide"                  "160"
        "tall"                  "24"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "tabPosition"           "0"
        "labelText"             "#GameUI_AspectRatio"
        "textAlignment"         "west"
        "associate"             "AspectRatio"
        "dulltext"              "0"
        "brighttext"            "0"
        "wrap"                  "0"
    }
    "AspectRatio"
    {
        "ControlName"               "ComboBox"
        "fieldName"                 "AspectRatio"
        "xpos"                      "36"
        "ypos"                      "126-23"
        "wide"                      "160"
        "tall"                      "24"
        "autoResize"                "0"
        "pinCorner"                 "0"
        "visible"                   "1"
        "enabled"                   "1"
        "tabPosition"               "3"
        "textHidden"                "0"
        "editable"                  "0"
        "maxchars"                  "-1"
        "NumericInputOnly"          "0"
        "unicode"                   "0"
    }
    "GammaButton"
    {
        "ControlName"                   "Button"
        "fieldName"                     "GammaButton"
        "xpos"                          "0"
        "ypos"                          "4"
        "wide"                          "182"
        "tall"                          "24"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "0"
        "tabPosition"                   "4"
        "labelText"                     "#GameUI_AdjustGamma"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "wrap"                          "0"
        "Default"                       "0"
        "pin_to_sibling"                "DisplayModeCombo"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
    }
    "AdvancedButton"
    {
        "ControlName"                   "Button"
        "fieldName"                     "AdvancedButton"
        "xpos"                          "0"
        "ypos"                          "4"
        "wide"                          "182"
        "tall"                          "24"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "5"
        "labelText"                     "#GameUI_AdvancedEllipsis"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "wrap"                          "0"
        "Default"                       "0"
        "pin_to_sibling"                "GammaButton"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
    }
    "ThirdPartyVideoCredits"
    {
        "ControlName"           "URLButton"
        "fieldName"             "ThirdPartyVideoCredits"
        "xpos"                  "254+5"
        "ypos"                  "270+5"
        "wide"                  "225"
        "tall"                  "24"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "tabPosition"           "6"
        "labelText"             "#GameUI_ThirdPartyTechCredits"
        "textAlignment"         "west"
        "dulltext"              "0"
        "brighttext"            "0"
        "wrap"                  "0"
        "Default"               "0"
        "selected"              "0"
    }
    // MARK: UNUSED
    "Renderer"	// not used
    {
        "ControlName"               "ComboBox"
        "fieldName"                 "Renderer"
        "xpos"                      "40"
        "ypos"                      "52"
        "wide"                      "160"
        "tall"                      "24"
        "autoResize"                "0"
        "pinCorner"                 "0"
        "visible"                   "0"
        "enabled"                   "1"
        "tabPosition"               "1"
        "textHidden"                "0"
        "editable"                  "0"
        "maxchars"                  "-1"
        "NumericInputOnly"          "0"
        "unicode"                   "0"
    }
    "Label2"	// not used
    {
        "ControlName"           "Label"
        "fieldName"             "Label2"
        "xpos"                  "40"
        "ypos"                  "28"
        "wide"                  "160"
        "tall"                  "24"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "1"
        "tabPosition"           "0"
        "labelText"             "#GameUI_Renderer"
        "textAlignment"         "west"
        "dulltext"              "0"
        "brighttext"            "0"
        "wrap"                  "0"
    }
    "HDContentButton"	// not used
    {
        "ControlName"                       "CheckButton"
        "fieldName"                         "HDContentButton"
        "xpos"                              "29"
        "ypos"                              "240"
        "wide"                              "250"
        "tall"                              "24"
        "autoResize"                        "0"
        "RoundedCorners"                    "15"
        "visible"                           "0"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "#GameUI_HDContent"
        "textAlignment"                     "west"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "wrap"                              "0"
        "centerwrap"                        "0"
        "textinsetx"                        "6"
        "textinsety"                        "0"
        "auto_wide_tocontents"              "0"
        "use_proportional_insets"           "0"
        "Default"                           "0"
    }
    "VRModeLabel"	// not used
    {
        "ControlName"           "Label"
        "fieldName"             "VRModeLabel"
        "xpos"                  "36"
        "ypos"                  "170"
        "wide"                  "160"
        "tall"                  "24"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "tabPosition"           "0"
        "labelText"             "#GameUI_VRMode"
        "textAlignment"         "west"
        "associate"             "VRMode"
        "dulltext"              "0"
        "brighttext"            "0"
        "wrap"                  "0"
    }
    "VRMode"	// not used
    {
        "ControlName"               "ComboBox"
        "fieldName"                 "VRMode"
        "xpos"                      "36"
        "ypos"                      "196"
        "wide"                      "160"
        "tall"                      "24"
        "autoResize"                "0"
        "pinCorner"                 "0"
        "visible"                   "1"
        "enabled"                   "1"
        "tabPosition"               "3"
        "textHidden"                "0"
        "editable"                  "0"
        "maxchars"                  "-1"
        "NumericInputOnly"          "0"
        "unicode"                   "0"
    }
    "BenchmarkButton"	// unused
    {
        "ControlName"           "Button"
        "fieldName"             "BenchmarkButton"
        "xpos"                  "39"
        "ypos"                  "230"
        "wide"                  "130"
        "tall"                  "24"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "1"
        "tabPosition"           "0"
        "labelText"             "#GameUI_LaunchBenchmarkVideoPanel"
        "textAlignment"         "west"
        "dulltext"              "0"
        "brighttext"            "0"
        "wrap"                  "0"
        "Default"               "0"
    }
    "Gamma label"	// unused
    {
        "ControlName"           "Label"
        "fieldName"             "Gamma label"
        "xpos"                  "257"
        "ypos"                  "117"
        "wide"                  "140"
        "tall"                  "24"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "1"
        "tabPosition"           "0"
        "labelText"             "#GameUI_Gamma"
        "textAlignment"         "west"
        "dulltext"              "0"
        "brighttext"            "0"
        "wrap"                  "0"
    }
}