"#base"         "../dev/reload_scheme.res"
"#base"         "inventorybackground_charinfo_override.res"
"#base"         "inventorybackground.res"
"Resource/UI/CharInfoPanel.res"
{
    "Character_Info"
    {
        "ControlName"                               "EditablePanel"
        "FieldName"                                 "Character_Info"
        "XPos"                                      "0"
        "YPos"                                      "0"
        "ZPos"                                      "0"
        "Wide"                                      "f0"
        "Tall"                                      "480"
        "Visible"                                   "1"
        "Enabled"                                   "1"
        "SetTitleBarVisible"                        "1"
        "PaintBackgroundType"                       "0"
        "BGColor_Override"                          "BLANK"
        "InFocus_BGColor_Override"                  "BLANK"
        "OutOfFocus_BGColor_Override"               "BLANK"
        "title"                                     "#CharInfoAndSetup"
        "title_font"                                "HudFontMediumBold"
        "titletextinsetX"                           "40"
        "titletextinsetY"                           "-4"
        "titlebarfgcolor_override"                  "Blank"
        "titlebardisabledfgcolor_override"          "Blank"
        "titlebarbgcolor_override"                  "Blank"
        "clientinsetx_override"                     "0"
        "sheetinset_bottom"                         "18"
    }
    "HeaderBG"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "HeaderBG"
        "XPos"                          "cs-0.5"
        "YPos"                          "0"
        "ZPos"                          "-2"
        "Wide"                          "f0"
        "Tall"                          "f0"
        "Visible"                       "1"
        "Enabled"                       "1"
        "mouseinputenabled"             "0"
        "paintBackground"               "1"
        "paintBackgroundtype"           "0"
        "BGcolor_Override"              "Background_Main"
    }
    "Sheet"
    {
        "ControlName"               "EditablePanel"
        "FieldName"                 "Sheet"
        "tabxindent"                "5"
        "tabxdelta"                 "99999"
        "tabwidth"                  "0"
        "tabheight"                 "18"
        "transition_time"           "0"
        "yoffset"                   "0"
        "TabsKV"
        {
            "TextInsetX"                    "0"
            "Font"                          ""
            "selectedcolor"                 "BLANK"
            "unselectedcolor"               "BLANK"
            "PaintBackground"               "0"
            "activeborder_override"         "NoBorder"
            "normalborder_override"         "NoBorder"
        }
    }
    "BackButton"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "BackButton"
        "xpos"                              "5"
        "ypos"                              "r45"
        "zpos"                              "2"
        "wide"                              "76"
        "tall"                              "22"
        "visible"                           "1"
        "enabled"                           "1"
        "labelText"                         "BACK (&Q)"
        "font"                              "Menu_Small"
        "textAlignment"                     "center"
        "default"                           "0"
        "Command"                           "back"
        "AllCaps"                           "1"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "DefaultBGColor_Override"           "Button_Dark"
        "ArmedBGColor_Override"             "Button_Hover"
        "DepressedBGColor_Override"         "Button_Dark"
    }
    "CloseButton"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "CloseButton"
        "xpos"                              "rs1-5"
        "ypos"                              "r45"
        "zpos"                              "2"
        "wide"                              "76"
        "tall"                              "22"
        "visible"                           "1"
        "enabled"                           "1"
        "labelText"                         "CLOSE (&E)"
        "font"                              "Menu_Small"
        "textAlignment"                     "center"
        "default"                           "0"
        "Command"                           "close"
        "AllCaps"                           "1"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "DefaultBGColor_Override"           "Button_Dark"
        "ArmedBGColor_Override"             "Button_Hover"
        "DepressedBGColor_Override"         "Button_Dark"
    }
    "NotificationsPresentPanel"
    {
        "ControlName"           "CNotificationsPresentPanel"
        "FieldName"             "NotificationsPresentPanel"
        "XPos"                  "r200"
        "YPos"                  "10"
        "ZPos"                  "10000"
        "Wide"                  "190"
        "Tall"                  "50"
        "Visible"               "0"
        "Enabled"               "1"
    }
    "ReloadSchemeButton"
    {
        "YPos"          "30"
    }
}