
"Resource/UI/ClassSelection_casual.res"
{
        "ClassesAnchor"
        {
            "ControlName"								"Panel"
            "FieldName"									"ClassesAnchor"
            "XPos"										"cs-0.5"
            "YPos"										"cs-0.5-40"
            "zpos"  "15"
            "Wide"										"1"
            "Tall"										"1"
            //"zpos"  "10"
            "Visible"									"0"
            "Enabled"									"1"
            "bgcolor_override"  "blank"
        }

        "Scout"
        {
            "ControlName"								"CExImageButton"
            "FieldName"									"Scout"
            "XPos"										"0"
            "YPos"										"0"
            "ZPos"										"10"
            "Wide"										"78"
            "Tall"										"78"
            "Visible"									"1"
            "Enabled"									"1"
            "LabelText"									"1" // Scout Icon
            "TextAlignment"								"center"
            "Command"									"joinclass scout"
            "Font"										"ClassSymbols80"
            "stayselectedonclick"						"1"
            "selectonhover"								"1"
            "KeyboardInputEnabled"						"0"

            "PaintBackground"							"0"
            "FGColor"									"White"
            "DefaultFGColor_Override"					"White"
            "ArmedFGColor_Override"						"98 219 220 255"
            "DepressedFGColor_Override"					"98 219 220 255"
            "selectedFGColor_override"					"98 219 220 255"

            "Pin_To_Sibling"							"Soldier"
            "pin_corner_to_sibling" "PIN_CENTER_RIGHT"
            "pin_to_sibling_corner" "PIN_CENTER_LEFT"
        }
        "NumScout"
        {
            "ControlName"								"CExLabel"
            "FieldName"									"NumScout"
            "XPos"										"-2"
            "YPos"										"-15"
            "Wide"										"50"
            "Tall"										"36"
            "ZPos"										"6"
            "Visible"									"1"
            "Enabled"									"1"
            "TextAlignment"								"center"
            "LabelText"									"%numScout%"
            "Font"										"JumpHUD_Secondary_Font"
            "FGColor"									"TransparentLightWhite"

            "Pin_To_Sibling"							"Scout"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_BOTTOM"
        }
        "MvMUpgradeImageScout"
        {
            "ControlName"								"ImagePanel"
            "FieldName"									"MvMUpgradeImageScout"
            "XPos"										"2"
            "YPos"										"1"
            "ZPos"										"10"
            "Wide"										"8"
            "Tall"										"8"
            "Visible"									"0"
            "Enabled"									"1"
            "Image"										"mvm/class_upgraded"
            "ScaleImage"								"1"

            "Pin_To_Sibling"							"Scout"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_LEFT"
        }
        "Soldier"
        {
            "ControlName"								"CExImageButton"
            "FieldName"									"Soldier"
            "XPos"										"0"
            "YPos"										"0"
            "ZPos"										"10"
            "Wide"										"78"
            "Tall"										"78"
            "Visible"									"1"
            "Enabled"									"1"
            "LabelText"									"2" // Soldier Icon
            "TextAlignment"								"center"
            "Command"									"joinclass Soldier"
            "Font"										"ClassSymbols80"
            "stayselectedonclick"						"1"
            "selectonhover"								"1"
            "KeyboardInputEnabled"						"0"

            "PaintBackground"							"0"
            "FGColor"									"White"
            "DefaultFGColor_Override"					"White"
            "ArmedFGColor_Override"						"98 219 220 255"
            "DepressedFGColor_Override"					"98 219 220 255"
            "selectedFGColor_override"					"98 219 220 255"

            "Pin_To_Sibling"							"Pyro"
            "pin_corner_to_sibling" "PIN_CENTER_RIGHT"
            "pin_to_sibling_corner" "PIN_CENTER_LEFT"
        }
        "NumSoldier"
        {
            "ControlName"								"CExLabel"
            "FieldName"									"NumSoldier"
            "XPos"										"-2"
            "YPos"										"-15"
            "Wide"										"50"
            "Tall"										"36"
            "ZPos"										"6"
            "Visible"									"1"
            "Enabled"									"1"
            "TextAlignment"								"center"
            "LabelText"									"%numSoldier%"
            "Font"										"JumpHUD_Secondary_Font"
            "FGColor"									"TransparentLightWhite"

            "Pin_To_Sibling"							"Soldier"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_BOTTOM"
        }
        "MvMUpgradeImageSoldier"
        {
            "ControlName"								"ImagePanel"
            "FieldName"									"MvMUpgradeImageSoldier"
            "XPos"										"2"
            "YPos"										"1"
            "ZPos"										"10"
            "Wide"										"8"
            "Tall"										"8"
            "Visible"									"0"
            "Enabled"									"1"
            "Image"										"mvm/class_upgraded"
            "ScaleImage"								"1"

            "Pin_To_Sibling"							"Soldier"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_LEFT"
        }
        "Pyro"
        {
            "ControlName"								"CExImageButton"
            "FieldName"									"Pyro"
            "XPos"										"0"
            "YPos"										"10"
            "ZPos"										"10"
            "Wide"										"78"
            "Tall"										"78"
            "Visible"									"1"
            "Enabled"									"1"
            "LabelText"									"3" // Pyro Icon
            "TextAlignment"								"center"
            "Command"									"joinclass Pyro"
            "Font"										"ClassSymbols80"
            "stayselectedonclick"						"1"
            "selectonhover"								"1"
            "KeyboardInputEnabled"						"0"

            "PaintBackground"							"0"
            "FGColor"									"White"
            "DefaultFGColor_Override"					"White"
            "ArmedFGColor_Override"						"98 219 220 255"
            "DepressedFGColor_Override"					"98 219 220 255"
            "selectedFGColor_override"					"98 219 220 255"

            "Pin_To_Sibling"							"Engineer"
            "pin_corner_to_sibling" "PIN_CENTER_BOTTOM"
            "pin_to_sibling_corner" "PIN_CENTER_TOP"
        }
        "NumPyro"
        {
            "ControlName"								"CExLabel"
            "FieldName"									"NumPyro"
            "XPos"										"-2"
            "YPos"										"-15"
            "Wide"										"50"
            "Tall"										"36"
            "ZPos"										"6"
            "Visible"									"1"
            "Enabled"									"1"
            "TextAlignment"								"center"
            "LabelText"									"%numPyro%"
            "Font"										"JumpHUD_Secondary_Font"
            "FGColor"									"TransparentLightWhite"

            "Pin_To_Sibling"							"Pyro"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_BOTTOM"
        }
        "MvMUpgradeImagePyro"
        {
            "ControlName"								"ImagePanel"
            "FieldName"									"MvMUpgradeImagePyro"
            "XPos"										"2"
            "YPos"										"1"
            "ZPos"										"10"
            "Wide"										"8"
            "Tall"										"8"
            "Visible"									"0"
            "Enabled"									"1"
            "Image"										"mvm/class_upgraded"
            "ScaleImage"								"1"

            "Pin_To_Sibling"							"Pyro"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_LEFT"
        }
        "Demoman"
        {
            "ControlName"								"CExImageButton"
            "FieldName"									"Demoman"
            "XPos"										"0"
            "YPos"										"0"
            "ZPos"										"10"
            "Wide"										"78"
            "Tall"										"78"
            "Visible"									"1"
            "Enabled"									"1"
            "LabelText"									"4" // Demoman Icon
            "TextAlignment"								"center"
            "Command"									"joinclass Demoman"
            "Font"										"ClassSymbols80"
            "stayselectedonclick"						"1"
            "selectonhover"								"1"
            "KeyboardInputEnabled"						"0"

            "PaintBackground"							"0"
            "FGColor"									"White"
            "DefaultFGColor_Override"					"White"
            "ArmedFGColor_Override"						"98 219 220 255"
            "DepressedFGColor_Override"					"98 219 220 255"
            "selectedFGColor_override"					"98 219 220 255"

            "Pin_To_Sibling"							"HeavyWeapons"
            "pin_corner_to_sibling" "PIN_CENTER_RIGHT"
            "pin_to_sibling_corner" "PIN_CENTER_LEFT"
        }
        "NumDemoman"
        {
            "ControlName"								"CExLabel"
            "FieldName"									"NumDemoman"
            "XPos"										"-2"
            "YPos"										"-15"
            "Wide"										"50"
            "Tall"										"36"
            "ZPos"										"6"
            "Visible"									"1"
            "Enabled"									"1"
            "TextAlignment"								"center"
            "LabelText"									"%numDemoman%"
            "Font"										"JumpHUD_Secondary_Font"
            "FGColor"									"TransparentLightWhite"

            "Pin_To_Sibling"							"Demoman"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_BOTTOM"
        }
        "MvMUpgradeImageDemoman"
        {
            "ControlName"								"ImagePanel"
            "FieldName"									"MvMUpgradeImageDemoman"
            "XPos"										"2"
            "YPos"										"1"
            "ZPos"										"10"
            "Wide"										"8"
            "Tall"										"8"
            "Visible"									"0"
            "Enabled"									"1"
            "Image"										"mvm/class_upgraded"
            "ScaleImage"								"1"

            "Pin_To_Sibling"							"Demoman"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_LEFT"
        }
        "HeavyWeapons"
        {
            "ControlName"								"CExImageButton"
            "FieldName"									"HeavyWeapons"
            "XPos"										"0"
            "YPos"										"0"
            "ZPos"										"10"
            "Wide"										"78"
            "Tall"										"78"
            "Visible"									"1"
            "Enabled"									"1"
            "LabelText"									"5" // Heavy Icon
            "TextAlignment"								"center"
            "Command"									"joinclass HeavyWeapons"
            "Font"										"ClassSymbols80"
            "stayselectedonclick"						"1"
            "selectonhover"								"1"
            "KeyboardInputEnabled"						"0"

            "PaintBackground"							"0"
            "FGColor"									"White"
            "DefaultFGColor_Override"					"White"
            "ArmedFGColor_Override"						"98 219 220 255"
            "DepressedFGColor_Override"					"98 219 220 255"
            "selectedFGColor_override"					"98 219 220 255"

            "Pin_To_Sibling"							"ClassesAnchor"
            "pin_corner_to_sibling" "PIN_CENTER_TOP"
            "pin_to_sibling_corner" "PIN_CENTER_TOP"
        }
        "NumHeavyWeapons"
        {
            "ControlName"								"CExLabel"
            "FieldName"									"NumHeavyWeapons"
            "XPos"										"-2"
            "YPos"										"-15"
            "Wide"										"50"
            "Tall"										"36"
            "ZPos"										"6"
            "Visible"									"1"
            "Enabled"									"1"
            "TextAlignment"								"center"
            "LabelText"									"%numHeavy%"
            "Font"										"JumpHUD_Secondary_Font"
            "FGColor"									"TransparentLightWhite"

            "Pin_To_Sibling"							"HeavyWeapons"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_BOTTOM"
        }
        "MvMUpgradeImageHeavyWeapons"
        {
            "ControlName"								"ImagePanel"
            "FieldName"									"MvMUpgradeImageHeavyWeapons"
            "XPos"										"2"
            "YPos"										"1"
            "ZPos"										"10"
            "Wide"										"8"
            "Tall"										"8"
            "Visible"									"0"
            "Enabled"									"1"
            "Image"										"mvm/class_upgraded"
            "ScaleImage"								"1"

            "Pin_To_Sibling"							"HeavyWeapons"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_LEFT"
        }
        "Engineer"
        {
            "ControlName"								"CExImageButton"
            "FieldName"									"Engineer"
            "XPos"										"0"
            "YPos"										"0"
            "ZPos"										"10"
            "Wide"										"78"
            "Tall"										"78"
            "Visible"									"1"
            "Enabled"									"1"
            "LabelText"									"6" // Engineer Icon
            "TextAlignment"								"center"
            "Command"									"joinclass Engineer"
            "Font"										"ClassSymbols80"
            "stayselectedonclick"						"1"
            "selectonhover"								"1"
            "KeyboardInputEnabled"						"0"

            "PaintBackground"							"0"
            "FGColor"									"White"
            "DefaultFGColor_Override"					"White"
            "ArmedFGColor_Override"						"98 219 220 255"
            "DepressedFGColor_Override"					"98 219 220 255"
            "selectedFGColor_override"					"98 219 220 255"

            "Pin_To_Sibling"							"HeavyWeapons"
            "pin_corner_to_sibling" "PIN_CENTER_LEFT"
            "pin_to_sibling_corner" "PIN_CENTER_RIGHT"
        }
        "NumEngineer"
        {
            "ControlName"								"CExLabel"
            "FieldName"									"NumEngineer"
            "XPos"										"-2"
            "YPos"										"-15"
            "Wide"										"50"
            "Tall"										"36"
            "ZPos"										"6"
            "Visible"									"1"
            "Enabled"									"1"
            "TextAlignment"								"center"
            "LabelText"									"%numEngineer%"
            "Font"										"JumpHUD_Secondary_Font"
            "FGColor"									"TransparentLightWhite"

            "Pin_To_Sibling"							"Engineer"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_BOTTOM"
        }
        "MvMUpgradeImageEngineer"
        {
            "ControlName"								"ImagePanel"
            "FieldName"									"MvMUpgradeImageEngineer"
            "XPos"										"2"
            "YPos"										"1"
            "ZPos"										"10"
            "Wide"										"8"
            "Tall"										"8"
            "Visible"									"0"
            "Enabled"									"1"
            "Image"										"mvm/class_upgraded"
            "ScaleImage"								"1"

            "Pin_To_Sibling"							"Engineer"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_LEFT"
        }
        "Medic"
        {
            "ControlName"								"CExImageButton"
            "FieldName"									"Medic"
            "XPos"										"0"
            "YPos"										"10"
            "ZPos"										"10"
            "Wide"										"78"
            "Tall"										"78"
            "Visible"									"1"
            "Enabled"									"1"
            "LabelText"									"7" // Medic Icon
            "TextAlignment"								"center"
            "Command"									"joinclass Medic"
            "Font"										"ClassSymbols80"
            "stayselectedonclick"						"1"
            "selectonhover"								"1"
            "KeyboardInputEnabled"						"0"

            "PaintBackground"							"0"
            "FGColor"									"White"
            "DefaultFGColor_Override"					"White"
            "ArmedFGColor_Override"						"98 219 220 255"
            "DepressedFGColor_Override"					"98 219 220 255"
            "selectedFGColor_override"					"98 219 220 255"

            "Pin_To_Sibling"							"Demoman"
            "pin_corner_to_sibling" "PIN_CENTER_TOP"
            "pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
        }
        "NumMedic"
        {
            "ControlName"								"CExLabel"
            "FieldName"									"NumMedic"
            "XPos"										"-2"
            "YPos"										"-15"
            "Wide"										"50"
            "Tall"										"36"
            "ZPos"										"6"
            "Visible"									"1"
            "Enabled"									"1"
            "TextAlignment"								"center"
            "LabelText"									"%numMedic%"
            "Font"										"JumpHUD_Secondary_Font"
            "FGColor"									"TransparentLightWhite"

            "Pin_To_Sibling"							"Medic"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_BOTTOM"
        }
        "MvMUpgradeImageMedic"
        {
            "ControlName"								"ImagePanel"
            "FieldName"									"MvMUpgradeImageMedic"
            "XPos"										"2"
            "YPos"										"1"
            "ZPos"										"10"
            "Wide"										"8"
            "Tall"										"8"
            "Visible"									"0"
            "Enabled"									"1"
            "Image"										"mvm/class_upgraded"
            "ScaleImage"								"1"

            "Pin_To_Sibling"							"Medic"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_LEFT"
        }
        "Sniper"
        {
            "ControlName"								"CExImageButton"
            "FieldName"									"Sniper"
            "XPos"										"0"
            "YPos"										"0"
            "ZPos"										"10"
            "Wide"										"78"
            "Tall"										"78"
            "Visible"									"1"
            "Enabled"									"1"
            "LabelText"									"8" // Sniper Icon
            "TextAlignment"								"center"
            "Command"									"joinclass Sniper"
            "Font"										"ClassSymbols80"
            "stayselectedonclick"						"1"
            "selectonhover"								"1"
            "KeyboardInputEnabled"						"0"

            "PaintBackground"							"0"
            "FGColor"									"White"
            "DefaultFGColor_Override"					"White"
            "ArmedFGColor_Override"						"98 219 220 255"
            "DepressedFGColor_Override"					"98 219 220 255"
            "selectedFGColor_override"					"98 219 220 255"

            "Pin_To_Sibling"							"Medic"
            "pin_corner_to_sibling" "PIN_CENTER_LEFT"
            "pin_to_sibling_corner" "PIN_CENTER_RIGHT"
        }
        "NumSniper"
        {
            "ControlName"								"CExLabel"
            "FieldName"									"NumSniper"
            "XPos"										"-2"
            "YPos"										"-15"
            "Wide"										"50"
            "Tall"										"36"
            "ZPos"										"6"
            "Visible"									"1"
            "Enabled"									"1"
            "TextAlignment"								"center"
            "LabelText"									"%numSniper%"
            "Font"										"JumpHUD_Secondary_Font"
            "FGColor"									"TransparentLightWhite"

            "Pin_To_Sibling"							"Sniper"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_BOTTOM"
        }
        "MvMUpgradeImageSniper"
        {
            "ControlName"								"ImagePanel"
            "FieldName"									"MvMUpgradeImageSniper"
            "XPos"										"2"
            "YPos"										"1"
            "ZPos"										"10"
            "Wide"										"8"
            "Tall"										"8"
            "Visible"									"0"
            "Enabled"									"1"
            "Image"										"mvm/class_upgraded"
            "ScaleImage"								"1"

            "Pin_To_Sibling"							"Sniper"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_LEFT"
        }
        "Spy"
        {
            "ControlName"								"CExImageButton"
            "FieldName"									"Spy"
            "XPos"										"0"
            "YPos"										"0"
            "ZPos"										"10"
            "Wide"										"78"
            "Tall"										"78"
            "Visible"									"1"
            "Enabled"									"1"
            "LabelText"									"9" // Spy Icon
            "TextAlignment"								"center"
            "Command"									"joinclass Spy"
            "Font"										"ClassSymbols80"
            "stayselectedonclick"						"1"
            "selectonhover"								"1"
            "KeyboardInputEnabled"						"0"

            "PaintBackground"							"0"
            "FGColor"									"White"
            "DefaultFGColor_Override"					"White"
            "ArmedFGColor_Override"						"98 219 220 255"
            "DepressedFGColor_Override"					"98 219 220 255"
            "selectedFGColor_override"					"98 219 220 255"

            "Pin_To_Sibling"							"Sniper"
            "pin_corner_to_sibling" "PIN_CENTER_LEFT"
            "pin_to_sibling_corner" "PIN_CENTER_RIGHT"
        }
        "NumSpy"
        {
            "ControlName"								"CExLabel"
            "FieldName"									"NumSpy"
            "XPos"										"-2"
            "YPos"										"-15"
            "Wide"										"50"
            "Tall"										"36"
            "ZPos"										"6"
            "Visible"									"1"
            "Enabled"									"1"
            "TextAlignment"								"center"
            "LabelText"									"%numSpy%"
            "Font"										"JumpHUD_Secondary_Font"
            "FGColor"									"TransparentLightWhite"

            "Pin_To_Sibling"							"Spy"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_BOTTOM"
        }
        "MvMUpgradeImageSpy"
        {
            "ControlName"								"ImagePanel"
            "FieldName"									"MvMUpgradeImageSpy"
            "XPos"										"2"
            "YPos"										"1"
            "ZPos"										"10"
            "Wide"										"8"
            "Tall"										"8"
            "Visible"									"0"
            "Enabled"									"1"
            "Image"										"mvm/class_upgraded"
            "ScaleImage"								"1"

            "Pin_To_Sibling"							"spy"
            "Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
            "Pin_To_Sibling_Corner"						"PIN_CENTER_LEFT"
        }

}