"speedo_hspeedo_base.res"
{
    "CurrentTime"
    {
        "controlName"           "EditablePanel"
        "visible"               "1"
        "enabled"               "1"
        "xpos"                  "4"
        "ypos"                  "4"
        "wide"                  "96"
        "tall"                  "18"
        "Icon"
        {
            "ControlName"                   "CExLabel"
            "FieldName"                     "Icon"
            "XPos"                          "0"
            "YPos"                          "0"
            "ZPos"                          "1"
            "Wide"                          "p0.25"
            "Tall"                          "f0"
            "Visible"                       "1"
            "Enabled"                       "1"
            "TextAlignment"                 "center"
            "LabelText"                     "-"
            "Font"                          "Symbols20"
            "FGColor"                       "White"
            "proportionalToParent"          "1"
        }
        "IconShadow"
        {
            "ControlName"                   "CExLabel"
            "FieldName"                     "IconShadow"
            "XPos"                          "1"
            "YPos"                          "1"
            "ZPos"                          "1"
            "Wide"                          "p0.25"
            "Tall"                          "f0"
            "Visible"                       "1"
            "Enabled"                       "1"
            "TextAlignment"                 "center"
            "LabelText"                     "-"
            "Font"                          "Symbols20"
            "FGColor"                       "Main_Shadow_Transparent"
            "proportionalToParent"          "1"
        }
        "Time"
        {
            "controlName"                   "EditablePanel"
            "visible"                       "1"
            "enabled"                       "1"
            "xpos"                          "p0.25"
            "ypos"                          "0"
            "wide"                          "p0.75"
            "tall"                          "f0"
            "proportionalToParent"          "1"
            "Digits_Container"
            {
                "controlName"                   "EditablePanel"
                "visible"                       "1"
                "enabled"                       "1"
                "wide"                          "f0"
                "tall"                          "f0"
                "xpos"                          "0"
                "ypos"                          "0"
                "proportionaltoparent"          "1"
                "d_l"
                {
                    "controlName"                   "CTFImagePanel"
                    "wide"                          "f0"
                    "tall"                          "f0"
                    "proportionaltoparent"          "1"
                    "image"                         "../speedo/time/d_l"
                }
                "d_r"
                {
                    "controlName"                   "CTFImagePanel"
                    "wide"                          "f0"
                    "tall"                          "f0"
                    "proportionaltoparent"          "1"
                    "image"                         "../speedo/time/d_r"
                }
            }
            "Shadows_Container"
            {
                "controlName"                   "EditablePanel"
                "visible"                       "1"
                "enabled"                       "1"
                "wide"                          "f0"
                "tall"                          "f0"
                "xpos"                          "1"
                "ypos"                          "1"
                "zpos"                          "-1"
                "proportionaltoparent"          "1"
                "d_l"
                {
                    "controlName"                   "CTFImagePanel"
                    "wide"                          "f0"
                    "tall"                          "f0"
                    "proportionaltoparent"          "1"
                    "image"                         "../speedo/time/d_l"
                    "drawcolor"                     "Main_Shadow"
                }
                "d_r"
                {
                    "controlName"                   "CTFImagePanel"
                    "wide"                          "f0"
                    "tall"                          "f0"
                    "proportionaltoparent"          "1"
                    "image"                         "../speedo/time/d_r"
                    "drawcolor"                     "Main_Shadow"
                }
            }
        }
    }
}