"Resource/UI/DisguiseStatusPanel.res"
{
	"ItemModelPanel"
	{
		"ControlName"								"CEmbeddedItemModelPanel"
		"FieldName"									"ItemModelPanel"
		"XPos"										"0"
		"YPos"										"0"
		"ZPos"										"1"
		"Wide"										"100"
		"Tall"										"100"
		"Visible"									"1"
		"Enabled"									"1"

		"useparentbg"								"1"
		"fov"										"54"
		"start_framed"								"1"
		"disable_manipulation"						"1"

		"Model"
		{
			"angles_x"								"10"
			"angles_y"								"130"
			"angles_z"								"0"
		}
	}
	"DisguiseStatusBG"
	{
		"ControlName"								"CTFImagePanel"
		"FieldName"									"DisguiseStatusBG"
		"XPos"										"cs-0.5"
		"YPos"										"rs1-74"
		"ZPos"										"-1"
		"Wide"										"140"
		"Tall"										"3"
		"Visible"									"1"
		"Enabled"									"1"
		"ProportionalToParent"						"1"
        "alpha" "175"

		"Image"										"../hud/color_panel_brown"
		"ScaleImage"								"1"
		"teambg_1"									"../hud/color_panel_brown"
		"teambg_2"									"../hud/color_panel_red"
		"teambg_3"									"../hud/color_panel_blu"

		"src_corner_height"							"15"
		"src_corner_width"							"15"
		"draw_corner_width"							"0"
		"draw_corner_height"						"0"
	}
	"DisguiseNameLabel"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"DisguiseNameLabel"
		"XPos"										"-40"
		"YPos"										"0"
		"ZPos"										"1"
		"Wide"										"95"
		"Tall"										"12"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"%disguisename%"
		"Font"										"TargetID_small"
		"TextAlignment"								"West"
		"FGColor"									"White"
		"alpha"										"255"

		"Pin_To_Sibling"							"DisguiseStatusBG"
		"Pin_Corner_To_Sibling"						"PIN_BOTTOMLEFT"
		"Pin_To_Sibling_Corner"						"PIN_TOPLEFT"
	}
    "DisguiseNameLabelShadow"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"DisguiseNameLabelShadow"
		"XPos"										"-1"
		"YPos"										"-1"
		"ZPos"										"1"
		"Wide"										"95"
		"Tall"										"12"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"%disguisename%"
		"Font"										"TargetID_small"
		"TextAlignment"								"West"
		"FGColor"									"Main_Shadow_Transparent"
		"alpha"										"255"

		"Pin_To_Sibling"							"DisguiseNameLabel"
	}
	"WeaponNameLabel"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"WeaponNameLabel"
		"XPos"										"-40"
		"YPos"										"-6"
		"ZPos"										"1"
		"Wide"										"95"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"%weaponname%"
		"Font"										"TargetID_Data_Small"
		"TextAlignment"								"West"
		"FGColor"									"White"
		"alpha"										"255"

		"Pin_To_Sibling"							"DisguiseStatusBG"
		"Pin_Corner_To_Sibling"						"PIN_TOPLEFT"
		"Pin_To_Sibling_Corner"						"PIN_BOTTOMLEFT"
	}
	"SpectatorGUIHealth"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"SpectatorGUIHealth"
		"XPos"										"0"
		"YPos"										"-6"
		"Wide"										"45"
		"Tall"										"44"
		"Visible"									"1"
		"Enabled"									"1"
		"HealthBonusPosAdj"							"10"
		"HealthDeathWarning"						"0.49"
		"TFFont"									"HudFontSmall"
		"HealthDeathWarningColor"					"HUDDeathWarning"
		"TextColor"									"HudOffWhite"

		"Pin_To_Sibling"							"DisguiseStatusBG"
		"Pin_Corner_To_Sibling"						"PIN_CENTER_LEFT"
		"Pin_To_Sibling_Corner"						"PIN_CENTER_LEFT"

        "HealthValue_Target"							// Proportional positioning doesn't work :(
        {
            "ControlName"								"CExLabel"
            "FieldName"									"HealthValue_Target"
            "XPos"										"-5"
            "YPos"										"0"
            "ZPos"										"20"
            "Wide"										"55"	// Made this larger so it can fit MvM bosses with 4 digit health,
            "Tall"										"40"
            "Visible"									"1"
            "Enabled"									"1"
            "ProportionalToParent"						"1"
            "TextAlignment"								"center"
            "LabelText"									"%Health%"
            "Font"										"Ingame_Medium"
            "FGColor"									"Health_Numbers"
        }
        "HealthValue_Target_Shadow"
        {
            "ControlName"								"CExLabel"
            "FieldName"									"HealthValue_Target_Shadow"
            "XPos"										"-1"
            "YPos"										"-1"
            "ZPos"										"19"
            "Wide"										"55"
            "Tall"										"40"
            "Visible"									"1"
            "Enabled"									"1"
            "ProportionalToParent"						"1"
            "TextAlignment"								"center"
            "LabelText"									"%Health%"
            "Font"										"Ingame_Medium"
            "FGColor"									"Main_Shadow_Transparent"

            "Pin_To_Sibling"							"HealthValue_Target"
        }
	}
}