"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Folder.res"
{
	"MainMenuOverride"
	{
		"Folder_Name_Warning"
		{
			"ControlName"								"EditablePanel"
			"FieldName"									"Folder_Name_Warning"
			"XPos"										"cs-0.5"
			"YPos"										"40"
			"ZPos"										"999"
			"Wide"										"600"
			"Tall"										"400"
			"Visible"									"1"
			"Enabled"									"1"
			"ProportionalToParent"						"1"
			"paintBackground"							"1"
			"paintBackgroundtype"						"0"
			"BGcolor_Override"							"Background_Darkest"

			"Warning"
			{
				"ControlName"							"CExLabel"
				"FieldName"								"Warning"
				"XPos"									"cs-0.5"
				"YPos"									"10"
				"ZPos"									"0"
				"Wide"									"f10"
				"Tall"									"50"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"LabelText"								"WARNING!"
				"Font"									"HudFontGiantBold"
				"TextAlignment"							"center"
				"FGColor"								"Red"
			}
			"Explanation_1"
			{
				"ControlName"							"CExLabel"
				"FieldName"								"Explanation_1"
				"XPos"									"cs-0.5"
				"YPos"									"85"
				"ZPos"									"0"
				"Wide"									"f10"
				"Tall"									"20"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"AllCaps"								"1"
				"LabelText"								"The HUD cannot function without the HUD folder being named jumphud"
				"Font"									"HudFontSmallishBold"
				"TextAlignment"							"center"
				"FGColor"								"Gray"
			}
            "Explanation_1b"
			{
				"ControlName"							"CExLabel"
				"FieldName"								"Explanation_1b"
				"XPos"									"cs-0.5"
				"YPos"									"135"
				"ZPos"									"0"
				"Wide"									"f10"
				"Tall"									"20"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"AllCaps"								"1"
				"LabelText"								"Please rename the HUD folder to:"
				"Font"									"HudFontMediumBold"
				"TextAlignment"							"center"
				"FGColor"								"White"
			}
			"jumphud"
			{
				"ControlName"							"CExLabel"
				"FieldName"								"jumphud"
				"XPos"									"cs-0.5"
				"YPos"									"cs-0.5+5"
				"ZPos"									"0"
				"Wide"									"f10"
				"Tall"									"50"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"LabelText"								"jumphud"
				"Font"									"HudFontGiantBold"
				"TextAlignment"							"center"
				"FGColor"								"White"
			}
            "CloseGameButton"
            {
                "ControlName"								"CExButton"
                "FieldName"									"CloseGameButton"
                "XPos"										"0"
                "YPos"										"20"
                "ZPos"										"20"
                "Wide"										"96"
                "Tall"										"22"
                "Visible"									"1"
                "Enabled"									"1"
                "ProportionalToParent"						"1"
                "AllCaps"									"1"
                "LabelText"									"Close TF2"
                "Font"										"HudFontSmallishBold"
                "TextAlignment"								"center"
                "Command"									"engine replay_confirmquit"
                "ActionSignalLevel"							"2"
                "Sound_Depressed"							"UI/buttonclick.wav"

                "DefaultBGColor_Override"					"Button_Red"
                "ArmedBGColor_Override"						"Button_Red_Hover"
                "DepressedBGColor_Override"					"Button_Red_Hover"

                "Pin_To_Sibling"							"jumphud"
                "Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
                "Pin_To_Sibling_Corner"						"PIN_CENTER_BOTTOM"
            }
			"Explanation_2"
			{
				"ControlName"							"CExLabel"
				"FieldName"								"Explanation_2"
				"XPos"									"cs-0.5"
				"YPos"									"rs1-50"
				"ZPos"									"0"
				"Wide"									"f10"
				"Tall"									"40"
				"Visible"								"1"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"AllCaps"								"1"
				"Wrap"									"1"
				"CenterWrap"							"1"
				"LabelText"								"This will ensure the HUD functions on all platforms! Once the folder is renamed simply restart TF2 to apply the changes and start using JumpHUD!"
				"Font"									"HudFontSmallishBold"
				"TextAlignment"							"center"
				"FGColor"								"Gray"
			}
		}
	}
}