"Resource/UI/HudDemomanCharge.res"
{
    "Markers"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Markers"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "3"
        "Wide"                          "140"
        "Tall"                          "4"
        "Visible"                       "1"
        "Enabled"                       "1"
        "pin_to_sibling"                "ChargeMeter"
        "pin_corner_to_sibling"         "PIN_CENTER_TOP"
        "pin_to_sibling_corner"         "PIN_CENTER_TOP"
        "Panel0"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "Panel0"
            "XPos"                          "0"
            "YPos"                          "0"
            "ZPos"                          "3"
            "Wide"                          "1"
            "Tall"                          "f0"
            "ProportionalToParent"          "1"
            "Visible"                       "1"
            "Enabled"                       "1"
            "PaintBackground"               "1"
            "PaintBackgroundType"           "0"
            "BGColor_Override"              "Gray"
        }
        "Panel1"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "Panel1"
            "XPos"                          "18"
            "YPos"                          "0"
            "ZPos"                          "3"
            "Wide"                          "1"
            "Tall"                          "f0"
            "ProportionalToParent"          "1"
            "Visible"                       "1"
            "Enabled"                       "1"
            "PaintBackground"               "1"
            "PaintBackgroundType"           "0"
            "BGColor_Override"              "TransparentLightBlack"
        }
        "Panel2"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "Panel2"
            "XPos"                          "35"
            "YPos"                          "0"
            "ZPos"                          "3"
            "Wide"                          "1"
            "Tall"                          "f0"
            "ProportionalToParent"          "1"
            "Visible"                       "1"
            "Enabled"                       "1"
            "PaintBackground"               "1"
            "PaintBackgroundType"           "0"
            "BGColor_Override"              "Gray"
        }
        "Panel3"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "Panel3"
            "XPos"                          "52"
            "YPos"                          "0"
            "ZPos"                          "3"
            "Wide"                          "1"
            "Tall"                          "f0"
            "ProportionalToParent"          "1"
            "Visible"                       "1"
            "Enabled"                       "1"
            "PaintBackground"               "1"
            "PaintBackgroundType"           "0"
            "BGColor_Override"              "TransparentLightBlack"
        }
        "Panel4"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "Panel4"
            "XPos"                          "70"
            "YPos"                          "0"
            "ZPos"                          "3"
            "Wide"                          "1"
            "Tall"                          "f0"
            "ProportionalToParent"          "1"
            "Visible"                       "1"
            "Enabled"                       "1"
            "PaintBackground"               "1"
            "PaintBackgroundType"           "0"
            "BGColor_Override"              "Gray"
        }
        "Panel5"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "Panel5"
            "XPos"                          "87"
            "YPos"                          "0"
            "ZPos"                          "3"
            "Wide"                          "1"
            "Tall"                          "f0"
            "ProportionalToParent"          "1"
            "Visible"                       "1"
            "Enabled"                       "1"
            "PaintBackground"               "1"
            "PaintBackgroundType"           "0"
            "BGColor_Override"              "TransparentLightBlack"
        }
        "Panel6"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "Panel6"
            "XPos"                          "105"
            "YPos"                          "0"
            "ZPos"                          "3"
            "Wide"                          "1"
            "Tall"                          "f0"
            "ProportionalToParent"          "1"
            "Visible"                       "1"
            "Enabled"                       "1"
            "PaintBackground"               "1"
            "PaintBackgroundType"           "0"
            "BGColor_Override"              "Gray"
        }
        "Panel7"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "Panel7"
            "XPos"                          "122"
            "YPos"                          "0"
            "ZPos"                          "3"
            "Wide"                          "1"
            "Tall"                          "f0"
            "ProportionalToParent"          "1"
            "Visible"                       "1"
            "Enabled"                       "1"
            "PaintBackground"               "1"
            "PaintBackgroundType"           "0"
            "BGColor_Override"              "TransparentLightBlack"
        }
        "Panel8"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "Panel8"
            "XPos"                          "rs1"
            "YPos"                          "0"
            "ZPos"                          "3"
            "Wide"                          "1"
            "Tall"                          "f0"
            "ProportionalToParent"          "1"
            "Visible"                       "1"
            "Enabled"                       "1"
            "PaintBackground"               "1"
            "PaintBackgroundType"           "0"
            "BGColor_Override"              "Gray"
        }
    }
}