"Resource/UI/HudMatchStatus_Base.res"
{
    "HudMatchStatus"
    {
        "FieldName"             "HudMatchStatus"
        "avatar_width"          "63"
        "spacer"                "5"
        "name_width"            "57"
        "horiz_inset"           "2"
    }
    "CountdownLabel"
    {
        "ControlName"                   "CExLabel"
        "FieldName"                     "CountdownLabel"
        "Font"                          "m0refont24Shadow"
        "XPos"                          "cs-0.5"
        "YPos"                          "cs-0.1"
        "Wide"                          "40"
        "Tall"                          "40"
        "ZPos"                          "5"
        "Visible"                       "0"
        "Enabled"                       "1"
        "LabelText"                     "%countdown%"
        "TextAlignment"                 "center"
        "ProportionalToParent"          "1"
        "FGColor"                       "White"
        "if_readymode"
        {
            "XPos"          "300"
            "YPos"          "130"
        }
    }
    "FrontParticlePanel"
    {
        "ControlName"                   "CTFParticlePanel"
        "FieldName"                     "FrontParticlePanel"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "3"
        "Wide"                          "f0"
        "Tall"                          "f0"
        "Visible"                       "1"
        "ProportionalToParent"          "1"
        "ParticleEffects"
        {
            "0"
            {
                "particle_xpos"             "c0"
                "particle_ypos"             "c0"
                "particle_scale"            "2"
                "particleName"              "versus_door_slam"
                "start_activated"           "0"
                "loop"                      "0"
            }
        }
        "PaintBackground"               "0"
    }
    "MatchDoors"
    {
        "ControlName"                   "CModelPanel"
        "FieldName"                     "MatchDoors"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "2"
        "Wide"                          "f0"
        "Tall"                          "f0"
        "Visible"                       "0"
        "Enabled"                       "1"
        "fov"                           "70"
        "ProportionalToParent"          "1"
        "Model"
        {
            "modelname"         "models/vgui/versus_doors.mdl"
            "skin"              "0"
            "angles_x"          "0"
            "angles_y"          "0"
            "angles_z"          "0"
            "origin_x"          "120"
            "origin_y"          "0"
            "origin_z"          "-77"
            "animation"
            {
                "name"              "ref"
                "sequence"          "ref"
            }
            "animation"
            {
                "name"              "open"
                "sequence"          "open"
            }
            "animation"
            {
                "name"              "close"
                "sequence"          "close"
            }
            "animation"
            {
                "name"              "idle_closed"
                "sequence"          "idle_closed"
            }
        }
    }
    "RoundCounter"
    {
        "FieldName"         "RoundCounter"
        "XPos"              "cs-0.5"
        "YPos"              "9999"
        "ZPos"              "1"
        "Wide"              "70"
        "Tall"              "30"
        "Visible"           "1"
        "Enabled"           "1"
    }
    "ObjectiveStatusTimePanel"	// HudObjectiveTimePanel
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "ObjectiveStatusTimePanel"
        "XPos"                          "cs-0.5"
        "YPos"                          "0"
        "ZPos"                          "5"
        "Wide"                          "100"
        "Tall"                          "50"
        "Visible"                       "1"
        "Enabled"                       "1"
        "delta_item_x"                  "9"
        "delta_item_start_y"            "29"
        "delta_item_end_y"              "29"
        "PositiveColor"                 "0 255 0 255"
        "NegativeColor"                 "255 0 0 255"
        "delta_lifetime"                "1"
        "delta_item_font"               "m0refont11"
        "ProportionalToParent"          "1"
        "TimePanelValue"
        {
            "ControlName"                   "CExLabel"
            "FieldName"                     "TimePanelValue"
            "XPos"                          "cs-0.5"
            "YPos"                          "0"
            "ZPos"                          "3"
            "Wide"                          "40"
            "Tall"                          "15"
            "Visible"                       "1"
            "Enabled"                       "1"
            "ProportionalToParent"          "1"
            "TextAlignment"                 "center"
            "LabelText"                     "0:00"
            "Font"                          "Time_Medium"
            "FGColor"                       "White"
            // "if_match"
            // {
            // "YPos"								"0"
            // "Tall"								"15"
            // "Font"								"Time_Medium"
            // }
        }
    }
    "TeamStatus"
    {
        "ControlName"               "CTFTeamStatus"
        "fieldName"                 "TeamStatus"
        "xpos"                      "0"
        "ypos"                      "0"
        "zpos"                      "2"
        "wide"                      "f0"
        "tall"                      "25"
        "visible"                   "1"
        "enabled"                   "1"
        "max_size"                  "50"
        "6v6_gap"                   "1"
        "12v12_gap"                 "1"
        "team1_grow_dir"            "west"
        "team1_base_x"              "c-50"
        "team1_max_expand"          "200"
        "team2_grow_dir"            "east"
        "team2_base_x"              "c51"
        "team2_max_expand"          "200"
        "playerpanels_kv"
        {
            "visible"                                       "0"
            "wide"                                          "f0"
            "tall"                                          "f0"
            "zpos"                                          "1"
            "proportionaltoparent"                          "1"
            "color_portrait_bg_red"                         "Red"
            "color_portrait_bg_blue"                        "Blue"
            "color_portrait_bg_red_dead"                    "Background_Main"
            "color_portrait_bg_blue_dead"                   "Background_Main"
            "color_bar_health_high"                         "Green"
            "color_bar_health_med"                          "255 130 50 255"
            "percentage_health_med"                         "0.6"
            "color_bar_health_low"                          "Red"
            "percentage_health_low"                         "0.3"
            "color_portrait_blend_dead_red"                 "White"
            "color_portrait_blend_dead_blue"                "White"
            "color_portrait_bg_red_local_player"            "Background_Main"
            "color_portrait_bg_blue_local_player"           "Background_Main"
            "ClassImageBg"
            {
                "ControlName"                   "Panel"
                "fieldName"                     "ClassImageBg"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "2"
                "wide"                          "f0"
                "tall"                          "19"
                "visible"                       "1"
                "enabled"                       "1"
                "PaintBackgroundType"           "0"
                "proportionaltoparent"          "1"
            }
            "PlayerName"
            {
                "ControlName"                   "CExLabel"
                "fieldName"                     "PlayerName"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "5"
                "wide"                          "f0"
                "tall"                          "7"
                "visible"                       "1"
                "textinsetx"                    "1"
                "labelText"                     "%playername%"
                "font"                          "VerdanaSmallest"
                "textAlignment"                 "center"
                "bgcolor_override"              "TransparentBlack"
                "proportionaltoparent"          "1"
                "alpha"                         "255"
                "pin_to_sibling"                "classimagebg"
                "pin_corner_to_sibling"         "PIN_CENTER_TOP"
                "pin_to_sibling_corner"         "PIN_CENTER_BOTTOM"
            }
            "ClassImage"
            {
                "ControlName"                   "CTFClassImage"
                "fieldName"                     "ClassImage"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "5"
                "wide"                          "22"
                "tall"                          "20"
                "visible"                       "1"
                "enabled"                       "1"
                "image"                         "../hud/class_scoutred"
                "scaleImage"                    "1"
                "proportionaltoparent"          "1"
                "pin_to_sibling"                "classimagebg"
                "pin_corner_to_sibling"         "PIN_CENTER_BOTTOM"
                "pin_to_sibling_corner"         "PIN_CENTER_BOTTOM"
            }
            "HealthBar"
            {
                "ControlName"                   "ContinuousProgressBar"
                "fieldName"                     "HealthBar"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "3"
                "wide"                          "f0"
                "tall"                          "19"
                "visible"                       "1"
                "enabled"                       "1"
                "bgcolor_override"              "80 80 80 255"
                "proportionaltoparent"          "1"
                "pin_to_sibling"                "playername"
                "pin_corner_to_sibling"         "PIN_CENTER_BOTTOM"
                "pin_to_sibling_corner"         "PIN_CENTER_TOP"
            }
            "OverHealBar"
            {
                "ControlName"                   "ContinuousProgressBar"
                "fieldName"                     "OverHealBar"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "4"
                "wide"                          "f0"
                "tall"                          "19"
                "visible"                       "1"
                "enabled"                       "1"
                "bgcolor_override"              "Blank"
                "fgcolor_override"              "255 255 255 200"
                "proportionaltoparent"          "1"
                "pin_to_sibling"                "healthbar"
            }
            "RespawnTime"
            {
                "ControlName"                   "CExLabel"
                "fieldName"                     "RespawnTime"
                "font"                          "m0refont12Shadow"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "10"
                "wide"                          "f0"
                "tall"                          "f0"
                "visible"                       "1"
                "labelText"                     "%respawntime%"
                "textAlignment"                 "center"
                "proportionaltoparent"          "1"
                "fgcolor"                       "White"
                "pin_to_sibling"                "ClassImageBg"
                "pin_corner_to_sibling"         "PIN_CENTER_TOP"
                "pin_to_sibling_corner"         "PIN_CENTER_TOP"
            }
            "HealthIcon"
            {
                "ControlName"           "EditablePanel"
                "fieldName"             "HealthIcon"
                "xpos"                  "9999"
                "ypos"                  "9999"
                "wide"                  "0"
                "tall"                  "0"
                "visible"               "0"
                "enabled"               "0"
            }
            "ReadyBG"
            {
                "ControlName"           "ScalableImagePanel"
                "fieldName"             "ReadyBG"
                "xpos"                  "9999"
                "ypos"                  "9999"
                "wide"                  "0"
                "tall"                  "0"
                "visible"               "0"
                "enabled"               "0"
            }
            "ReadyImage"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "ReadyImage"
                "xpos"                  "9999"
                "ypos"                  "9999"
                "wide"                  "0"
                "tall"                  "0"
                "visible"               "0"
                "enabled"               "0"
            }
            "chargeamount"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "chargeamount"
                "xpos"                  "9999"
                "ypos"                  "9999"
                "wide"                  "0"
                "tall"                  "0"
                "visible"               "0"
                "enabled"               "0"
            }
            "specindex"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "specindex"
                "xpos"                  "9999"
                "ypos"                  "9999"
                "wide"                  "0"
                "tall"                  "0"
                "visible"               "0"
                "enabled"               "0"
            }
            "DeathPanel"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "DeathPanel"
                "xpos"                  "9999"
                "ypos"                  "9999"
                "wide"                  "0"
                "tall"                  "0"
                "visible"               "0"
                "enabled"               "0"
            }
            "SkullPanel"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "SkullPanel"
                "xpos"                  "9999"
                "ypos"                  "9999"
                "wide"                  "0"
                "tall"                  "0"
                "visible"               "0"
                "enabled"               "0"
            }
        }
    }
    "BlueTeamPanel"
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "BlueTeamPanel"
        "XPos"                  "-155"
        "YPos"                  "125"
        "ZPos"                  "50"
        "Wide"                  "150"
        "Tall"                  "260"
        "Visible"               "0"
        "Enabled"               "1"
        "alpha"                 "255"
        "if_large"
        {
            "YPos"          "65"
            "Tall"          "385"
        }
        "BlueTeamBG"
        {
            "ControlName"           "EditablePanel"
            "FieldName"             "BlueTeamBG"
            "XPos"                  "0"
            "YPos"                  "10"
            "ZPos"                  "2"
            "Wide"                  "147"
            "Tall"                  "36"
            "Visible"               "1"
            "Enabled"               "1"
            "Border"                "TFFatLineBorderBlueBGOpaque"
        }
        "BlueTeamImage"
        {
            "ControlName"           "ImagePanel"
            "FieldName"             "BlueTeamImage"
            "XPos"                  "9"
            "YPos"                  "0"
            "ZPos"                  "5"
            "Wide"                  "56"
            "Tall"                  "56"
            "Visible"               "1"
            "Enabled"               "1"
            "Image"                 "../hud/team_blue"
            "ScaleImage"            "1"
        }
        "BlueTeamLabel"
        {
            "ControlName"           "CExLabel"
            "FieldName"             "BlueTeamLabel"
            "Font"                  "CompMatchStartTeamNames"
            "LabelText"             "%blueteamname%"
            "TextAlignment"         "center"
            "XPos"                  "48"
            "YPos"                  "13"
            "ZPos"                  "20"
            "Wide"                  "95"
            "Tall"                  "30"
            "Visible"               "1"
            "Enabled"               "1"
            "CenterWrap"            "1"
        }
        "BlueLeaderAvatar"
        {
            "ControlName"           "CAvatarImagePanel"
            "FieldName"             "BlueLeaderAvatar"
            "XPos"                  "11"
            "YPos"                  "10"
            "ZPos"                  "5"
            "Wide"                  "35"
            "Tall"                  "35"
            "Visible"               "1"
            "Enabled"               "1"
            "Image"                 ""
            "ScaleImage"            "1"
            "color_outline"         "52 48 45 255"
        }
        "BlueLeaderAvatarBG"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "BlueLeaderAvatarBG"
            "XPos"                          "9"
            "YPos"                          "8"
            "ZPos"                          "4"
            "Wide"                          "39"
            "Tall"                          "39"
            "Visible"                       "1"
            "PaintBackgroundType"           "2"
            "BGColor_Override"              "117 107 94 255"
        }
        "BluePlayerList"
        {
            "ControlName"           "SectionedListPanel"
            "FieldName"             "BluePlayerList"
            "XPos"                  "6"
            "YPos"                  "38"
            "ZPos"                  "1"
            "Wide"                  "136"
            "Tall"                  "205"
            "Visible"               "1"
            "Enabled"               "1"
            "autoresize"            "3"
            "linespacing"           "26"
            "linegap"               "4"
            // "show_columns"						"1"
            "if_large"
            {
                "Tall"          "315"
            }
        }
        "BluePlayerListBG"
        {
            "ControlName"           "EditablePanel"
            "FieldName"             "BluePlayerListBG"
            "XPos"                  "4"
            "YPos"                  "30"
            "ZPos"                  "0"
            "Wide"                  "139"
            "Tall"                  "215"
            "Visible"               "1"
            "Enabled"               "1"
            "Border"                "TFFatLineBorderClearBG"
            "if_large"
            {
                "Tall"          "325"
            }
        }
    }
    "RedTeamPanel"
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "RedTeamPanel"
        "XPos"                  "r-5"
        "YPos"                  "125"
        "ZPos"                  "50"
        "Wide"                  "150"
        "Tall"                  "260"
        "Visible"               "0"
        "Enabled"               "1"
        "alpha"                 "255"
        "if_large"
        {
            "YPos"          "65"
            "Tall"          "385"
        }
        "RedTeamBG"
        {
            "ControlName"           "EditablePanel"
            "FieldName"             "RedTeamBG"
            "XPos"                  "0"
            "YPos"                  "10"
            "ZPos"                  "2"
            "Wide"                  "147"
            "Tall"                  "36"
            "Visible"               "1"
            "Enabled"               "1"
            "Border"                "TFFatLineBorderRedBGOpaque"
        }
        "RedTeamImage"
        {
            "ControlName"           "ImagePanel"
            "FieldName"             "RedTeamImage"
            "XPos"                  "84"
            "YPos"                  "-9"
            "ZPos"                  "5"
            "Wide"                  "70"
            "Tall"                  "70"
            "Visible"               "1"
            "Enabled"               "1"
            "Image"                 "../hud/team_Red"
            "ScaleImage"            "1"
        }
        "RedTeamLabel"
        {
            "ControlName"           "CExLabel"
            "FieldName"             "RedTeamLabel"
            "Font"                  "CompMatchStartTeamNames"
            "LabelText"             "%redteamname%"
            "TextAlignment"         "center"
            "XPos"                  "5"
            "YPos"                  "13"
            "ZPos"                  "20"
            "Wide"                  "95"
            "Tall"                  "30"
            "Visible"               "1"
            "Enabled"               "1"
            "CenterWrap"            "1"
        }
        "RedLeaderAvatar"
        {
            "ControlName"           "CAvatarImagePanel"
            "FieldName"             "RedLeaderAvatar"
            "XPos"                  "102"
            "YPos"                  "10"
            "ZPos"                  "5"
            "Wide"                  "35"
            "Tall"                  "35"
            "Visible"               "1"
            "Enabled"               "1"
            "Image"                 ""
            "ScaleImage"            "1"
            "color_outline"         "52 48 45 255"
        }
        "RedLeaderAvatarBG"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "RedLeaderAvatarBG"
            "XPos"                          "100"
            "YPos"                          "8"
            "ZPos"                          "4"
            "Wide"                          "39"
            "Tall"                          "39"
            "Visible"                       "1"
            "PaintBackgroundType"           "2"
            "BGColor_Override"              "117 107 94 255"
        }
        "RedPlayerList"
        {
            "ControlName"           "SectionedListPanel"
            "FieldName"             "RedPlayerList"
            "XPos"                  "6"
            "YPos"                  "38"
            "ZPos"                  "1"
            "Wide"                  "136"
            "Tall"                  "205"
            "Visible"               "1"
            "Enabled"               "1"
            "autoresize"            "3"
            "linespacing"           "26"
            "linegap"               "4"
            // "show_columns"						"1"
            "if_large"
            {
                "Tall"          "315"
            }
        }
        "RedPlayerListBG"
        {
            "ControlName"           "EditablePanel"
            "FieldName"             "RedPlayerListBG"
            "XPos"                  "4"
            "YPos"                  "30"
            "ZPos"                  "0"
            "Wide"                  "139"
            "Tall"                  "215"
            "Visible"               "1"
            "Enabled"               "1"
            "Border"                "TFFatLineBorderClearBG"
            "if_large"
            {
                "Tall"          "325"
            }
        }
    }
    // ==================================================================================================================================================
    // REMOVED ELEMENTS
    // ==================================================================================================================================================
    "BGFrame"
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "BGFrame"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
    "CountdownLabelShadow"
    {
        "ControlName"           "CExLabel"
        "FieldName"             "CountdownLabelShadow"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
    "RoundSignModel"
    {
        "ControlName"           "CModelPanel"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
    "RankUpLabel"
    {
        "ControlName"           "CExLabel"
        "FieldName"             "RankUpLabel"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
    "RankUpShadowLabel"
    {
        "ControlName"           "CExLabel"
        "FieldName"             "RankUpShadowLabel"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
}