"Resource/UI/HudUpgradePanel.res"
{
	"HudUpgradePanel"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"HudUpgradePanel"
		"XPos"										"0"
		"YPos"										"0"
		"ZPos"										"1000"
		"Wide"										"f0"
		"Tall"										"480"
		"Visible"									"0"
		"Enabled"									"1"
		"settitlebarvisible"						"0"

		"itempanel_xpos"							"15"
		"itempanel_ypos"							"24"
		"itempanel_xdelta"							"5"
		"itempanel_ydelta"							"5"

		"upgradebuypanel_xpos"						"160"
		"upgradebuypanel_ypos"						"65"
		"upgradebuypanel_delta"						"6"

		"modelpanels_kv"
		{
			"ZPos"									"-2"
			"Wide"									"70"
			"Tall"									"50"
			"BGcolor_Override"						"Blank"
			"noitem_textcolor"						"White"
			"PaintBackgroundType"					"0"
			"PaintBorder"							"0"

			"model_ypos"							"5"
			"model_tall"							"32"
			"model_wide"							"48"
			"model_center_x"						"1"
			"text_ypos"								"60"
			"text_center"							"1"
			"name_only"								"1"
			"text_forcesize"						"3"

			"itemmodelpanel"
			{
				"use_item_rendertarget"				"0"
				"inventory_image_type"				"1"
				"allow_rot"							"0"
			}
		}
	}
	"BGGrayoutPanel"								//FULL SCREEN BG
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"BGGrayoutPanel"
		"XPos"										"0"
		"YPos"										"0"
		"Wide"										"f0"
		"Tall"										"f0"
		"ZPos"										"-1"
		"Visible"									"1"
		"Enabled"									"1"
		"ProportionalToParent"						"1"
		"PaintBackground"							"1"
		"PaintBackgroundType"						"0"
		"BGcolor_Override"							"TransparentLightBlack"
	}
	"SelectWeaponPanel"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"SelectWeaponPanel"
		"XPos"										"c-250"
		"YPos"										"85"
		"Wide"										"500"
		"Tall"										"350"
		"Visible"									"1"
		"Enabled"									"1"
		"PaintBackground"							"0"

		"OutterBG"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"OutterBG"
			"XPos"									"0"
			"YPos"									"23"
			"ZPos"									"-8"
			"Wide"									"478"
			"Tall"									"290"
			"Visible"								"1"
			"Enabled"								"1"
			"PaintBackground"						"1"
			"PaintBackgroundType"					"0"
			"BGcolor_Override"						"TransparentBlack"
		}
		"InnerPanelRim"
		{
			"ControlName"							"Panel"
			"FieldName"								"InnerPanelRim"
			"XPos"									"10"
			"YPos"									"64"
			"ZPos"									"10"
			"Wide"									"468"
			"Tall"									"1"
			"Visible"								"1"
			"Enabled"								"1"
			"PaintBackground"						"1"
			"PaintBackgroundType"					"0"
			"BGcolor_Override"						"black"
		}
		"InnerBGPanel"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"InnerBGPanel"
			"XPos"									"0"
			"YPos"									"64"
			"ZPos"									"0"
			"Wide"									"155"
			"Tall"									"201"
			"Visible"								"1"
			"PaintBackground"						"1"
			"PaintBackgroundType"					"0"
            "alpha" "255"
			"BGcolor_Override"						"Black"
		}
        "UpgradesBGPanel"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"UpgradesBGPanel"
			"XPos"									"20+135+3"
			"YPos"									"64"
			"ZPos"									"0"
			"Wide"									"320"
			"Tall"									"201"
			"Visible"								"1"
			"PaintBackground"						"1"
			"PaintBackgroundType"					"0"
            "alpha" "255"
			"BGcolor_Override"						"Black"
		}
		"PlayerUpgradeButton"
		{
			"ControlName"							"CExButton"
			"FieldName"								"PlayerUpgradeButton"
			"XPos"									"15"
			"YPos"									"24"
			"ZPos"									"-2"
			"Wide"									"70"
			"Tall"									"50"
			"Visible"								"1"
			"Enabled"								"1"
			"LabelText"								"PLAYER"
			"Font"									"HudFontSmall"
			"TextAlignment"							"center"
			"TextInsetX"							"50"
			"Command"								"PlayerUpgrade"
			"Sound_Depressed"						"UI/buttonclick.wav"
			"sound_released"						"UI/buttonclickrelease.wav"
			"alpha"									"0"
		}
		"ClassImage"
		{
			"ControlName"							"CTFClassImage"
			"FieldName"								"ClassImage"
			"XPos"									"30"
			"YPos"									"24"
			"ZPos"									"-2"
			"Wide"									"40"
			"Tall"									"40"
			"Visible"								"1"
			"Enabled"								"1"
			"Image"									"../hud/class_scoutred"
			"ScaleImage"							"1"
		}
		"SentryIcon"
		{
			"ControlName"							"ImagePanel"
			"FieldName"								"SentryIcon"
			"XPos"									"332"
			"YPos"									"24"
			"Wide"									"34"
			"Tall"									"34"
			"ZPos"									"-2"
			"Visible"								"1"
			"Enabled"								"1"

			"ScaleImage"							"1"

			"Image"									"../hud/eng_build_sentry"
		}
		"ActiveTabPanel"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"ActiveTabPanel"
			"XPos"									"88"
			"YPos"									"8"
			"ZPos"									"-3"
			"Wide"									"74"
			"Tall"									"43"
			"Visible"								"1"
			"Enabled"								"1"
			"BGcolor_Override"						"Highlight_Color_Dark"
			"PaintBackgroundType"					"0"
		}
		"MouseOverTabPanel"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"MouseOverTabPanel"
			"XPos"									"14"
			"YPos"									"9" // hardcoded? :(
			"ZPos"									"-6"
			"Wide"									"72"
			"Tall"									"42"
			"Visible"								"0"
			"Enabled"								"1"
			"BGcolor_Override"						"Button_Hover"
			"PaintBackgroundType"					"0"
		}
		"MouseOverUpgradePanel"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"MouseOverUpgradePanel"
			"XPos"									"0"
			"YPos"									"0"
			"ZPos"									"10"
			"Wide"									"158"
			"Tall"									"48"
			"Visible"								"0"
			"Enabled"								"1"
			"BGcolor_Override"						"Button_Hover"
			"PaintBackgroundType"					"0"
		}
		"InactiveTabPanel1"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"InactiveTabPanel1"
			"XPos"									"15"
			"YPos"									"10"
			"ZPos"									"-5"
			"Wide"									"70"
			"Tall"									"54"
			"Visible"								"1"
			"Enabled"								"1"
			"BGcolor_Override"						"Blank"
			"PaintBackgroundType"					"0"
		}
		"InactiveTabPanel2"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"InactiveTabPanel2"
			"XPos"									"15"
			"YPos"									"10"
			"ZPos"									"-5"
			"Wide"									"70"
			"Tall"									"54"
			"Visible"								"1"
			"Enabled"								"1"
			"BGcolor_Override"						"Blank"
			"PaintBackgroundType"					"0"
		}
		"InactiveTabPanel3"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"InactiveTabPanel3"
			"XPos"									"15"
			"YPos"									"10"
			"ZPos"									"-5"
			"Wide"									"70"
			"Tall"									"54"
			"Visible"								"1"
			"Enabled"								"1"
			"BGcolor_Override"						"Blank"
			"PaintBackgroundType"					"0"
		}
		"InactiveTabPanel4"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"InactiveTabPanel4"
			"XPos"									"15"
			"YPos"									"10"
			"ZPos"									"-5"
			"Wide"									"70"
			"Tall"									"54"
			"Visible"								"1"
			"Enabled"								"1"
			"BGcolor_Override"						"Blank"
			"PaintBackgroundType"					"0"
		}
		"InactiveTabPanel5"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"InactiveTabPanel5"
			"XPos"									"15"
			"YPos"									"10"
			"ZPos"									"-5"
			"Wide"									"70"
			"Tall"									"54"
			"Visible"								"1"
			"Enabled"								"1"
			"BGcolor_Override"						"Blank"
			"PaintBackgroundType"					"0"
		}
		"InactiveTabPanel6"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"InactiveTabPanel6"
			"XPos"									"15"
			"YPos"									"10"
			"ZPos"									"-5"
			"Wide"									"70"
			"Tall"									"54"
			"Visible"								"1"
			"Enabled"								"1"
			"BGcolor_Override"						"Blank"
			"PaintBackgroundType"					"0"
		}
		"InactiveSeparatorPanel"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"InactiveSeparatorPanel"
			"XPos"									"10"
			"YPos"									"49"
			"ZPos"									"-4"
			"Wide"									"480"
			"Tall"									"5"
			"Visible"								"0"
			"Enabled"								"1"
			"BGcolor_Override"						"White"
		}
		"GreyedOutLabel"							//DEAD
		{
			"ControlName"							"CExLabel"
			"FieldName"								"GreyedOutLabel"
			"Font"									"HudFontSmall"
			"LabelText"								"%powerup_hint%"
			"TextAlignment"							"north"
			"Wrap"									"1"
			"CenterWrap"							"1"
			"XPos"									"190"
			"YPos"									"95"
			"ZPos"									"2"
			"Wide"									"240"
			"Tall"									"140"
			"Visible"								"1"
			"Enabled"								"1"
			"mouseinputenabled"						"0"
			"FGColor"								"White"
		}
		"QuickEquipButton"							//DEAD
		{
			"ControlName"							"CExButton"
			"FieldName"								"QuickEquipButton"
			"XPos"									"250"
			"YPos"									"195"
			"ZPos"									"1"
			"Wide"									"120"
			"Tall"									"17"
			"Visible"								"0"
			"Enabled"								"1"
			"LabelText"								"#TF_PVE_Quick_Equip_Bottle"
			"Font"									"HudFontSmallest"
			"TextAlignment"							"center"
			"TextInsetX"							"50"
			"Command"								"quick_equip_bottle"
			"Sound_Depressed"						"UI/buttonclick.wav"
			"sound_released"						"UI/buttonclickrelease.wav"
		}
		"LoadoutButton"								//DEAD
		{
			"ControlName"							"CExButton"
			"FieldName"								"LoadoutButton"
			"XPos"									"250"
			"YPos"									"215"
			"ZPos"									"1"
			"Wide"									"120"
			"Tall"									"17"
			"Visible"								"0"
			"Enabled"								"1"
			"LabelText"								"#OpenGeneralLoadout"
			"Font"									"HudFontSmallest"
			"TextAlignment"							"center"
			"TextInsetX"							"50"
			"Command"								"open_charinfo_direct"
			"Sound_Depressed"						"UI/buttonclick.wav"
			"sound_released"						"UI/buttonclickrelease.wav"
		}
		"UpgradeItemsDescriptionBG"
		{
			"ControlName"							"Panel"
			"FieldName"								"UpgradeItemsDescriptionBG"
			"XPos"									"5"
			"YPos"									"65"
			"ZPos"									"0"
			"Wide"									"150"
			"Tall"									"65"
			"Visible"								"1"
			"Enabled"								"1"

			"BGcolor_Override"						"blank"
		}
		"UpgradeItemsDescriptionLabel"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"UpgradeItemsDescriptionLabel"
			"Font"									"LabelsFontLarge"
			"LabelText"								"%upgrade_description%"
			"TextAlignment"							"center"
			"Wrap"									"1"
			"CenterWrap"							"1"
			"XPos"									"10"
			"YPos"									"65"
			"ZPos"									"2"
			"Wide"									"140"
			"Tall"									"65"
			"Visible"								"1"
			"Enabled"								"1"
			"AllCaps"								"1"
			"FGColor"								"White"
		}
		"UpgradeItemsBG"
		{
			"ControlName"							"Panel"
			"FieldName"								"UpgradeItemsBG"
			"XPos"									"25"
			"YPos"									"135"
			"ZPos"									"0"
			"Wide"									"0"
			"Tall"									"0"
			"Visible"								"0"
			"Enabled"								"0"

			"BGcolor_Override"						"blank"
		}
		"UpgradeItemsHeaderBG"
		{
			"ControlName"							"Panel"
			"FieldName"								"UpgradeItemsHeaderBG"
			"XPos"									"0"
			"YPos"									"135"
			"ZPos"									"1"
			"Wide"									"155"
			"Tall"									"1"
			"Visible"								"1"
			"Enabled"								"1"
            "alpha" "10"
			"BGcolor_Override"						"White"
		}
		"UpgradeItemsLabel"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"UpgradeItemsLabel"
			"Font"									"TargetID_Small"
			"LabelText"								"%upgrade_label%"
			"TextAlignment"							"Center"
			"XPos"									"2"
			"YPos"									"135"
			"ZPos"									"2"
			"Wide"									"151"
			"Tall"									"20"
			"Visible"								"1"
			"Enabled"								"1"
			"AllCaps"								"1"
			"FGColor"								"White"
		}
		"UpgradeItemStatsLabel"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"UpgradeItemStatsLabel"
			"Font"									"LabelsFontLarge"
			"LabelText"								""
			"TextAlignment"							"north-west"
			"XPos"									"4"
			"YPos"									"160"
			"ZPos"									"2"
			"Wide"									"147"
			"Tall"									"105"
			"Visible"								"1"
			"Enabled"								"1"
			"Wrap"									"1"
			"AllCaps"								"1"
			"FGColor"								"White"
		}
		"CreditsBG"
		{
			"ControlName"							"EditablePanel"
			"FieldName"								"CreditsBG"
			"XPos"									"151"
			"YPos"									"285"
			"Wide"									"69"
			"Tall"									"20"
			"Visible"								"1"
			"Enabled"								"1"
			"PaintBackground"						"1"
			"PaintBackgroundType"					"0"
            "alpha" "255"
			"BGcolor_Override"						"background_main"
		}
		"CreditsIcon"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"CreditsIcon"
			"Font"									"HudFontMediumSmall"
			"LabelText"								"$"
			"TextAlignment"							"east"
			"XPos"									"0"
			"YPos"									"0"
			"ZPos"									"1"
			"Wide"									"20"
			"Tall"									"20"
			"Visible"								"1"
			"Enabled"								"1"
			"AllCaps"								"1"
			"PaintBackground"						"0"
			"PaintBackgroundType"					"0"
			"BGcolor_Override"						"blank"
			"FGColor"								"White"
			"Pin_To_Sibling"						"CreditsBG"
		}
		"CreditsLabel"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"CreditsLabel"
			"Font"									"HudFontMediumSmall"
			"LabelText"								"%credits%"
			"TextAlignment"							"west"
			"XPos"									"-2"
			"YPos"									"0"
			"ZPos"									"1"
			"Wide"									"45"
			"Tall"									"20"
			"Visible"								"1"
			"Enabled"								"1"
			"AllCaps"								"1"
			"FGColor"								"CreditsGreen"

			"Pin_To_Sibling"						"CreditsBG"
			"Pin_Corner_To_Sibling"					"PIN_CENTER_RIGHT"
			"Pin_To_Sibling_Corner"					"PIN_CENTER_RIGHT"
		}
		"CancelButton"
		{
			"ControlName"							"CExButton"
			"FieldName"								"CancelButton"
			"XPos"									"224"
			"YPos"									"285"
			"ZPos"									"10"
			"Wide"									"120"
			"Tall"									"20"
			"Visible"								"1"
			"Enabled"								"1"
			"LabelText"								"#TF_PVE_UpgradeCancel"
			"Font"									"HudFontSmallestBold"
			"TextAlignment"							"center"
			"Command"								"cancel"
			"Sound_Depressed"						"UI/buttonclick.wav"
			"sound_released"						"UI/buttonclickrelease.wav"

			"AllCaps"								"1"

			"PaintBackground"						"1"

			"DefaultFGColor_Override"				"White"
			"ArmedFGColor_Override"					"White"
			"DepressedFGColor_Override"				"White"

			"DefaultBGColor_Override"				"Background_Main"
			"ArmedBGColor_Override"					"Highlight_Color_Dark"
			"DepressedBGColor_Override"				"Highlight_Color_Dark"
		}
		"CloseButton"
		{
			"ControlName"							"CExButton"
			"FieldName"								"CloseButton"
			"XPos"									"350"
			"YPos"									"285"
			"ZPos"									"10"
			"Wide"									"120"
			"Tall"									"20"
			"Visible"								"1"
			"Enabled"								"0"
			"LabelText"								"#TF_PVE_UpgradeDone"
			"Font"									"HudFontSmallestBold"
			"TextAlignment"							"center"
			"Command"								"close"
			"Sound_Depressed"						"UI/buttonclick.wav"
			"sound_released"						"UI/buttonclickrelease.wav"

			"AllCaps"								"1"

			"PaintBackground"						"1"

			"DefaultFGColor_Override"				"White"
			"ArmedFGColor_Override"					"White"
			"DepressedFGColor_Override"				"White"

			"DefaultBGColor_Override"				"Background_Main"
			"ArmedBGColor_Override"					"CreditsGreen"
			"DepressedBGColor_Override"				"CreditsGreen"
		}
		"RespecButton"
		{
			"ControlName"							"CExButton"
			"FieldName"								"RespecButton"
			"XPos"									"10"
			"YPos"									"285"
			"ZPos"									"10"
			"Wide"									"136"
			"Tall"									"20"
			"Visible"								"0"
			"Enabled"								"0"
			"LabelText"								"#TF_PVE_UpgradeRespec"
			"Font"									"HudFontSmallestBold"
			"TextAlignment"							"center"
			"Command"								"respec"
			"Sound_Depressed"						"UI/buttonclick.wav"
			"sound_released"						"UI/buttonclickrelease.wav"

			"AllCaps"								"1"

			"PaintBackground"						"1"

			"DefaultFGColor_Override"				"White"
			"ArmedFGColor_Override"					"White"
			"DepressedFGColor_Override"				"White"

			"DefaultBGColor_Override"				"Background_Main"
			"ArmedBGColor_Override"					"Highlight_Color_Dark"
			"DepressedBGColor_Override"				"Highlight_Color_Dark"
		}
		"CreditsTextLabel"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"CreditsTextLabel"
			"XPos"									"9999"
		}
		"OutterPanelBG"
		{
			"ControlName"							"ScalableImagePanel"
			"FieldName"								"OutterPanelBG"
			"XPos"									"9999"
		}
	}


	//===================================================================================
	// REMOVED ELEMENTS
	//===================================================================================
	"TipPanel"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"TipPanel"
		"XPos"										"9999"
		"YPos"										"9999"
		"Wide"										"0"
		"Tall"										"0"
		"Visible"									"0"
		"Enabled"									"0"
	}
}