"Resource/SteamWorkshopDialog.res"
{
    "SteamWorkshopDialog"
    {
        "ControlName"               "CSteamWorkshopDialog"
        "FieldName"                 "SteamWorkshopDialog"
        "XPos"                      "0"
        "YPos"                      "0"
        "Wide"                      "f0"
        "Tall"                      "f0"
        "Visible"                   "1"
        "Enabled"                   "1"
        "PaintBackground"           "0"
    }
    "Container"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Container"
        "XPos"                          "c-274"
        "YPos"                          "140"
        "Wide"                          "290"
        "Tall"                          "39"
        "Visible"                       "1"
        "Enabled"                       "1"
        "ProportionalToParent"          "1"
        "PaintBackground"               "1"
        "PaintBackgroundType"           "0"
        "BGcolor_Override"              "blank"
        "TransparentBackground"
        {
            "ControlName"                           "EditablePanel"
            "FieldName"                             "TransparentBackground"
            "XPos"                                  "0"
            "YPos"                                  "0"
            "ZPos"                                  "-2"
            "Wide"                                  "f0"
            "Tall"                                  "20"
            "ProportionalToParent"                  "1"
            "Visible"                               "1"
            "Enabled"                               "1"
            "PaintBackground"                       "1"
            "PaintBackgroundType"                   "0"
            "BGColor_Override"                      "TransparentBlack"
            "InFocus_BGColor_Override"              "TransparentBlack"
            "OutOfFocus_BGColor_Override"           "TransparentBlack"
        }
        "HintLabel"
        {
            "ControlName"                   "Label"
            "FieldName"                     "HintLabel"
            "XPos"                          "-20"
            "YPos"                          "0"
            "ZPos"                          "8"
            "Wide"                          "f0-40"
            "Tall"                          "20"
            "Visible"                       "1"
            "Enabled"                       "1"
            "Font"                          "HudFontSmall"
            "LabelText"                     "Click the Jump logo to switch to Casual mode"
            "TextInsetY"                    "-1"
            "TextAlignment"                 "center"
            "ProportionalToParent"          "1"
            "FGColor_Override"              "White"
        }
        "Arrow"
        {
            "ControlName"           "ImagePanel"
            "FieldName"             "Arrow"
            "XPos"                  "-7"
            "YPos"                  "13"
            "ZPos"                  "3"
            "Wide"                  "42"
            "Tall"                  "42"
            "Visible"               "1"
            "Enabled"               "1"
            "image"                 "logos/build_icons/hud_obj_status_tele_entrance"
            "drawcolor"             "white"
            "ScaleImage"            "1"
        }
        "CancelButton"
        {
            "ControlName"                       "CExButton"
            "FieldName"                         "CancelButton"
            "XPos"                              "rs1"
            "YPos"                              "0"
            "ZPos"                              "20"
            "Wide"                              "40"
            "Tall"                              "20"
            "Visible"                           "1"
            "Enabled"                           "1"
            "LabelText"                         "OK!"
            "Font"                              "HudFontSmall"
            "TextAlignment"                     "center"
            "Command"                           "cancel"
            "ProportionalToParent"              "1"
            "AllCaps"                           "1"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "1"
            "DefaultBGColor_Override"           "Highlight_Color_Dark"
            "ArmedBGColor_Override"             "Button_Hover"
            "DepressedBGColor_Override"         "Button_Hover"
        }
        // ===================================================================================
        // REMOVED ELEMENTS
        // ===================================================================================
        "LearnMore2Button"
        {
            "ControlName"           "CExButton"
            "FieldName"             "LearnMore2Button"
            "XPos"                  "9999"
            "YPos"                  "9999"
            "Wide"                  "0"
            "Tall"                  "0"
            "Visible"               "0"
            "Enabled"               "0"
        }
        "ViewLegalAgreementButton"
        {
            "ControlName"           "CExButton"
            "FieldName"             "ViewLegalAgreementButton"
            "XPos"                  "9999"
            "YPos"                  "9999"
            "Wide"                  "0"
            "Tall"                  "0"
            "Visible"               "0"
            "Enabled"               "0"
        }
        "Background"
        {
            "ControlName"           "EditablePanel"
            "FieldName"             "Background"
            "XPos"                  "9999"
            "YPos"                  "9999"
            "Wide"                  "0"
            "Tall"                  "0"
            "Visible"               "0"
            "Enabled"               "0"
        }
        "WorkshopBranding"
        {
            "ControlName"           "ImagePanel"
            "FieldName"             "WorkshopBranding"
            "XPos"                  "9999"
            "YPos"                  "9999"
            "Wide"                  "0"
            "Tall"                  "0"
            "Visible"               "0"
            "Enabled"               "0"
        }
        "BackgroundBottom"
        {
            "ControlName"           "EditablePanel"
            "FieldName"             "BackgroundBottom"
            "XPos"                  "9999"
            "YPos"                  "9999"
            "Wide"                  "0"
            "Tall"                  "0"
            "Visible"               "0"
            "Enabled"               "0"
        }
    }
}