"Resource/UI/TargetID.res"
{
	"TargetIDBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"TargetIDBG"
		"xpos"			"8"
		"ypos"			"-32"
		"zpos"			"-1"
		"wide"			"252"
		"tall"	 		"15"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/color_panel_clear"
		"scaleImage"		"1"
        "alpha"										"175"
		"teambg_1"		"../hud/color_panel_clear"
		"teambg_2"		"replay/thumbnails/panels/target_red"
		"teambg_3"		"replay/thumbnails/panels/target_blue"
	}
	"TargetIDBG_Spec_Blue"
	{
		"ControlName"								"ScalableImagePanel"
		"FieldName"									"TargetIDBG_Spec_Blue"
		"XPos"										"8"
		"YPos"										"-22"
		"ZPos"										"-1"
		"Wide"										"252"
		"Tall"										"0"
		"Visible"									"0"
		"Enabled"									"1"
		"ScaleImage"								"1"
		"alpha"										"175"

		"Image"										"replay/thumbnails/panels/target_blue"
		"src_corner_height"							"0"
		"src_corner_width"							"0"
		"draw_corner_width"							"0"
		"draw_corner_height"						"0"
	}
	"TargetIDBG_Spec_Red"
	{
		"ControlName"								"ScalableImagePanel"
		"FieldName"									"TargetIDBG_Spec_Red"
		"XPos"										"8"
		"YPos"										"-22"
		"ZPos"										"-1"
		"Wide"										"252"
		"Tall"										"30"
		"Visible"									"0"
		"Enabled"									"1"
		"ScaleImage"								"1"
		"alpha"										"175"

		"Image"										"replay/thumbnails/panels/target_red"
		"src_corner_height"							"0"
		"src_corner_width"							"0"
		"draw_corner_width"							"0"
		"draw_corner_height"						"0"
	}
	"TargetBGshade"
	{
		"ControlName"								"ImagePanel"
		"FieldName"									"TargetBGshade"
		"XPos"										"8"
		"YPos"										"cs-0.5-4"
		"ZPos"										"-1"
		"Wide"										"252"
		"Tall"										"14"
		"Visible"									"0"
		"Enabled"									"1"
		"ProportionalToParent"						"1"
		"fillcolor"									"TransparentLightBlack"
	}
	
	"TargetNameLabel"
	{	
		"ControlName"		"Label"
		"fieldName"		"TargetNameLabel"
		"font"			"TargetID_small"
		"xpos"			"0"
		"ypos"			"2"
		"zpos"			"1"
		"wide"			"6969"
		"tall"			"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"labelText"		"%targetname%"
		"textAlignment"		"West"
		"proportionaltoparent"	"1"
	}
    "TargetNameLabelS"
	{	
		"ControlName"		"Label"
		"fieldName"		"TargetNameLabelS"
		"font"			"TargetID_small"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"1"
		"wide"			"6969"
		"tall"			"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"labelText"		"%targetname%"
        "TextColor" "Main_Shadow_Transparent"
        "alpha" "200"
		"textAlignment"		"West"
		"proportionaltoparent"	"1"
        "pin_to_sibling"    "targetnamelabel"
	}
	
	"TargetDataLabel"
	{	
		"ControlName"		"Label"
		"fieldName"		"TargetDataLabel"
		"font"			"TargetID_data"
		"xpos"			"8"
		"ypos"			"26"
		"zpos"			"1"
		"wide"			"6969"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"labelText"		"%targetdata%"
		"textAlignment"		"West"
		"proportionaltoparent"	"1"
		//"DisabledFgColor2_override"		"CSSOrangeBright"
	}
	"SpectatorGUIHealth"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"SpectatorGUIHealth"
		"xpos"			"15"
		"ypos"			"10"
		"wide"			"35"
		"tall"			"18"
		"visible"		"0"
		"enabled"		"0"	
		"HealthBonusPosAdj"	"0"
		"HealthDeathWarning"	"0.49"
		"TFFont"		"Ingame_Medium"
		"HealthDeathWarningColor"	"HUDDeathWarning"
		"TextColor"		"White"
		"proportionaltoparent"	"1"

        "PlayerStatusHealthValueID"
        {
            "ControlName"								"CExLabel"
            "fieldName"									"PlayerStatusHealthValueID"
            "xpos"										"0"
            "ypos"										"0"
            "zpos"										"20"
            "wide"										"f0"
            "tall"										"18"
            "visible"									"1"
            "enabled"									"1"
            "textAlignment"								"west"
            "labeltext"									"%Health%"
            "font"										"Ingame_Medium"
            "fgcolor"									"White"
        }
        "PlayerStatusHealthValueShadow"
        {
            "ControlName"								"CExLabel"
            "fieldName"									"PlayerStatusHealthValueShadow"
            "xpos"										"-1"
            "ypos"										"-1"
            "zpos"										"19"
            "wide"										"f0"
            "tall"										"18"
            "visible"									"1"
            "enabled"									"1"
            "textAlignment"								"west"
            "labeltext"									"%Health%"
            "font"										"Ingame_Medium"
            "fgcolor"									"Main_Shadow_Transparent"

            "pin_to_sibling"							"PlayerStatusHealthValueID"
        }
        "HealthValue_Target"							// Proportional positioning doesn't work :(
        {
            "Visible"									"0"
        }
        "HealthValue_Target_Shadow"
        {
            "Visible"									"0"
        }
	}
	
	"AmmoIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"AmmoIcon"
		"xpos"			"0"
		"ypos"			"20"
		"zpos"			"12"
		"wide"			"0"
		"tall"			"8"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/leaderboard_class_heavy"
		"scaleImage"	"1"
	}
	
	"KillStreakIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"KillStreakIcon"
		"xpos"			"10"
		"xpos_minmode"	"30"
		"ypos"			"20"
		"ypos_minmode"	"16"
		"zpos"			"12"
		"wide"			"0"
		"tall"			"8"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/leaderboard_streak"
		"scaleImage"	"1"
	}
	
	"MoveableSubPanel"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"MoveableSubPanel"
		"xpos"			"-100"
		"ypos"			"0"
		"zpos"			"-5"
		"wide"			"0"
		"tall"			"36"
		"visible"		"0"
		"enabled"		"1"	
		
		"MoveableIconBG"
		{
			"ControlName"	"CIconPanel"
			"fieldName"		"MoveableIconBG"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"36"
			"visible"		"0"
			"enabled"		"1"
			"icon"			"obj_status_alert_background_tall_nocolor"
			"iconColor"		"HudBlack"
			"scaleImage"	"1"
		}
		
		"MoveableIcon"
		{
			"ControlName"	"CIconPanel"
			"fieldName"		"MoveableIcon"
			"xpos"			"5"
			"ypos"			"7"
			"zpos"			"11"
			"wide"			"0"
			"tall"			"14"
			"visible"		"1"
			"enabled"		"1"
			"icon"			"obj_status_sentrygun_1"
			"drawcolor"		"ProgressOffWhite"
			"scaleImage"	"1"
		}
		"MoveableSymbolIcon"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"MoveableSymbolIcon"
			"xpos"			"16"
			"ypos"			"-2"
			"zpos"			"12"
			"wide"			"0"
			"tall"			"8"
			"visible"		"1"
			"enabled"		"1"
			"image"			"../hud/eng_sel_item_movable"
			"drawcolor"		"ProgressOffWhite"
			"scaleImage"	"1"
		}

		"MoveableKeyLabel"
		{	
			"ControlName"		"Label"
			"fieldName"		"MoveableKeyLabel"
			"font"			"Default"
			"fgcolor_override"			"white"
			"xpos"			"-5"
			"ypos"			"13"
			"zpos"			"1"
			"wide"			"0"
			"tall"			"0"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"%movekey%"
			"textAlignment"		"north"
			"dulltext"		"0"
			"proportionaltoparent"	"1"
			"brighttext"		"0"
			"AllCaps"	"1"
		}
		
		"MoveableLabel"
		{	
			"ControlName"		"CExLabel"
			"fieldName"		"MoveableLabel"
			"font"			"Default"
			"fgcolor_override"			"white"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"100"
			"tall"			"14"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"PICKUP"
			"textAlignment"		"north"
			"dulltext"		"0"
			"proportionaltoparent"	"1"
			"brighttext"		"0"
			
			"pin_to_sibling"	"MoveableKeyLabel"
			"pin_to_sibling_corner"	"6"
			"pin_corner_to_sibling"	"4"
		}
	}
	"AvatarImage"
	{
		"ControlName"	"CAvatarImagePanel"
		"fieldName"		"AvatarImage"
		"xpos"			"6"
		"xpos_minmode"	"6"
		"ypos"			"6"	[$WIN32]
		"ypos"			"0"	[$X360]
		"zpos"			"99"
		"wide"			"11"
		"tall"			"11"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"	"1"	
		"color_outline"	"52 48 45 255"
	}

    // disable jump mode stuff
    "TargetNameLabelC"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"TargetNameLabelC"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
		"enabled"									"0"
	}

    "TargetNameLabelCs"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"TargetNameLabelCs"
        "wide"										"0"
		"tall"										"0"
		"visible"									"0"
		"enabled"									"0"

	}
	"TargetDataLabelC" // disabled
	{
		"ControlName"		       					"CExLabel"
		"fieldName"		        					"TargetDataLabelC"
        "wide"										"0"
		"tall"										"0"
		"visible"									"0"
		"enabled"									"0"
	}
	"TargetDataLabelCs" // disabled
	{
		"ControlName"		       					"CExLabel"
		"fieldName"		        					"TargetDataLabelCs"
        "wide"										"0"
		"tall"										"0"
		"visible"									"0"
		"enabled"									"0"
	}
}
