"Resource/UI/HudMatchStatus_Base.res"
{
    "TeamStatus"
    {
        "ControlName"               "CTFTeamStatus"
        "FieldName"                 "TeamStatus"
        "XPos"                      "0"
        "YPos"                      "0"
        "ZPos"                      "2"
        "Wide"                      "f0"
        "Tall"                      "15"
        "Visible"                   "1"
        "Enabled"                   "1"
        "max_size"                  "19"
        "6v6_gap"                   "1"
        "12v12_gap"                 "1"
        "team1_grow_dir"            "west"
        "team1_base_x"              "c-50"
        "team1_max_expand"          "200"
        "team2_grow_dir"            "east"
        "team2_base_x"              "c51"
        "team2_max_expand"          "200"
        "PlayerPanels_KV"
        {
            "Visible"                                       "0"
            "Wide"                                          "f0"
            "Tall"                                          "f0"
            "ZPos"                                          "1"
            "ProportionalToParent"                          "1"
            "color_portrait_bg_red"                         "Red"
            "color_portrait_bg_blue"                        "Blue"
            "color_portrait_bg_red_dead"                    "15 15 15 255"
            "color_portrait_bg_blue_dead"                   "15 15 15 255"
            "color_bar_health_high"                         "105 180 75 255"
            "color_bar_health_med"                          "255 200 0 255"
            "percentage_health_med"                         "0.6"
            "color_bar_health_low"                          "255 40 40 255"
            "percentage_health_low"                         "0.3"
            "color_portrait_blend_dead_red"                 "White"
            "color_portrait_blend_dead_blue"                "White"
            "color_portrait_bg_red_local_player"            "15 15 15 255"
            "color_portrait_bg_blue_local_player"           "15 15 15 255"
            "PlayerName"
            {
                "ControlName"                   "CExLabel"
                "FieldName"                     "PlayerName"
                "XPos"                          "0"
                "YPos"                          "rs1"
                "ZPos"                          "5"
                "Wide"                          "f0"
                "Tall"                          "6"
                "Visible"                       "0"
                "LabelText"                     "%playername%"
                "Font"                          "Ingame_Tiny"
                "TextInsetX"                    "1"
                "TextAlignment"                 "west"
                "BGColor_Override"              "TransparentLightBlack"
                "ProportionalToParent"          "1"
                "FGColor"                       "White"
            }
            "ClassImage"
            {
                "ControlName"                   "CTFClassImage"
                "FieldName"                     "ClassImage"
                "XPos"                          "cs-0.5"
                "YPos"                          "0"
                "ZPos"                          "5"
                "Wide"                          "o1"
                "Tall"                          "f0"
                "Visible"                       "1"
                "Enabled"                       "1"
                "Image"                         "../hud/class_scoutred"
                "ScaleImage"                    "1"
                "ProportionalToParent"          "1"
            }
            "ClassImageBG"
            {
                "ControlName"                   "Panel"
                "FieldName"                     "ClassImageBG"
                "XPos"                          "0"
                "YPos"                          "0"
                "ZPos"                          "2"
                "Wide"                          "f0"
                "Tall"                          "f0"
                "Visible"                       "1"
                "Enabled"                       "1"
                "PaintBackgroundType"           "0"
                "ProportionalToParent"          "1"
            }
            "HealthBar"
            {
                "ControlName"                   "ContinuousProgressBar"
                "FieldName"                     "HealthBar"
                "XPos"                          "0"
                "YPos"                          "0"
                "ZPos"                          "3"
                "Wide"                          "9999"
                "Tall"                          "f0"
                "Visible"                       "1"
                "Enabled"                       "1"
                "BGColor_Override"              "30 30 30 255"
                "ProportionalToParent"          "1"
            }
            "OverhealBar"
            {
                "ControlName"                   "ContinuousProgressBar"
                "FieldName"                     "OverhealBar"
                "XPos"                          "0"
                "YPos"                          "0"
                "ZPos"                          "4"
                "Wide"                          "f0"
                "Tall"                          "f0"
                "Visible"                       "1"
                "Enabled"                       "1"
                "BGColor_Override"              "Blank"
                "FGColor_Override"              "255 255 255 180"
                "ProportionalToParent"          "1"
            }
            "RespawnTime"
            {
                "ControlName"                   "CExLabel"
                "FieldName"                     "RespawnTime"
                "Font"                          "m0refont12Shadow"
                "XPos"                          "cs-0.5"
                "YPos"                          "cs-0.5"
                "ZPos"                          "10"
                "Wide"                          "f0"
                "Tall"                          "f0"
                "Visible"                       "1"
                "LabelText"                     "%respawntime%"
                "TextAlignment"                 "center"
                "ProportionalToParent"          "1"
                "FGColor"                       "255 255 0 255"
            }
        }
    }
    "BlueTeamPanel"
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "BlueTeamPanel"
        "XPos"                  "-155"
        "YPos"                  "125"
        "ZPos"                  "50"
        "Wide"                  "150"
        "Tall"                  "260"
        "Visible"               "0"
        "Enabled"               "1"
        "alpha"                 "255"
        "if_large"
        {
            "YPos"          "65"
            "Tall"          "385"
        }
        "BlueTeamBG"
        {
            "ControlName"           "EditablePanel"
            "FieldName"             "BlueTeamBG"
            "XPos"                  "0"
            "YPos"                  "10"
            "ZPos"                  "2"
            "Wide"                  "147"
            "Tall"                  "36"
            "Visible"               "1"
            "Enabled"               "1"
            "Border"                "TFFatLineBorderBlueBGOpaque"
        }
        "BlueTeamImage"
        {
            "ControlName"           "ImagePanel"
            "FieldName"             "BlueTeamImage"
            "XPos"                  "9"
            "YPos"                  "0"
            "ZPos"                  "5"
            "Wide"                  "56"
            "Tall"                  "56"
            "Visible"               "1"
            "Enabled"               "1"
            "Image"                 "../hud/team_blue"
            "ScaleImage"            "1"
        }
        "BlueTeamLabel"
        {
            "ControlName"           "CExLabel"
            "FieldName"             "BlueTeamLabel"
            "Font"                  "CompMatchStartTeamNames"
            "LabelText"             "%blueteamname%"
            "TextAlignment"         "center"
            "XPos"                  "48"
            "YPos"                  "13"
            "ZPos"                  "20"
            "Wide"                  "95"
            "Tall"                  "30"
            "Visible"               "1"
            "Enabled"               "1"
            "CenterWrap"            "1"
        }
        "BlueLeaderAvatar"
        {
            "ControlName"           "CAvatarImagePanel"
            "FieldName"             "BlueLeaderAvatar"
            "XPos"                  "11"
            "YPos"                  "10"
            "ZPos"                  "5"
            "Wide"                  "35"
            "Tall"                  "35"
            "Visible"               "1"
            "Enabled"               "1"
            "Image"                 ""
            "ScaleImage"            "1"
            "color_outline"         "52 48 45 255"
        }
        "BlueLeaderAvatarBG"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "BlueLeaderAvatarBG"
            "XPos"                          "9"
            "YPos"                          "8"
            "ZPos"                          "4"
            "Wide"                          "39"
            "Tall"                          "39"
            "Visible"                       "1"
            "PaintBackgroundType"           "2"
            "BGColor_Override"              "117 107 94 255"
        }
        "BluePlayerList"
        {
            "ControlName"           "SectionedListPanel"
            "FieldName"             "BluePlayerList"
            "XPos"                  "6"
            "YPos"                  "38"
            "ZPos"                  "1"
            "Wide"                  "136"
            "Tall"                  "205"
            "Visible"               "1"
            "Enabled"               "1"
            "autoresize"            "3"
            "linespacing"           "26"
            "linegap"               "4"
            // "show_columns"						"1"
            "if_large"
            {
                "Tall"          "315"
            }
        }
        "BluePlayerListBG"
        {
            "ControlName"           "EditablePanel"
            "FieldName"             "BluePlayerListBG"
            "XPos"                  "4"
            "YPos"                  "30"
            "ZPos"                  "0"
            "Wide"                  "139"
            "Tall"                  "215"
            "Visible"               "1"
            "Enabled"               "1"
            "Border"                "TFFatLineBorderClearBG"
            "if_large"
            {
                "Tall"          "325"
            }
        }
    }
    "RedTeamPanel"
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "RedTeamPanel"
        "XPos"                  "r-5"
        "YPos"                  "125"
        "ZPos"                  "50"
        "Wide"                  "150"
        "Tall"                  "260"
        "Visible"               "0"
        "Enabled"               "1"
        "alpha"                 "255"
        "if_large"
        {
            "YPos"          "65"
            "Tall"          "385"
        }
        "RedTeamBG"
        {
            "ControlName"           "EditablePanel"
            "FieldName"             "RedTeamBG"
            "XPos"                  "0"
            "YPos"                  "10"
            "ZPos"                  "2"
            "Wide"                  "147"
            "Tall"                  "36"
            "Visible"               "1"
            "Enabled"               "1"
            "Border"                "TFFatLineBorderRedBGOpaque"
        }
        "RedTeamImage"
        {
            "ControlName"           "ImagePanel"
            "FieldName"             "RedTeamImage"
            "XPos"                  "84"
            "YPos"                  "-9"
            "ZPos"                  "5"
            "Wide"                  "70"
            "Tall"                  "70"
            "Visible"               "1"
            "Enabled"               "1"
            "Image"                 "../hud/team_Red"
            "ScaleImage"            "1"
        }
        "RedTeamLabel"
        {
            "ControlName"           "CExLabel"
            "FieldName"             "RedTeamLabel"
            "Font"                  "CompMatchStartTeamNames"
            "LabelText"             "%redteamname%"
            "TextAlignment"         "center"
            "XPos"                  "5"
            "YPos"                  "13"
            "ZPos"                  "20"
            "Wide"                  "95"
            "Tall"                  "30"
            "Visible"               "1"
            "Enabled"               "1"
            "CenterWrap"            "1"
        }
        "RedLeaderAvatar"
        {
            "ControlName"           "CAvatarImagePanel"
            "FieldName"             "RedLeaderAvatar"
            "XPos"                  "102"
            "YPos"                  "10"
            "ZPos"                  "5"
            "Wide"                  "35"
            "Tall"                  "35"
            "Visible"               "1"
            "Enabled"               "1"
            "Image"                 ""
            "ScaleImage"            "1"
            "color_outline"         "52 48 45 255"
        }
        "RedLeaderAvatarBG"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "RedLeaderAvatarBG"
            "XPos"                          "100"
            "YPos"                          "8"
            "ZPos"                          "4"
            "Wide"                          "39"
            "Tall"                          "39"
            "Visible"                       "1"
            "PaintBackgroundType"           "2"
            "BGColor_Override"              "117 107 94 255"
        }
        "RedPlayerList"
        {
            "ControlName"           "SectionedListPanel"
            "FieldName"             "RedPlayerList"
            "XPos"                  "6"
            "YPos"                  "38"
            "ZPos"                  "1"
            "Wide"                  "136"
            "Tall"                  "205"
            "Visible"               "1"
            "Enabled"               "1"
            "autoresize"            "3"
            "linespacing"           "26"
            "linegap"               "4"
            // "show_columns"						"1"
            "if_large"
            {
                "Tall"          "315"
            }
        }
        "RedPlayerListBG"
        {
            "ControlName"           "EditablePanel"
            "FieldName"             "RedPlayerListBG"
            "XPos"                  "4"
            "YPos"                  "30"
            "ZPos"                  "0"
            "Wide"                  "139"
            "Tall"                  "215"
            "Visible"               "1"
            "Enabled"               "1"
            "Border"                "TFFatLineBorderClearBG"
            "if_large"
            {
                "Tall"          "325"
            }
        }
    }
}