"Resource/UI/custom/#Customization_Menu/HUD_Customization_Speedos_Demo.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Speedos_DynamicColors_Info"
			{
				"ControlName"							"EditablePanel"
				"FieldName"								"HUD_Speedos_DynamicColors_Info"
				"XPos"									"rs1-30"
				"YPos"									"cs-0.5"
				"ZPos"									"1"
				"Wide"									"400"
				"Tall"									"224"
				"Visible"								"0"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"PaintBackground"						"1"
				"paintBackgroundType"					"0"
				"BGColor_Override"						"30 30 30 255"

                "Title_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title_Icon"
					"XPos"								"4"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"20"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"1"
					"Font"								"HypnotizeIcons18"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
                "Title"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title"
					"XPos"								"15"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"DYNAMIC COLORS INFO"
					"Font"								"HudFontSmallishbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
                "SubTitle"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"SubTitle"
					"XPos"								"20"
					"YPos"								"rs1-4"
					"ZPos"								"0"
					"Wide"								"390"
					"Tall"								"8"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"These ranges can be adjusted in jumphud/materials/vgui/replay/thumbnails/speedo/color/ranges/"
					"Font"								"HudFontVerySmallBold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
                "Separator_1"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_1"
					"XPos"								"3"
					"YPos"								"25"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
                "Column_Left"
                {
                    "ControlName"                       "EditablePanel"
                    "FieldName"                         "Column_Left"
                    "xpos"                              "15"
                    "ypos"                              "35"
                    "wide"                              "p0.45"
                    "tall"                              "p0.78"
                    "proportionaltoparent"              "1"
                    "visible"                           "1"
                    "enabled"                           "1"

                    "paintbackground"                   "1"
                    "bgcolor_override"                  "Background_Main"

                    "SubTitle"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"SubTitle"
                        "XPos"								"5"
                        "YPos"								"0"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Soldier Dynamic Color Ranges"
                        "Font"								"HudFontSmallishBold"
                        "TextAlignment"						"west"
                        "FGColor"							"Gray"
                    }
                    "Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f20"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"SubTitle"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
                    "Subheading_1"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Subheading_1"
                        "XPos"								"0"
                        "YPos"								"1"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Horizontal"
                        "Font"								"HudFontSmallBold"
                        "TextAlignment"						"west"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Separator_1"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator_1"
						"XPos"							"2"
						"YPos"							"-1"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Subheading_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
                    "Range_1"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Range_1"
                        "XPos"								"0"
                        "YPos"								"-2"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"1050 - 1150 u/s"
                        "Font"								"HudFontSmall"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"m0reGreen"

                        "Pin_To_Sibling"				"Subheading_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Range_1B"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Range_1B"
                        "XPos"								"-85"
                        "YPos"								"0"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"850 - 1350 u/s"
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"m0reBlue"

                        "Pin_To_Sibling"				"Range_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPLEFT"
                    }
                    "Info_1"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_1"
                        "XPos"								"0"
                        "YPos"								"-5"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"15"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Rocket speed"
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Range_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Subheading_2"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Subheading_2"
                        "XPos"								"0"
                        "YPos"								"1"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Vertical"
                        "Font"								"HudFontSmallBold"
                        "TextAlignment"						"west"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Info_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Separator_2"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator_2"
						"XPos"							"2"
						"YPos"							"-1"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Subheading_2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
                    "Range_2"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Range_2"
                        "XPos"								"0"
                        "YPos"								"-2"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"None"
                        "Font"								"HudFontSmall"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"White"

                        "Pin_To_Sibling"				"Subheading_2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Info_2"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_2"
                        "XPos"								"0"
                        "YPos"								"-5"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"15"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							""
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Range_2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Subheading_3"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Subheading_3"
                        "XPos"								"0"
                        "YPos"								"1"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Absolute"
                        "Font"								"HudFontSmallBold"
                        "TextAlignment"						"west"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Info_2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Separator_3"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator_3"
						"XPos"							"2"
						"YPos"							"-1"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Subheading_3"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
                    "Range_3"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Range_3"
                        "XPos"								"0"
                        "YPos"								"-2"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"1050 - 1150 u/s"
                        "Font"								"HudFontSmall"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"m0reGreen"

                        "Pin_To_Sibling"				"Subheading_3"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Range_3B"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Range_3B"
                        "XPos"								"-85"
                        "YPos"								"0"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"850 - 1350 u/s"
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"m0reBlue"

                        "Pin_To_Sibling"				"Range_3"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPLEFT"
                    }
                    "Info_3"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_3"
                        "XPos"								"0"
                        "YPos"								"-5"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"15"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Rocket speed"
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Range_3"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                }
                "Column_Right"
                {
                    "ControlName"                       "EditablePanel"
                    "FieldName"                         "Column_Right"
                    "xpos"                              "rs1-15"
                    "ypos"                              "35"
                    "wide"                              "p0.45"
                    "tall"                              "p0.78"
                    "proportionaltoparent"              "1"
                    "visible"                           "1"
                    "enabled"                           "1"

                    "paintbackground"                   "1"
                    "bgcolor_override"                  "Background_Main"

                    "SubTitle"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"SubTitle"
                        "XPos"								"5"
                        "YPos"								"0"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Demo Dynamic Color Ranges"
                        "Font"								"HudFontSmallishBold"
                        "TextAlignment"						"west"
                        "FGColor"							"Gray"
                    }
                    "Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f20"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"SubTitle"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
                    "Subheading_1"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Subheading_1"
                        "XPos"								"0"
                        "YPos"								"1"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Horizontal"
                        "Font"								"HudFontSmallBold"
                        "TextAlignment"						"west"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Separator_1"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator_1"
						"XPos"							"2"
						"YPos"							"-1"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Subheading_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
                    "Range_1"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Range_1"
                        "XPos"								"0"
                        "YPos"								"-2"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"850 - 900 u/s"
                        "Font"								"HudFontSmall"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"m0reGreen"

                        "Pin_To_Sibling"				"Subheading_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Range_1B"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Range_1B"
                        "XPos"								"-85"
                        "YPos"								"0"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"700 - 1200 u/s"
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"m0reBlue"

                        "Pin_To_Sibling"				"Range_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPLEFT"
                    }
                    "Info_1"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_1"
                        "XPos"								"0"
                        "YPos"								"-5"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"15"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Uncharged horizontal airpogo"
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Range_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Subheading_2"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Subheading_2"
                        "XPos"								"0"
                        "YPos"								"1"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Vertical"
                        "Font"								"HudFontSmallBold"
                        "TextAlignment"						"west"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Info_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Separator_2"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator_2"
						"XPos"							"2"
						"YPos"							"-1"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Subheading_2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
                    "Range_2"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Range_2"
                        "XPos"								"0"
                        "YPos"								"-2"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"1100 - 1200 u/s"
                        "Font"								"HudFontSmall"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"m0reGreen"

                        "Pin_To_Sibling"				"Subheading_2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Range_2B"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Range_2B"
                        "XPos"								"-85"
                        "YPos"								"0"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"800 - 1500 u/s"
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"m0reBlue"

                        "Pin_To_Sibling"				"Range_2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPLEFT"
                    }
                    "Info_2"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_2"
                        "XPos"								"0"
                        "YPos"								"-5"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"15"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Crouched vertical airpogo"
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Range_2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Info_2B"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_2B"
                        "XPos"								"0"
                        "YPos"								"-2"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"23"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Ideally you want to fire at 1100 u/s, so fire slightly after the speedo flashes green"
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Info_2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Subheading_3"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Subheading_3"
                        "XPos"								"0"
                        "YPos"								"-2"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Absolute"
                        "Font"								"HudFontSmallBold"
                        "TextAlignment"						"west"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Info_2B"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Separator_3"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator_3"
						"XPos"							"2"
						"YPos"							"-1"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Subheading_3"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
                    "Range_3"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Range_3"
                        "XPos"								"0"
                        "YPos"								"-2"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"None"
                        "Font"								"HudFontSmall"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"White"

                        "Pin_To_Sibling"				"Subheading_3"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Info_3"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_3"
                        "XPos"								"0"
                        "YPos"								"-5"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"15"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							""
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Range_3"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                }
         
                "CloseButton"
                {
                    "ControlName"								"CExButton"
                    "FieldName"									"CloseButton"
                    "XPos"										"rs1-2"
                    "YPos"										"2"
                    "ZPos"										"20"
                    "Wide"										"18"
                    "Tall"										"18"
                    "Visible"									"1"
                    "Enabled"									"1"
                    "ProportionalToParent"						"1"
                    "LabelText"									"X"
                    "Font"										"Symbols16"
                    "TextAlignment"								"center"
                    "Command"									"engine jh_customization_submenu_clear; hud_reloadscheme" 
                    "ActionSignalLevel"							"4"
                    "Sound_Depressed"							"UI/buttonclick.wav"
                    "PaintBackground"							"1"

                    "DefaultFGColor_Override"					"White"
                    "ArmedFGColor_Override"						"White"
                    "DepressedFGColor_Override"					"White"

                    "DefaultBGColor_Override"					"Button_Red"
                    "ArmedBGColor_Override"						"Button_Red_Hover"
                    "DepressedBGColor_Override"					"Button_Red_Hover"
                }
			}
		}
	}
}