"Resource/UI/custom/#Customization_Menu/HUD_Customization_Miscellaneous.res"
{
    "SafeMode"
    {
        "Customizations_Panel"
        {
            "HUD_Shaders_Selection"
            {
                "ControlName"                   "CScrollableList"
                "FieldName"                     "HUD_Shaders_Selection"
                "XPos"                          "cs-0.5"
                "YPos"                          "cs-0.5"
                "ZPos"                          "0"
                "Wide"                          "f0"
                "Tall"                          "f0"
                "Visible"                       "0"
                "Enabled"                       "1"
                "ProportionalToParent"          "1"
                "PaintBackground"               "0"
                "paintBackgroundType"           "0"
                "BGColor_Override"              "Black"
                "Scrollbar"
                {
                    "XPos"                          "rs1+1"
                    "YPos"                          "0"
                    "Wide"                          "6"
                    "Tall"                          "f0"
                    "ZPos"                          "1000"
                    "ProportionalToParent"          "1"
                    "Slider"
                    {
                        "PaintBackgroundType"           "0"
                        "FGColor_Override"              "ScrollBar"
                    }
                    "nobuttons"                     "1"
                }
                "Title_Icon"
                {
                    "ControlName"                   "CExLabel"
                    "FieldName"                     "Title_Icon"
                    "XPos"                          "4"
                    "YPos"                          "0"
                    "ZPos"                          "0"
                    "Wide"                          "20"
                    "Tall"                          "25"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "ProportionalToParent"          "1"
                    "LabelText"                     "$"
                    "Font"                          "Symbols24"
                    "TextAlignment"                 "center"
                    "FGColor"                       "Gray"
                }
                "Title"
                {
                    "ControlName"                   "CExLabel"
                    "FieldName"                     "Title"
                    "XPos"                          "30"
                    "YPos"                          "0"
                    "ZPos"                          "0"
                    "Wide"                          "f25"
                    "Tall"                          "25"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "ProportionalToParent"          "1"
                    "LabelText"                     "SHADERS"
                    "Font"                          "HudFontMediumbold"
                    "TextAlignment"                 "west"
                    "FGColor"                       "Gray"
                }
                "SubTitle"
                {
                    "ControlName"                   "CExLabel"
                    "FieldName"                     "SubTitle"
                    "XPos"                          "30"
                    "YPos"                          "22"
                    "ZPos"                          "0"
                    "Wide"                          "f0"
                    "Tall"                          "12"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "ProportionalToParent"          "1"
                    "LabelText"                     "Some shaders are very dark, try using them in combination with mat_fullbright 1"
                    "Font"                          "Menu_Tiny"
                    "TextAlignment"                 "west"
                    "FGColor"                       "Gray"
                }
                "Separator_1"
                {
                    "ControlName"                   "EditablePanel"
                    "FieldName"                     "Separator_1"
                    "XPos"                          "3"
                    "YPos"                          "35"
                    "ZPos"                          "0"
                    "Wide"                          "f40"
                    "Tall"                          "2"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "ProportionalToParent"          "1"
                    "paintBackground"               "1"
                    "paintBackgroundtype"           "3"
                    "BGcolor_Override"              "Background_Bright"
                }
                // VISIBILITY ------------------------------------------------------------------------------------------------------------
                "Shader_Visibility"
                {
                    "ControlName"                   "EditablePanel"
                    "FieldName"                     "Shader_Visibility"
                    "XPos"                          "4"
                    "YPos"                          "41"
                    "ZPos"                          "20"
                    "Wide"                          "170"
                    "Tall"                          "80"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "ProportionalToParent"          "1"
                    "Visibility_Label"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Visibility_Label"
                        "XPos"                          "0"
                        "YPos"                          "0"
                        "ZPos"                          "0"
                        "Wide"                          "f25"
                        "Tall"                          "15"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "AllCaps"                       "1"
                        "LabelText"                     "Shader Visibility"
                        "Font"                          "HudFontSmallBold"
                        "TextAlignment"                 "west"
                        "FGColor"                       "Gray"
                    }
                    "Separator"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Separator"
                        "XPos"                          "2"
                        "YPos"                          "1"
                        "ZPos"                          "0"
                        "Wide"                          "f40"
                        "Tall"                          "1"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "paintBackground"               "1"
                        "paintBackgroundtype"           "3"
                        "BGcolor_Override"              "Background_Bright"
                        "Pin_To_Sibling"                "Visibility_Label"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Shaders_ON"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Shaders_ON"
                        "XPos"                          "-2"
                        "YPos"                          "5"
                        "ZPos"                          "1"
                        "Wide"                          "68"
                        "Tall"                          "50"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "PaintBackground"               "1"
                        "BGcolor_Override"              "CustomizationOptionBG"
                        "Pin_To_Sibling"                "Separator"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                        "Shader_Icon"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Icon"
                            "XPos"                          "cs-0.5"
                            "YPos"                          "0"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "f12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "Symbols35"
                            "LabelText"                     "V"
                            "TextAlignment"                 "center"
                            "FGColor"                       "White"
                        }
                        "Shader_Label"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Label"
                            "XPos"                          "0"
                            "YPos"                          "rs1"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "FontStorePrice"
                            "LabelText"                     "Enabled"
                            "TextAlignment"                 "center"
                            "FGColor"                       "Gray"
                            "PaintBackground"               "1"
                            "PaintBackgroundType"           "0"
                            "BGColor_Override"              "Background_Darkest"
                        }
                        "Shader_Button"
                        {
                            "ControlName"                   "CExButton"
                            "FieldName"                     "Shader_Button"
                            "XPos"                          "0"
                            "YPos"                          "0"
                            "ZPos"                          "5"
                            "Wide"                          "f0"
                            "Tall"                          "f0"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "Font"                          ""
                            "Command"                       "engine jh_shader_vis_enabled"
                            "LabelText"                     ""
                            "Sound_Depressed"               "UI/buttonclick.wav"
                            "ProportionalToParent"          "1"
                            "ActionSignalLevel"             "6"
                            "PaintBackground"               "0"
                            "PaintBorder"                   "1"
                            "border_default"                "NoBorder"
                            "border_armed"                  "BorderSelectionGray"
                        }
                    }
                    "Shaders_OFF"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Shaders_OFF"
                        "XPos"                          "5"
                        "YPos"                          "0"
                        "ZPos"                          "1"
                        "Wide"                          "68"
                        "Tall"                          "50"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "PaintBackground"               "1"
                        "BGcolor_Override"              "CustomizationOptionBG"
                        "Pin_To_Sibling"                "Shaders_ON"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_TOPRIGHT"
                        "Shader_Icon"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Icon"
                            "XPos"                          "cs-0.5"
                            "YPos"                          "0"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "f12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "Symbols35"
                            "LabelText"                     "X"
                            "TextAlignment"                 "center"
                            "FGColor"                       "White"
                        }
                        "Shader_Label"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Label"
                            "XPos"                          "0"
                            "YPos"                          "rs1"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "FontStorePrice"
                            "LabelText"                     "Disabled"
                            "TextAlignment"                 "center"
                            "FGColor"                       "Gray"
                            "PaintBackground"               "1"
                            "PaintBackgroundType"           "0"
                            "BGColor_Override"              "Background_Darkest"
                        }
                        "Shader_Button"
                        {
                            "ControlName"                   "CExButton"
                            "FieldName"                     "Shader_Button"
                            "XPos"                          "0"
                            "YPos"                          "0"
                            "ZPos"                          "5"
                            "Wide"                          "f0"
                            "Tall"                          "f0"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "Font"                          ""
                            "Command"                       "engine jh_shader_vis_disabled"
                            "LabelText"                     ""
                            "Sound_Depressed"               "UI/buttonclick.wav"
                            "ProportionalToParent"          "1"
                            "ActionSignalLevel"             "6"
                            "PaintBackground"               "0"
                            "PaintBorder"                   "1"
                            "border_default"                "NoBorder"
                            "border_armed"                  "BorderSelectionGray"
                        }
                    }
                }
                "Mirror_World"
                {
                    "ControlName"                   "EditablePanel"
                    "FieldName"                     "Mirror_World"
                    "XPos"                          "180"
                    "YPos"                          "41"
                    "ZPos"                          "20"
                    "Wide"                          "170"
                    "Tall"                          "80"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "ProportionalToParent"          "1"
                    "Heading"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Heading"
                        "XPos"                          "0"
                        "YPos"                          "0"
                        "ZPos"                          "0"
                        "Wide"                          "f25"
                        "Tall"                          "15"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "AllCaps"                       "1"
                        "LabelText"                     "Mirror World"
                        "Font"                          "HudFontSmallBold"
                        "TextAlignment"                 "west"
                        "FGColor"                       "Gray"
                    }
                    "Separator"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Separator"
                        "XPos"                          "2"
                        "YPos"                          "1"
                        "ZPos"                          "0"
                        "Wide"                          "f40"
                        "Tall"                          "1"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "paintBackground"               "1"
                        "paintBackgroundtype"           "3"
                        "BGcolor_Override"              "Background_Bright"
                        "Pin_To_Sibling"                "Heading"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Mirror_World_Toggle"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Mirror_World_Toggle"
                        "XPos"                          "0"
                        "YPos"                          "5"
                        "ZPos"                          "1"
                        "Wide"                          "150"
                        "Tall"                          "22"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "PaintBackground"               "0"
                        "Pin_To_Sibling"                "Separator"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                        "Toggle_Button"
                        {
                            "ControlName"                       "CExButton"
                            "FieldName"                         "Toggle_Button"
                            "XPos"                              "0"
                            "YPos"                              "0"
                            "ZPos"                              "20"
                            "Wide"                              "f0"
                            "Tall"                              "f0"
                            "Visible"                           "1"
                            "Enabled"                           "1"
                            "ActionSignalLevel"                 "6"
                            "ProportionalToParent"              "1"
                            "LabelText"                         ""
                            "TextAlignment"                     "west"
                            "Command"                           "engine jh_mirrorworld_toggle; hud_reloadscheme"
                            "Sound_Depressed"                   "UI/buttonclick.wav"
                            "PaintBackground"                   "1"
                            "PaintBorder"                       "0"
                            "border_default"                    "NoBorder"
                            "border_armed"                      "BorderSelectionWhite"
                            "DefaultBGColor_Override"           "Blank"
                            "ArmedBGColor_Override"             "Button_Hover"
                            "DepressedBGColor_Override"         "Button_Hover"
                        }
                        "Check"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Check"
                            "XPos"                          "0"
                            "YPos"                          "cs-0.5"
                            "ZPos"                          "21"
                            "Wide"                          "22"
                            "Tall"                          "22"
                            "Visible"                       "0"
                            "Enabled"                       "1"
                            "AllCaps"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "Font"                          "Marlett"	// set in hudlayout_customization.res
                            "LabelText"                     "b"
                            "TextAlignment"                 "east"
                            "textinsetx"                    "1"
                            "Wrap"                          "0"
                            "FGColor"                       "White"
                        }
                        "Setting_Checkbox"	// dummy
                        {
                            "ControlName"                   "CvarToggleCheckButton"
                            "FieldName"                     "Setting_Checkbox"
                            "XPos"                          "0"
                            "YPos"                          "cs-0.5"
                            "ZPos"                          "21"
                            "Wide"                          "22"
                            "Tall"                          "22"
                            "ProportionalToParent"          "1"
                            "LabelText"                     ""
                            "TextAlignment"                 "west"
                            "SmallCheckImage"               "0"
                            "button_activation_type"        "1"
                            "cvar_name"                     ""
                            "MouseInputEnabled"             "0"
                        }
                        "Setting_Label"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Setting_Label"
                            "XPos"                          "26"
                            "YPos"                          "cs-0.5"
                            "ZPos"                          "21"
                            "Wide"                          "f24"
                            "Tall"                          "f0"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "AllCaps"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "Font"                          "HudFontSmallest"
                            "LabelText"                     "Overrides other shaders"
                            "TextAlignment"                 "west"
                            "Wrap"                          "0"
                            "FGColor"                       "White"
                        }
                    }
                }
                // SHADER OPTIONS -------------------------------------------------------------------------------------------------------
                "Shader_Styles"
                {
                    "ControlName"                   "EditablePanel"
                    "FieldName"                     "Shader_Styles"
                    "XPos"                          "4"
                    "YPos"                          "41+81"
                    "ZPos"                          "20"
                    "Wide"                          "f0"
                    "Tall"                          "280"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "ProportionalToParent"          "1"
                    "Shader_Label"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Shader_Label"
                        "XPos"                          "0"
                        "YPos"                          "0"
                        "ZPos"                          "0"
                        "Wide"                          "f25"
                        "Tall"                          "15"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "AllCaps"                       "1"
                        "LabelText"                     "Shader Options"
                        "Font"                          "HudFontSmallBold"
                        "TextAlignment"                 "west"
                        "FGColor"                       "Gray"
                    }
                    "Separator"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Separator"
                        "XPos"                          "2"
                        "YPos"                          "1"
                        "ZPos"                          "0"
                        "Wide"                          "f40"
                        "Tall"                          "1"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "paintBackground"               "1"
                        "paintBackgroundtype"           "3"
                        "BGcolor_Override"              "Background_Bright"
                        "Pin_To_Sibling"                "Shader_Label"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    // "Shader_Blur"
                    // {
                    // "ControlName"                   "EditablePanel"
                    // "FieldName"                     "Shader_Blur"
                    // "XPos"                          "5"
                    // "YPos"                          "4"
                    // "ZPos"                          "1"
                    // "Wide"                          "120"
                    // "Tall"                          "82"
                    // "Visible"                       "1"
                    // "Enabled"                       "1"
                    // "ProportionalToParent"          "1"
                    // "PaintBackground"               "1"
                    // "BGcolor_Override"              "CustomizationOptionBG"
                    // "Pin_To_Sibling"                "Separator"
                    // "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                    // "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    // "Shader_Image"
                    // {
                    // "ControlName"                   "ImagePanel"
                    // "FieldName"                     "Shader_Image"
                    // "XPos"                          "cs-0.5"
                    // "YPos"                          "cs-0.5-6"
                    // "ZPos"                          "0"
                    // "Wide"                          "120"
                    // "Tall"                          "70"
                    // "Visible"                       "1"
                    // "Enabled"                       "1"
                    // "MouseInputEnabled"             "0"
                    // "ScaleImage"                    "1"
                    // "ProportionalToParent"          "1"
                    // "Image"                         "replay/thumbnails/custom/shaders/blur"
                    // }
                    // "Shader_Label"
                    // {
                    // "ControlName"                   "CExLabel"
                    // "FieldName"                     "Shader_Label"
                    // "XPos"                          "0"
                    // "YPos"                          "rs1"
                    // "ZPos"                          "1"
                    // "Wide"                          "f0"
                    // "Tall"                          "12"
                    // "Visible"                       "1"
                    // "Enabled"                       "1"
                    // "MouseInputEnabled"             "0"
                    // "ProportionalToParent"          "1"
                    // "AllCaps"                       "1"
                    // "Font"                          "FontStorePrice"
                    // "LabelText"                     "Blur"
                    // "TextAlignment"                 "center"
                    // "FGColor"                       "Gray"
                    // "PaintBackground"               "1"
                    // "PaintBackgroundType"           "0"
                    // "BGColor_Override"              "Background_Darkest"
                    // }
                    // "Shader_Button"
                    // {
                    // "ControlName"                   "CExButton"
                    // "FieldName"                     "Shader_Button"
                    // "XPos"                          "0"
                    // "YPos"                          "0"
                    // "ZPos"                          "5"
                    // "Wide"                          "f0"
                    // "Tall"                          "f0"
                    // "Visible"                       "1"
                    // "Enabled"                       "1"
                    // "Font"                          ""
                    // "Command"                       "engine jh_shader_blur"
                    // "LabelText"                     ""
                    // "Sound_Depressed"               "UI/buttonclick.wav"
                    // "ProportionalToParent"          "1"
                    // "ActionSignalLevel"             "6"
                    // "PaintBackground"               "0"
                    // "PaintBorder"                   "1"
                    // "border_default"                "NoBorder"
                    // "border_armed"                  "BorderSelectionGray"
                    // }
                    // }
                    /////////////////////////
                    "Shader_Celshade"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Shader_Celshade"
                        "XPos"                          "-2"
                        "YPos"                          "4"
                        "ZPos"                          "1"
                        "Wide"                          "120"
                        "Tall"                          "82"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "PaintBackground"               "1"
                        "BGcolor_Override"              "CustomizationOptionBG"
                        "Pin_To_Sibling"                "Separator"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                        "Shader_Image"
                        {
                            "ControlName"                   "ImagePanel"
                            "FieldName"                     "Shader_Image"
                            "XPos"                          "cs-0.5"
                            "YPos"                          "cs-0.5-6"
                            "ZPos"                          "0"
                            "Wide"                          "120"
                            "Tall"                          "70"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ScaleImage"                    "1"
                            "ProportionalToParent"          "1"
                            "Image"                         "replay/thumbnails/custom/shaders/celshade"
                        }
                        "Shader_Label"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Label"
                            "XPos"                          "0"
                            "YPos"                          "rs1"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "FontStorePrice"
                            "LabelText"                     "Celshade"
                            "TextAlignment"                 "center"
                            "FGColor"                       "Gray"
                            "PaintBackground"               "1"
                            "PaintBackgroundType"           "0"
                            "BGColor_Override"              "Background_Darkest"
                        }
                        "Shader_Button"
                        {
                            "ControlName"                   "CExButton"
                            "FieldName"                     "Shader_Button"
                            "XPos"                          "0"
                            "YPos"                          "0"
                            "ZPos"                          "5"
                            "Wide"                          "f0"
                            "Tall"                          "f0"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "Font"                          ""
                            "Command"                       "engine jh_shader_celshade"
                            "LabelText"                     ""
                            "Sound_Depressed"               "UI/buttonclick.wav"
                            "ProportionalToParent"          "1"
                            "ActionSignalLevel"             "6"
                            "PaintBackground"               "0"
                            "PaintBorder"                   "1"
                            "border_default"                "NoBorder"
                            "border_armed"                  "BorderSelectionGray"
                        }
                    }
                    "Shader_Oilpaint"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Shader_Oilpaint"
                        "XPos"                          "5"
                        "YPos"                          "0"
                        "ZPos"                          "1"
                        "Wide"                          "120"
                        "Tall"                          "82"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "PaintBackground"               "1"
                        "BGcolor_Override"              "CustomizationOptionBG"
                        "Pin_To_Sibling"                "Shader_Celshade"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_TOPRIGHT"
                        "Shader_Image"
                        {
                            "ControlName"                   "ImagePanel"
                            "FieldName"                     "Shader_Image"
                            "XPos"                          "cs-0.5"
                            "YPos"                          "cs-0.5-6"
                            "ZPos"                          "0"
                            "Wide"                          "120"
                            "Tall"                          "70"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ScaleImage"                    "1"
                            "ProportionalToParent"          "1"
                            "Image"                         "replay/thumbnails/custom/shaders/oilpaint"
                        }
                        "Shader_Label"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Label"
                            "XPos"                          "0"
                            "YPos"                          "rs1"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "FontStorePrice"
                            "LabelText"                     "Oilpaint"
                            "TextAlignment"                 "center"
                            "FGColor"                       "Gray"
                            "PaintBackground"               "1"
                            "PaintBackgroundType"           "0"
                            "BGColor_Override"              "Background_Darkest"
                        }
                        "Shader_Button"
                        {
                            "ControlName"                   "CExButton"
                            "FieldName"                     "Shader_Button"
                            "XPos"                          "0"
                            "YPos"                          "0"
                            "ZPos"                          "5"
                            "Wide"                          "f0"
                            "Tall"                          "f0"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "Font"                          ""
                            "Command"                       "engine jh_shader_oilpaint"
                            "LabelText"                     ""
                            "Sound_Depressed"               "UI/buttonclick.wav"
                            "ProportionalToParent"          "1"
                            "ActionSignalLevel"             "6"
                            "PaintBackground"               "0"
                            "PaintBorder"                   "1"
                            "border_default"                "NoBorder"
                            "border_armed"                  "BorderSelectionGray"
                        }
                    }
                    "Shader_PSX"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Shader_PSX"
                        "XPos"                          "5"
                        "YPos"                          "0"
                        "ZPos"                          "1"
                        "Wide"                          "120"
                        "Tall"                          "82"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "PaintBackground"               "1"
                        "BGcolor_Override"              "CustomizationOptionBG"
                        "Pin_To_Sibling"                "Shader_Oilpaint"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_TOPRIGHT"
                        "Shader_Image"
                        {
                            "ControlName"                   "ImagePanel"
                            "FieldName"                     "Shader_Image"
                            "XPos"                          "cs-0.5"
                            "YPos"                          "cs-0.5-6"
                            "ZPos"                          "0"
                            "Wide"                          "120"
                            "Tall"                          "70"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ScaleImage"                    "1"
                            "ProportionalToParent"          "1"
                            "Image"                         "replay/thumbnails/custom/shaders/psx"
                        }
                        "Shader_Label"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Label"
                            "XPos"                          "0"
                            "YPos"                          "rs1"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "FontStorePrice"
                            "LabelText"                     "PSX"
                            "TextAlignment"                 "center"
                            "FGColor"                       "Gray"
                            "PaintBackground"               "1"
                            "PaintBackgroundType"           "0"
                            "BGColor_Override"              "Background_Darkest"
                        }
                        "Shader_Button"
                        {
                            "ControlName"                   "CExButton"
                            "FieldName"                     "Shader_Button"
                            "XPos"                          "0"
                            "YPos"                          "0"
                            "ZPos"                          "5"
                            "Wide"                          "f0"
                            "Tall"                          "f0"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "Font"                          ""
                            "Command"                       "engine jh_shader_psx"
                            "LabelText"                     ""
                            "Sound_Depressed"               "UI/buttonclick.wav"
                            "ProportionalToParent"          "1"
                            "ActionSignalLevel"             "6"
                            "PaintBackground"               "0"
                            "PaintBorder"                   "1"
                            "border_default"                "NoBorder"
                            "border_armed"                  "BorderSelectionGray"
                        }
                    }
                    /////////////////////////
                    "Shader_Fullbright"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Shader_Fullbright"
                        "XPos"                          "0"
                        "YPos"                          "0"
                        "ZPos"                          "1"
                        "Wide"                          "120"
                        "Tall"                          "82"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "PaintBackground"               "1"
                        "BGcolor_Override"              "CustomizationOptionBG"
                        "Pin_To_Sibling"                "Shader_Celshade"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                        "Shader_Image"
                        {
                            "ControlName"                   "ImagePanel"
                            "FieldName"                     "Shader_Image"
                            "XPos"                          "cs-0.5"
                            "YPos"                          "cs-0.5-6"
                            "ZPos"                          "0"
                            "Wide"                          "120"
                            "Tall"                          "70"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ScaleImage"                    "1"
                            "ProportionalToParent"          "1"
                            "Image"                         "replay/thumbnails/custom/shaders/fullbright"
                        }
                        "Shader_Label"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Label"
                            "XPos"                          "0"
                            "YPos"                          "rs1"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "FontStorePrice"
                            "LabelText"                     "Fullbright"
                            "TextAlignment"                 "center"
                            "FGColor"                       "Gray"
                            "PaintBackground"               "1"
                            "PaintBackgroundType"           "0"
                            "BGColor_Override"              "Background_Darkest"
                        }
                        "Shader_Button"
                        {
                            "ControlName"                   "CExButton"
                            "FieldName"                     "Shader_Button"
                            "XPos"                          "0"
                            "YPos"                          "0"
                            "ZPos"                          "5"
                            "Wide"                          "f0"
                            "Tall"                          "f0"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "Font"                          ""
                            "Command"                       "engine jh_shader_fullbright"
                            "LabelText"                     ""
                            "Sound_Depressed"               "UI/buttonclick.wav"
                            "ProportionalToParent"          "1"
                            "ActionSignalLevel"             "6"
                            "PaintBackground"               "0"
                            "PaintBorder"                   "1"
                            "border_default"                "NoBorder"
                            "border_armed"                  "BorderSelectionGray"
                        }
                    }
                    "Shader_Nightmode"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Shader_Nightmode"
                        "XPos"                          "5"
                        "YPos"                          "0"
                        "ZPos"                          "1"
                        "Wide"                          "120"
                        "Tall"                          "82"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "PaintBackground"               "1"
                        "BGcolor_Override"              "CustomizationOptionBG"
                        "Pin_To_Sibling"                "Shader_Fullbright"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_TOPRIGHT"
                        "Shader_Image"
                        {
                            "ControlName"                   "ImagePanel"
                            "FieldName"                     "Shader_Image"
                            "XPos"                          "cs-0.5"
                            "YPos"                          "cs-0.5-6"
                            "ZPos"                          "0"
                            "Wide"                          "120"
                            "Tall"                          "70"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ScaleImage"                    "1"
                            "ProportionalToParent"          "1"
                            "Image"                         "replay/thumbnails/custom/shaders/nightmode"
                        }
                        "Shader_Label"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Label"
                            "XPos"                          "0"
                            "YPos"                          "rs1"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "FontStorePrice"
                            "LabelText"                     "Nightmode"
                            "TextAlignment"                 "center"
                            "FGColor"                       "Gray"
                            "PaintBackground"               "1"
                            "PaintBackgroundType"           "0"
                            "BGColor_Override"              "Background_Darkest"
                        }
                        "Shader_Button"
                        {
                            "ControlName"                   "CExButton"
                            "FieldName"                     "Shader_Button"
                            "XPos"                          "0"
                            "YPos"                          "0"
                            "ZPos"                          "5"
                            "Wide"                          "f0"
                            "Tall"                          "f0"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "Font"                          ""
                            "Command"                       "engine jh_shader_nightmode"
                            "LabelText"                     ""
                            "Sound_Depressed"               "UI/buttonclick.wav"
                            "ProportionalToParent"          "1"
                            "ActionSignalLevel"             "6"
                            "PaintBackground"               "0"
                            "PaintBorder"                   "1"
                            "border_default"                "NoBorder"
                            "border_armed"                  "BorderSelectionGray"
                        }
                    }
                    "Shader_Rain"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Shader_Rain"
                        "XPos"                          "5"
                        "YPos"                          "0"
                        "ZPos"                          "1"
                        "Wide"                          "120"
                        "Tall"                          "82"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "PaintBackground"               "1"
                        "BGcolor_Override"              "CustomizationOptionBG"
                        "Pin_To_Sibling"                "Shader_Nightmode"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_TOPRIGHT"
                        "Shader_Image"
                        {
                            "ControlName"                   "ImagePanel"
                            "FieldName"                     "Shader_Image"
                            "XPos"                          "cs-0.5"
                            "YPos"                          "cs-0.5-6"
                            "ZPos"                          "0"
                            "Wide"                          "120"
                            "Tall"                          "70"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ScaleImage"                    "1"
                            "ProportionalToParent"          "1"
                            "Image"                         "replay/thumbnails/custom/shaders/rain"
                        }
                        "Shader_Label"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Label"
                            "XPos"                          "0"
                            "YPos"                          "rs1"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "FontStorePrice"
                            "LabelText"                     "Rain"
                            "TextAlignment"                 "center"
                            "FGColor"                       "Gray"
                            "PaintBackground"               "1"
                            "PaintBackgroundType"           "0"
                            "BGColor_Override"              "Background_Darkest"
                        }
                        "Shader_Button"
                        {
                            "ControlName"                   "CExButton"
                            "FieldName"                     "Shader_Button"
                            "XPos"                          "0"
                            "YPos"                          "0"
                            "ZPos"                          "5"
                            "Wide"                          "f0"
                            "Tall"                          "f0"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "Font"                          ""
                            "Command"                       "engine jh_shader_rain"
                            "LabelText"                     ""
                            "Sound_Depressed"               "UI/buttonclick.wav"
                            "ProportionalToParent"          "1"
                            "ActionSignalLevel"             "6"
                            "PaintBackground"               "0"
                            "PaintBorder"                   "1"
                            "border_default"                "NoBorder"
                            "border_armed"                  "BorderSelectionGray"
                        }
                    }
                    // "Shader_Halftone"
                    // {
                    // "ControlName"                   "EditablePanel"
                    // "FieldName"                     "Shader_Halftone"
                    // "XPos"                          "0"
                    // "YPos"                          "0"
                    // "ZPos"                          "1"
                    // "Wide"                          "120"
                    // "Tall"                          "82"
                    // "Visible"                       "1"
                    // "Enabled"                       "1"
                    // "ProportionalToParent"          "1"
                    // "PaintBackground"               "1"
                    // "BGcolor_Override"              "CustomizationOptionBG"
                    // "Pin_To_Sibling"                "Shader_Blur"
                    // "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                    // "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    // "Shader_Image"
                    // {
                    // "ControlName"                   "ImagePanel"
                    // "FieldName"                     "Shader_Image"
                    // "XPos"                          "cs-0.5"
                    // "YPos"                          "cs-0.5-6"
                    // "ZPos"                          "0"
                    // "Wide"                          "120"
                    // "Tall"                          "70"
                    // "Visible"                       "1"
                    // "Enabled"                       "1"
                    // "MouseInputEnabled"             "0"
                    // "ScaleImage"                    "1"
                    // "ProportionalToParent"          "1"
                    // "Image"                         "replay/thumbnails/custom/shaders/halftone"
                    // }
                    // "Shader_Label"
                    // {
                    // "ControlName"                   "CExLabel"
                    // "FieldName"                     "Shader_Label"
                    // "XPos"                          "0"
                    // "YPos"                          "rs1"
                    // "ZPos"                          "1"
                    // "Wide"                          "f0"
                    // "Tall"                          "12"
                    // "Visible"                       "1"
                    // "Enabled"                       "1"
                    // "MouseInputEnabled"             "0"
                    // "ProportionalToParent"          "1"
                    // "AllCaps"                       "1"
                    // "Font"                          "FontStorePrice"
                    // "LabelText"                     "Halftone"
                    // "TextAlignment"                 "center"
                    // "FGColor"                       "Gray"
                    // "PaintBackground"               "1"
                    // "PaintBackgroundType"           "0"
                    // "BGColor_Override"              "Background_Darkest"
                    // }
                    // "Shader_Button"
                    // {
                    // "ControlName"                   "CExButton"
                    // "FieldName"                     "Shader_Button"
                    // "XPos"                          "0"
                    // "YPos"                          "0"
                    // "ZPos"                          "5"
                    // "Wide"                          "f0"
                    // "Tall"                          "f0"
                    // "Visible"                       "1"
                    // "Enabled"                       "1"
                    // "Font"                          ""
                    // "Command"                       "engine jh_shader_halftone"
                    // "LabelText"                     ""
                    // "Sound_Depressed"               "UI/buttonclick.wav"
                    // "ProportionalToParent"          "1"
                    // "ActionSignalLevel"             "6"
                    // "PaintBackground"               "0"
                    // "PaintBorder"                   "1"
                    // "border_default"                "NoBorder"
                    // "border_armed"                  "BorderSelectionGray"
                    // }
                    // }
                    "Shader_Kitsune"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Shader_Kitsune"
                        "XPos"                          "0"
                        "YPos"                          "0"
                        "ZPos"                          "1"
                        "Wide"                          "120"
                        "Tall"                          "82"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "PaintBackground"               "1"
                        "BGcolor_Override"              "CustomizationOptionBG"
                        "Pin_To_Sibling"                "Shader_Fullbright"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                        "Shader_Image"
                        {
                            "ControlName"                   "ImagePanel"
                            "FieldName"                     "Shader_Image"
                            "XPos"                          "cs-0.5"
                            "YPos"                          "cs-0.5-6"
                            "ZPos"                          "0"
                            "Wide"                          "120"
                            "Tall"                          "70"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ScaleImage"                    "1"
                            "ProportionalToParent"          "1"
                            "Image"                         "replay/thumbnails/custom/shaders/kitsune"
                        }
                        "Shader_Label"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Label"
                            "XPos"                          "0"
                            "YPos"                          "rs1"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "FontStorePrice"
                            "LabelText"                     "Kitsune"
                            "TextAlignment"                 "center"
                            "FGColor"                       "Gray"
                            "PaintBackground"               "1"
                            "PaintBackgroundType"           "0"
                            "BGColor_Override"              "Background_Darkest"
                        }
                        "Shader_Button"
                        {
                            "ControlName"                   "CExButton"
                            "FieldName"                     "Shader_Button"
                            "XPos"                          "0"
                            "YPos"                          "0"
                            "ZPos"                          "5"
                            "Wide"                          "f0"
                            "Tall"                          "f0"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "Font"                          ""
                            "Command"                       "engine jh_shader_kitsune"
                            "LabelText"                     ""
                            "Sound_Depressed"               "UI/buttonclick.wav"
                            "ProportionalToParent"          "1"
                            "ActionSignalLevel"             "6"
                            "PaintBackground"               "0"
                            "PaintBorder"                   "1"
                            "border_default"                "NoBorder"
                            "border_armed"                  "BorderSelectionGray"
                        }
                    }
                    "Shader_Redtint"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Shader_Redtint"
                        "XPos"                          "5"
                        "YPos"                          "0"
                        "ZPos"                          "1"
                        "Wide"                          "120"
                        "Tall"                          "82"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "PaintBackground"               "1"
                        "BGcolor_Override"              "CustomizationOptionBG"
                        "Pin_To_Sibling"                "Shader_Kitsune"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_TOPRIGHT"
                        "Shader_Image"
                        {
                            "ControlName"                   "ImagePanel"
                            "FieldName"                     "Shader_Image"
                            "XPos"                          "cs-0.5"
                            "YPos"                          "cs-0.5-6"
                            "ZPos"                          "0"
                            "Wide"                          "120"
                            "Tall"                          "70"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ScaleImage"                    "1"
                            "ProportionalToParent"          "1"
                            "Image"                         "replay/thumbnails/custom/shaders/redtint"
                        }
                        "Shader_Label"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Label"
                            "XPos"                          "0"
                            "YPos"                          "rs1"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "FontStorePrice"
                            "LabelText"                     "Red Tint"
                            "TextAlignment"                 "center"
                            "FGColor"                       "Gray"
                            "PaintBackground"               "1"
                            "PaintBackgroundType"           "0"
                            "BGColor_Override"              "Background_Darkest"
                        }
                        "Shader_Button"
                        {
                            "ControlName"                   "CExButton"
                            "FieldName"                     "Shader_Button"
                            "XPos"                          "0"
                            "YPos"                          "0"
                            "ZPos"                          "5"
                            "Wide"                          "f0"
                            "Tall"                          "f0"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "Font"                          ""
                            "Command"                       "engine jh_shader_redtint"
                            "LabelText"                     ""
                            "Sound_Depressed"               "UI/buttonclick.wav"
                            "ProportionalToParent"          "1"
                            "ActionSignalLevel"             "6"
                            "PaintBackground"               "0"
                            "PaintBorder"                   "1"
                            "border_default"                "NoBorder"
                            "border_armed"                  "BorderSelectionGray"
                        }
                    }
                    "Shader_Notebook"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Shader_Notebook"
                        "XPos"                          "5"
                        "YPos"                          "0"
                        "ZPos"                          "1"
                        "Wide"                          "120"
                        "Tall"                          "82"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "PaintBackground"               "1"
                        "BGcolor_Override"              "CustomizationOptionBG"
                        "Pin_To_Sibling"                "Shader_Redtint"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_TOPRIGHT"
                        "Shader_Image"
                        {
                            "ControlName"                   "ImagePanel"
                            "FieldName"                     "Shader_Image"
                            "XPos"                          "cs-0.5"
                            "YPos"                          "cs-0.5-6"
                            "ZPos"                          "0"
                            "Wide"                          "120"
                            "Tall"                          "70"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ScaleImage"                    "1"
                            "ProportionalToParent"          "1"
                            "Image"                         "replay/thumbnails/custom/shaders/notebook"
                        }
                        "Shader_Label"
                        {
                            "ControlName"                   "CExLabel"
                            "FieldName"                     "Shader_Label"
                            "XPos"                          "0"
                            "YPos"                          "rs1"
                            "ZPos"                          "1"
                            "Wide"                          "f0"
                            "Tall"                          "12"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "MouseInputEnabled"             "0"
                            "ProportionalToParent"          "1"
                            "AllCaps"                       "1"
                            "Font"                          "FontStorePrice"
                            "LabelText"                     "Notebook"
                            "TextAlignment"                 "center"
                            "FGColor"                       "Gray"
                            "PaintBackground"               "1"
                            "PaintBackgroundType"           "0"
                            "BGColor_Override"              "Background_Darkest"
                        }
                        "Shader_Button"
                        {
                            "ControlName"                   "CExButton"
                            "FieldName"                     "Shader_Button"
                            "XPos"                          "0"
                            "YPos"                          "0"
                            "ZPos"                          "5"
                            "Wide"                          "f0"
                            "Tall"                          "f0"
                            "Visible"                       "1"
                            "Enabled"                       "1"
                            "Font"                          ""
                            "Command"                       "engine jh_shader_notebook"
                            "LabelText"                     ""
                            "Sound_Depressed"               "UI/buttonclick.wav"
                            "ProportionalToParent"          "1"
                            "ActionSignalLevel"             "6"
                            "PaintBackground"               "0"
                            "PaintBorder"                   "1"
                            "border_default"                "NoBorder"
                            "border_armed"                  "BorderSelectionGray"
                        }
                    }
                    // "Shader_Sepia"
                    // {
                    // "ControlName"					"EditablePanel"
                    // "FieldName"						"Shader_Sepia"
                    // "XPos"							"5"
                    // "YPos"							"0"
                    // "ZPos"							"1"
                    // "Wide"							"120"
                    // "Tall"							"82"
                    // "Visible"						"1"
                    // "Enabled"						"1"
                    // "ProportionalToParent"			"1"
                    // "PaintBackground"				"1"
                    // "BGcolor_Override"				"CustomizationOptionBG"
                    // "Pin_To_Sibling"				"Shader_Redtint"
                    // "Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
                    // "Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"
                    // "Shader_Image"
                    // {
                    // "ControlName"				"ImagePanel"
                    // "FieldName"					"Shader_Image"
                    // "XPos"						"cs-0.5"
                    // "YPos"						"cs-0.5-6"
                    // "ZPos"						"0"
                    // "Wide"						"120"
                    // "Tall"						"70"
                    // "Visible"					"1"
                    // "Enabled"					"1"
                    // "MouseInputEnabled"			"0"
                    // "ScaleImage"				"1"
                    // "ProportionalToParent"		"1"
                    // "Image"						"replay/thumbnails/custom/shaders/sepia"
                    // }
                    // "Shader_Label"
                    // {
                    // "ControlName"				"CExLabel"
                    // "FieldName"					"Shader_Label"
                    // "XPos"						"0"
                    // "YPos"						"rs1"
                    // "ZPos"						"1"
                    // "Wide"						"f0"
                    // "Tall"						"12"
                    // "Visible"					"1"
                    // "Enabled"					"1"
                    // "MouseInputEnabled"			"0"
                    // "ProportionalToParent"		"1"
                    // "AllCaps"					"1"
                    // "Font"						"FontStorePrice"
                    // "LabelText"					"Sepia"
                    // "TextAlignment"				"center"
                    // "FGColor"					"Gray"
                    // "PaintBackground"			"1"
                    // "PaintBackgroundType"		"0"
                    // "BGColor_Override"			"Background_Darkest"
                    // }
                    // "Shader_Button"
                    // {
                    // "ControlName"				"CExButton"
                    // "FieldName"					"Shader_Button"
                    // "XPos"						"0"
                    // "YPos"						"0"
                    // "ZPos"						"5"
                    // "Wide"						"f0"
                    // "Tall"						"f0"
                    // "Visible"					"1"
                    // "Enabled"					"1"
                    // "Font"						""
                    // "Command"					"engine jh_shader_Sepia"
                    // "LabelText"					""
                    // "Sound_Depressed"			"UI/buttonclick.wav"
                    // "ProportionalToParent"		"1"
                    // "ActionSignalLevel"			"6"
                    // "PaintBackground"			"0"
                    // "PaintBorder"				"1"
                    // "border_default"			"NoBorder"
                    // "border_armed"				"BorderSelectionGray"
                    // }
                    // }
                }
            }
        }
    }
}