"Resource/UI/custom/#Customization_Menu/HUD_Customization_Speedos_Demo.res"
{
    "SafeMode"
    {
        "Customizations_Panel"
        {
            "HUD_Speedos_Confirm_Dialog"
            {
                "ControlName"                   "EditablePanel"
                "FieldName"                     "HUD_Speedos_Confirm_Dialog"
                "XPos"                          "cs-0.5"
                "YPos"                          "cs-0.5"
                "ZPos"                          "2"
                "Wide"                          "250"
                "Tall"                          "100"
                "Visible"                       "0"
                "Enabled"                       "1"
                "ProportionalToParent"          "1"
                "PaintBackground"               "1"
                "paintBackgroundType"           "0"
                "BGColor_Override"              "30 30 30 255"
                "TitleLabel"
                {
                    "ControlName"                   "CExLabel"
                    "FieldName"                     "TitleLabel"
                    "XPos"                          "cs-0.5"
                    "YPos"                          "15"
                    "ProportionalToParent"          "1"
                    "ZPos"                          "1"
                    "Wide"                          "324"
                    "Tall"                          "25"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "AllCaps"                       "1"
                    "Font"                          "HudFontMedium"
                    "LabelText"                     "#ConfirmTitle"
                    "TextAlignment"                 "north"
                    "FGColor"                       "Gray"
                }
                "ExplanationLabel"
                {
                    "ControlName"                   "CExLabel"
                    "FieldName"                     "ExplanationLabel"
                    "XPos"                          "40"
                    "YPos"                          "50"
                    "ProportionalToParent"          "1"
                    "ZPos"                          "1"
                    "Wide"                          "244"
                    "Tall"                          "170"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "CenterWrap"                    "1"
                    "AllCaps"                       "1"
                    "Font"                          "HudFontSmall"
                    "LabelText"                     ""	// override in button
                    "TextAlignment"                 "north"
                    "FGColor"                       "Gray"
                }
                "CancelButton"
                {
                    "ControlName"                   "CExButton"
                    "FieldName"                     "CancelButton"
                    "XPos"                          "20"
                    "YPos"                          "rs1-20"
                    "ProportionalToParent"          "1"
                    "ZPos"                          "20"
                    "Wide"                          "100"
                    "Tall"                          "20"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "LabelText"                     "#GameUI_CancelBold"
                    "Font"                          "HudFontSmall"
                    "TextAlignment"                 "center"
                    "TextInsetX"                    "50"
                    "Command"                       "engine jh_customization_submenu_clear; hud_reloadscheme"
                    "ActionSignalLevel"             "4"
                    "AllCaps"                       "1"
                    "Sound_Depressed"               "UI/buttonclick.wav"
                    "PaintBackground"               "1"
                }
                "ConfirmButton_Soldier_Preset_JH"
                {
                    "ControlName"                       "CExButton"
                    "FieldName"                         "ConfirmButton_Soldier_Preset_JH"
                    "XPos"                              "rs1-20"
                    "YPos"                              "rs1-20"
                    "ProportionalToParent"              "1"
                    "ZPos"                              "20"
                    "Wide"                              "100"
                    "Tall"                              "20"
                    "default"                           "1"
                    "Visible"                           "0"
                    "Enabled"                           "1"
                    "LabelText"                         "CONFIRM"
                    "Font"                              "HudFontSmall"	// change in hudlayout_customization
                    "TextAlignment"                     "center"
                    "TextInsetX"                        "50"
                    "Command"                           "engine jh_speedos_s_preset_jumphud; jh_customization_submenu_clear; hud_reloadscheme"
                    "ActionSignalLevel"                 "4"
                    "AllCaps"                           "1"
                    "Sound_Depressed"                   "UI/buttonclick.wav"
                    "PaintBackground"                   "1"
                    "DefaultFGColor_Override"           "Red"
                    "DepressedFGColor_Override"         "White"
                    "ArmedFGColor_Override"             "White"
                    // "DefaultBGColor_Override"				       "Red"
                    "DepressedBGColor_Override"         "Red"
                    "ArmedBGColor_Override"             "Red"
                }
                "ConfirmButton_Demo_Preset_JH"
                {
                    "ControlName"                       "CExButton"
                    "FieldName"                         "ConfirmButton_Demo_Preset_JH"
                    "XPos"                              "rs1-20"
                    "YPos"                              "rs1-20"
                    "ProportionalToParent"              "1"
                    "ZPos"                              "20"
                    "Wide"                              "100"
                    "Tall"                              "20"
                    "default"                           "1"
                    "Visible"                           "0"
                    "Enabled"                           "1"
                    "LabelText"                         "CONFIRM"
                    "Font"                              "HudFontSmall"	// change in hudlayout_customization
                    "TextAlignment"                     "center"
                    "TextInsetX"                        "50"
                    "Command"                           "engine jh_speedos_d_preset_jumphud; jh_customization_submenu_clear; hud_reloadscheme"
                    "ActionSignalLevel"                 "4"
                    "AllCaps"                           "1"
                    "Sound_Depressed"                   "UI/buttonclick.wav"
                    "PaintBackground"                   "1"
                    "DefaultFGColor_Override"           "Red"
                    "DepressedFGColor_Override"         "White"
                    "ArmedFGColor_Override"             "White"
                    // "DefaultBGColor_Override"				       "Red"
                    "DepressedBGColor_Override"         "Red"
                    "ArmedBGColor_Override"             "Red"
                }
                "ConfirmButton_Bars_Preset_JH"
                {
                    "ControlName"                       "CExButton"
                    "FieldName"                         "ConfirmButton_Bars_Preset_JH"
                    "XPos"                              "rs1-20"
                    "YPos"                              "rs1-20"
                    "ProportionalToParent"              "1"
                    "ZPos"                              "20"
                    "Wide"                              "100"
                    "Tall"                              "20"
                    "default"                           "1"
                    "Visible"                           "0"
                    "Enabled"                           "1"
                    "LabelText"                         "CONFIRM"
                    "Font"                              "HudFontSmall"	// change in hudlayout_customization
                    "TextAlignment"                     "center"
                    "TextInsetX"                        "50"
                    "Command"                           "engine jh_bspeedos_preset_jumphud; jh_customization_submenu_clear; hud_reloadscheme"
                    "ActionSignalLevel"                 "4"
                    "AllCaps"                           "1"
                    "Sound_Depressed"                   "UI/buttonclick.wav"
                    "PaintBackground"                   "1"
                    "DefaultFGColor_Override"           "Red"
                    "DepressedFGColor_Override"         "White"
                    "ArmedFGColor_Override"             "White"
                    // "DefaultBGColor_Override"				       "Red"
                    "DepressedBGColor_Override"         "Red"
                    "ArmedBGColor_Override"             "Red"
                }
                "ConfirmButton_Reset_HUD"
                {
                    "ControlName"                       "CExButton"
                    "FieldName"                         "ConfirmButton_Reset_HUD"
                    "XPos"                              "rs1-20"
                    "YPos"                              "rs1-20"
                    "ProportionalToParent"              "1"
                    "ZPos"                              "20"
                    "Wide"                              "100"
                    "Tall"                              "20"
                    "default"                           "1"
                    "Visible"                           "0"
                    "Enabled"                           "1"
                    "LabelText"                         "CONFIRM"
                    "Font"                              "HudFontSmall"	// change in hudlayout_customization
                    "TextAlignment"                     "center"
                    "TextInsetX"                        "50"
                    "Command"                           "engine jh_customization_reset; jh_customization_submenu_clear; hud_reloadscheme"
                    "ActionSignalLevel"                 "4"
                    "AllCaps"                           "1"
                    "Sound_Depressed"                   "UI/buttonclick.wav"
                    "PaintBackground"                   "1"
                    "DefaultFGColor_Override"           "Red"
                    "DepressedFGColor_Override"         "White"
                    "ArmedFGColor_Override"             "White"
                    // "DefaultBGColor_Override"				       "Red"
                    "DepressedBGColor_Override"         "Red"
                    "ArmedBGColor_Override"             "Red"
                }
                "ConfirmButton_Restart_Game"
                {
                    "ControlName"                       "CExButton"
                    "FieldName"                         "ConfirmButton_Restart_Game"
                    "XPos"                              "rs1-20"
                    "YPos"                              "rs1-20"
                    "ProportionalToParent"              "1"
                    "ZPos"                              "20"
                    "Wide"                              "100"
                    "Tall"                              "20"
                    "default"                           "1"
                    "Visible"                           "0"
                    "Enabled"                           "1"
                    "LabelText"                         "CONFIRM"
                    "Font"                              "HudFontSmall"	// change in hudlayout_customization
                    "TextAlignment"                     "center"
                    "TextInsetX"                        "50"
                    "Command"                           "engine gameui_allowescape; mat_queue_mode -1; gamemenucommand RestartWithNewLanguage"
                    "ActionSignalLevel"                 "4"
                    "AllCaps"                           "1"
                    "Sound_Depressed"                   "UI/buttonclick.wav"
                    "PaintBackground"                   "1"
                    "DefaultFGColor_Override"           "Red"
                    "DepressedFGColor_Override"         "White"
                    "ArmedFGColor_Override"             "White"
                    // "DefaultBGColor_Override"				       "Red"
                    "DepressedBGColor_Override"         "Red"
                    "ArmedBGColor_Override"             "Red"
                }
            }
        }
    }
}