"Resource/UI/custom/#Customization_Menu/HUD_Customization_Speedos_Demo.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Speedos_Bar_Sweetspot_Info"
			{
				"ControlName"							"EditablePanel"
				"FieldName"								"HUD_Speedos_Bar_Sweetspot_Info"
				"XPos"									"rs1-50"
				"YPos"									"cs-0.5"
				"ZPos"									"1"
				"Wide"									"360"
				"Tall"									"180"
				"Visible"								"0"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"PaintBackground"						"1"
				"paintBackgroundType"					"0"
				"BGColor_Override"						"30 30 30 255"

                "Title_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title_Icon"
					"XPos"								"4"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"20"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"1"
					"Font"								"HypnotizeIcons18"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
                "Title"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title"
					"XPos"								"15"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"SWEETSPOTS INFO"
					"Font"								"HudFontSmallishbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
                "Separator_1"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_1"
					"XPos"								"3"
					"YPos"								"25"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
                "Column_Left"
                {
                    "ControlName"                       "EditablePanel"
                    "FieldName"                         "Column_Left"
                    "xpos"                              "15"
                    "ypos"                              "35"
                    "wide"                              "p0.45"
                    "tall"                              "p0.7"
                    "proportionaltoparent"              "1"
                    "visible"                           "1"
                    "enabled"                           "1"

                    "paintbackground"                   "1"
                    "bgcolor_override"                  "Background_Main"

                    "SubTitle"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"SubTitle"
                        "XPos"								"5"
                        "YPos"								"0"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Horizontal Sweetspots"
                        "Font"								"HudFontSmallishBold"
                        "TextAlignment"						"west"
                        "FGColor"							"Gray"
                    }
                    "Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f20"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"SubTitle"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
                    "Info_1"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_1"
                        "XPos"								"0"
                        "YPos"								"3"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"850 - 900 u/s"
                        "Font"								"HudFontSmall"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"White"

                        "Pin_To_Sibling"				"SubTitle"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Info_2"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_2"
                        "XPos"								"0"
                        "YPos"								"-5"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"15"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Uncharged horizontal airpogo range"
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Info_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Reference_1A"
                    {
                        "ControlName"                       "CExLabel"
                        "FieldName"							"Reference_1A"
                        "XPos"								"1"
                        "YPos"								"3"
                        "ZPos"								"0"
                        "Wide"								"20"
                        "Tall"								"18"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"1"
                        "Font"								"HudFontVerySmallBold"
                        "TextAlignment"						"east"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Info_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPRIGHT"
						"Pin_To_Sibling_Corner"			"PIN_TOPLEFT"
                    }
                    "Reference_1B"
                    {
                        "ControlName"                       "CExLabel"
                        "FieldName"							"Reference_1B"
                        "XPos"								"-45"
                        "YPos"								"0"
                        "ZPos"								"0"
                        "Wide"								"20"
                        "Tall"								"18"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"1"
                        "Font"								"HudFontVerySmallBold"
                        "TextAlignment"						"center"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"barspeedos"
						"Pin_Corner_To_Sibling"			"PIN_CENTER_BOTTOM"
						"Pin_To_Sibling_Corner"			"PIN_CENTER_BOTTOM"
                    }
                    "barspeedos"
                    {
                        "controlName" "EditablePanel"
                        "visible" "1"
                        "enabled" "1"
                        "wide" "180"
                        "tall" "180"
                        "xpos" "36"
                        "ypos" "rs1-5"
                        "proportionaltoparent"  "1"

                        "paintBackground"   "0"
                        "bgcolor_override"  "red"

                        "hspeedo_container" {
                            "controlName" "EditablePanel"
                            "visible" "1"
                            "enabled" "1"
                            "xpos" "rs1"
                            "zpos"  "1"
                            "wide" "f0"
                            "tall" "p0.03125"
                            "ypos" "rs1"
                            "proportionaltoparent"  "1"

                            "hspeedo_overlay" {
                                "controlName" "CTFImagePanel"
                                "xpos" "0"
                                "zpos"  "2"
                                "wide" "f0"
                                "tall" "f0"
                                "proportionaltoparent"  "1"
                                "image" "replay/thumbnails/speedo/bar/overlay_h_outline"
                                "visible"   "1"
                            }
                            "hspeedo_sweetspot" {
                                "controlName" "CTFImagePanel"
                                "xpos" "0"
                                "zpos"  "1"
                                "wide" "f0"
                                "tall" "f0"
                                "proportionaltoparent"  "1"
                                "image" "replay/thumbnails/speedo/bar/overlay_h_sweetspots"
                                "visible"   "1"
                            }
                        }
                        "background_container" {
                            "controlName" "EditablePanel"
                            "visible" "1"
                            "enabled" "1"
                            "xpos" "rs1"
                            "wide" "f0"
                            "tall" "f0"
                            "ypos" "0"
                            "zpos"  "-1"
                            "proportionaltoparent"  "1"

                            "hspeedo_background" {
                                "ControlName"								"EditablePanel"
                                "FieldName"									"hspeedo_background"
                                "XPos"										"0"
                                "YPos"										"rs1"
                                "Wide"										"p0.5"
                                "Tall"										"p0.03125"
                                "ProportionalToParent"						"1"
                                "Visible"									"1"
                                "Enabled"									"1"
                                "PaintBackground"							"1"
                                "PaintBackgroundType"						"0"
                                "BGColor_Override"							"TransparentLightBlack"
                            }
                        }
                    }
                }

                "Column_Right"
                {
                    "ControlName"                       "EditablePanel"
                    "FieldName"                         "Column_Right"
                    "xpos"                              "rs1-15"
                    "ypos"                              "35"
                    "wide"                              "p0.45"
                    "tall"                              "p0.7"
                    "proportionaltoparent"              "1"
                    "visible"                           "1"
                    "enabled"                           "1"

                    "paintbackground"                   "1"
                    "bgcolor_override"                  "Background_Main"

                    "SubTitle"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"SubTitle"
                        "XPos"								"5"
                        "YPos"								"0"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Vertical Sweetspots"
                        "Font"								"HudFontSmallishBold"
                        "TextAlignment"						"west"
                        "FGColor"							"Gray"
                    }
                    "Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f20"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"SubTitle"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
                    "Info_1"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_1"
                        "XPos"								"0"
                        "YPos"								"3"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"1100 u/s"
                        "Font"								"HudFontSmall"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"White"

                        "Pin_To_Sibling"				"SubTitle"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Info_2"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_2"
                        "XPos"								"0"
                        "YPos"								"-5"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"15"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Crouched vertical airpogo timing"
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Info_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Info_3"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_3"
                        "XPos"								"0"
                        "YPos"								"0"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"20"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"450 u/s"
                        "Font"								"HudFontSmall"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"White"

                        "Pin_To_Sibling"				"Info_2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Info_4"
                    {
                        "ControlName"						"CExLabel"
                        "FieldName"							"Info_4"
                        "XPos"								"0"
                        "YPos"								"-5"
                        "ZPos"								"0"
                        "Wide"								"f0"
                        "Tall"								"15"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"Downair timing"
                        "Font"								"HudFontSmallest"
                        "TextAlignment"						"west"
                        "wrap"                              "1"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Info_3"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
                    "Reference_2A"
                    {
                        "ControlName"                       "CExLabel"
                        "FieldName"							"Reference_2A"
                        "XPos"								"1"
                        "YPos"								"3"
                        "ZPos"								"0"
                        "Wide"								"20"
                        "Tall"								"18"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"2"
                        "Font"								"HudFontVerySmallBold"
                        "TextAlignment"						"east"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Info_1"
						"Pin_Corner_To_Sibling"			"PIN_TOPRIGHT"
						"Pin_To_Sibling_Corner"			"PIN_TOPLEFT"
                    }
                    "Reference_2B"
                    {
                        "ControlName"                       "CExLabel"
                        "FieldName"							"Reference_2B"
                        "XPos"								"-5"
                        "YPos"								"33"
                        "ZPos"								"0"
                        "Wide"								"20"
                        "Tall"								"18"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"2"
                        "Font"								"HudFontVerySmallBold"
                        "TextAlignment"						"center"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"barspeedos"
						"Pin_Corner_To_Sibling"			"PIN_CENTER_RIGHT"
						"Pin_To_Sibling_Corner"			"PIN_CENTER_LEFT"
                    }
                    "Reference_3A"
                    {
                        "ControlName"                       "CExLabel"
                        "FieldName"							"Reference_3A"
                        "XPos"								"1"
                        "YPos"								"3"
                        "ZPos"								"0"
                        "Wide"								"20"
                        "Tall"								"18"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"3"
                        "Font"								"HudFontVerySmallBold"
                        "TextAlignment"						"east"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"Info_3"
						"Pin_Corner_To_Sibling"			"PIN_TOPRIGHT"
						"Pin_To_Sibling_Corner"			"PIN_TOPLEFT"
                    }
                    "Reference_3B"
                    {
                        "ControlName"                       "CExLabel"
                        "FieldName"							"Reference_3B"
                        "XPos"								"-5"
                        "YPos"								"67"
                        "ZPos"								"0"
                        "Wide"								"20"
                        "Tall"								"18"
                        "Visible"							"1"
                        "Enabled"							"1"
                        "ProportionalToParent"				"1"
                        "LabelText"							"3"
                        "Font"								"HudFontVerySmallBold"
                        "TextAlignment"						"center"
                        "FGColor"							"Gray"

                        "Pin_To_Sibling"				"barspeedos"
						"Pin_Corner_To_Sibling"			"PIN_CENTER_RIGHT"
						"Pin_To_Sibling_Corner"			"PIN_CENTER_LEFT"
                    }
                    "barspeedos"
                    {
                        "controlName" "EditablePanel"
                        "visible" "1"
                        "enabled" "1"
                        "wide" "180"
                        "tall" "180"
                        "xpos" "152"
                        "ypos" "-61"
                        "proportionaltoparent"  "1"

                        "paintBackground"   "0"
                        "bgcolor_override"  "red"

                        "vspeedo_container" {
                            "controlName" "EditablePanel"
                            "visible" "1"
                            "enabled" "1"
                            "xpos" "0"
                            "wide" "p0.03125"   // 4
                            "tall" "f0"
                            "ypos" "0"
                            "proportionaltoparent"  "1"

                            "vspeedo_overlay" {
                                "controlName" "CTFImagePanel"
                                "xpos" "0"
                                "zpos"  "2"
                                "wide" "f0"
                                "tall" "f0"
                                "proportionaltoparent"  "1"
                                "image" "replay/thumbnails/speedo/bar/overlay_v_outline"
                                "visible"   "1"
                            }
                            "vspeedo_sweetspot" {
                                "controlName" "CTFImagePanel"
                                "xpos" "0"
                                "zpos"  "1"
                                "wide" "f0"
                                "tall" "f0"
                                "proportionaltoparent"  "1"
                                "image" "replay/thumbnails/speedo/bar/overlay_v_sweetspots"
                                "visible"   "1"
                            }
                        }
                        "background_container" {
                            "controlName" "EditablePanel"
                            "visible" "1"
                            "enabled" "1"
                            "xpos" "rs1"
                            "wide" "f0"
                            "tall" "f0"
                            "ypos" "0"
                            "zpos"  "-1"
                            "proportionaltoparent"  "1"

                            "vspeedo_background" {
                                "ControlName"								"EditablePanel"
                                "FieldName"									"vspeedo_background"
                                "XPos"										"0"
                                "YPos"										"rs1"
                                "Wide"										"p0.03125"
                                "Tall"										"p0.628"
                                "ProportionalToParent"						"1"
                                "Visible"									"1"
                                "Enabled"									"1"
                                "PaintBackground"							"1"
                                "PaintBackgroundType"						"0"
                                "BGColor_Override"							"TransparentLightBlack"
                            }
                        }
                    }
                }
         

                "CloseButton"
                {
                    "ControlName"								"CExButton"
                    "FieldName"									"CloseButton"
                    "XPos"										"rs1-2"
                    "YPos"										"2"
                    "ZPos"										"20"
                    "Wide"										"18"
                    "Tall"										"18"
                    "Visible"									"1"
                    "Enabled"									"1"
                    "ProportionalToParent"						"1"
                    "LabelText"									"X"
                    "Font"										"Symbols16"
                    "TextAlignment"								"center"
                    "Command"									"engine jh_custom_speedos_bar; hud_reloadscheme"
                    "ActionSignalLevel"							"4"
                    "Sound_Depressed"							"UI/buttonclick.wav"
                    "PaintBackground"							"1"

                    "DefaultFGColor_Override"					"White"
                    "ArmedFGColor_Override"						"White"
                    "DepressedFGColor_Override"					"White"

                    "DefaultBGColor_Override"					"Button_Red"
                    "ArmedBGColor_Override"						"Button_Red_Hover"
                    "DepressedBGColor_Override"					"Button_Red_Hover"
                }
			}
		}
	}
}