"Resource/UI/custom/#Customization_Menu/HUD_Customization_Speedos_Demo.res"
{
    "SafeMode"
    {
        "Customizations_Panel"
        {
            "HUD_Speedos_Heighto_Info"
            {
                "ControlName"                   "EditablePanel"
                "FieldName"                     "HUD_Speedos_Heighto_Info"
                "XPos"                          "rs1-30"
                "YPos"                          "cs-0.5"
                "ZPos"                          "1"
                "Wide"                          "400"
                "Tall"                          "224"
                "Visible"                       "0"
                "Enabled"                       "1"
                "ProportionalToParent"          "1"
                "PaintBackground"               "1"
                "paintBackgroundType"           "0"
                "BGColor_Override"              "30 30 30 255"
                "Title_Icon"
                {
                    "ControlName"                   "CExLabel"
                    "FieldName"                     "Title_Icon"
                    "XPos"                          "4"
                    "YPos"                          "0"
                    "ZPos"                          "0"
                    "Wide"                          "20"
                    "Tall"                          "25"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "ProportionalToParent"          "1"
                    "LabelText"                     "1"
                    "Font"                          "HypnotizeIcons18"
                    "TextAlignment"                 "west"
                    "FGColor"                       "Gray"
                }
                "Title"
                {
                    "ControlName"                   "CExLabel"
                    "FieldName"                     "Title"
                    "XPos"                          "15"
                    "YPos"                          "0"
                    "ZPos"                          "0"
                    "Wide"                          "f25"
                    "Tall"                          "25"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "ProportionalToParent"          "1"
                    "LabelText"                     "HEIGHTO INFO"
                    "Font"                          "HudFontSmallishbold"
                    "TextAlignment"                 "west"
                    "FGColor"                       "Gray"
                }
                "SubTitle"
                {
                    "ControlName"                   "CExLabel"
                    "FieldName"                     "SubTitle"
                    "XPos"                          "20"
                    "YPos"                          "rs1-4"
                    "ZPos"                          "0"
                    "Wide"                          "390"
                    "Tall"                          "8"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "ProportionalToParent"          "1"
                    "LabelText"                     "These ranges can be adjusted in jumphud/materials/speedo/color/ranges/"
                    "Font"                          "HudFontVerySmallBold"
                    "TextAlignment"                 "west"
                    "FGColor"                       "Gray"
                }
                "Separator_1"
                {
                    "ControlName"                   "EditablePanel"
                    "FieldName"                     "Separator_1"
                    "XPos"                          "3"
                    "YPos"                          "25"
                    "ZPos"                          "0"
                    "Wide"                          "f40"
                    "Tall"                          "2"
                    "Visible"                       "1"
                    "Enabled"                       "1"
                    "ProportionalToParent"          "1"
                    "paintBackground"               "1"
                    "paintBackgroundtype"           "3"
                    "BGcolor_Override"              "Background_Bright"
                }
                "Column_Left"
                {
                    "ControlName"                   "EditablePanel"
                    "FieldName"                     "Column_Left"
                    "xpos"                          "15"
                    "ypos"                          "35"
                    "wide"                          "p0.45"
                    "tall"                          "p0.78"
                    "proportionaltoparent"          "1"
                    "visible"                       "1"
                    "enabled"                       "1"
                    "paintbackground"               "1"
                    "bgcolor_override"              "Background_Main"
                    "SubTitle"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "SubTitle"
                        "XPos"                          "5"
                        "YPos"                          "0"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "Heighto Highlight Thresholds"
                        "Font"                          "HudFontSmallishBold"
                        "TextAlignment"                 "west"
                        "FGColor"                       "Gray"
                    }
                    "Separator"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Separator"
                        "XPos"                          "2"
                        "YPos"                          "1"
                        "ZPos"                          "0"
                        "Wide"                          "f20"
                        "Tall"                          "1"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "paintBackground"               "1"
                        "paintBackgroundtype"           "3"
                        "BGcolor_Override"              "Background_Bright"
                        "Pin_To_Sibling"                "SubTitle"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Subheading_1"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Subheading_1"
                        "XPos"                          "0"
                        "YPos"                          "1"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "Re-Sync Double"
                        "Font"                          "HudFontSmallBold"
                        "TextAlignment"                 "west"
                        "FGColor"                       "Gray"
                        "Pin_To_Sibling"                "Separator"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Separator_1"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Separator_1"
                        "XPos"                          "2"
                        "YPos"                          "-1"
                        "ZPos"                          "0"
                        "Wide"                          "f40"
                        "Tall"                          "1"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "paintBackground"               "1"
                        "paintBackgroundtype"           "3"
                        "BGcolor_Override"              "Background_Bright"
                        "Pin_To_Sibling"                "Subheading_1"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Range_1"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Range_1"
                        "XPos"                          "0"
                        "YPos"                          "-2"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "1260 units"
                        "Font"                          "HudFontSmall"
                        "TextAlignment"                 "west"
                        "wrap"                          "1"
                        "FGColor"                       "m0reBlue"
                        "Pin_To_Sibling"                "Subheading_1"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Info_1"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Info_1"
                        "XPos"                          "0"
                        "YPos"                          "-5"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "15"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     ""
                        "Font"                          "HudFontSmallest"
                        "TextAlignment"                 "west"
                        "wrap"                          "1"
                        "FGColor"                       "Gray"
                        "Pin_To_Sibling"                "Range_1"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Subheading_2"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Subheading_2"
                        "XPos"                          "0"
                        "YPos"                          "1"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "Re-Sync Triple"
                        "Font"                          "HudFontSmallBold"
                        "TextAlignment"                 "west"
                        "FGColor"                       "Gray"
                        "Pin_To_Sibling"                "Info_1"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Separator_2"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Separator_2"
                        "XPos"                          "2"
                        "YPos"                          "-1"
                        "ZPos"                          "0"
                        "Wide"                          "f40"
                        "Tall"                          "1"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "paintBackground"               "1"
                        "paintBackgroundtype"           "3"
                        "BGcolor_Override"              "Background_Bright"
                        "Pin_To_Sibling"                "Subheading_2"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Range_2"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Range_2"
                        "XPos"                          "0"
                        "YPos"                          "-2"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "2160 units"
                        "Font"                          "HudFontSmall"
                        "TextAlignment"                 "west"
                        "wrap"                          "1"
                        "FGColor"                       "m0reGreen"
                        "Pin_To_Sibling"                "Subheading_2"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Info_2"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Info_2"
                        "XPos"                          "0"
                        "YPos"                          "-5"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "15"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     ""
                        "Font"                          "HudFontSmallest"
                        "TextAlignment"                 "west"
                        "wrap"                          "1"
                        "FGColor"                       "Gray"
                        "Pin_To_Sibling"                "Range_2"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Subheading_3"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Subheading_3"
                        "XPos"                          "0"
                        "YPos"                          "1"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "Max Velocity"
                        "Font"                          "HudFontSmallBold"
                        "TextAlignment"                 "west"
                        "FGColor"                       "Gray"
                        "Pin_To_Sibling"                "Info_2"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Separator_3"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Separator_3"
                        "XPos"                          "2"
                        "YPos"                          "-1"
                        "ZPos"                          "0"
                        "Wide"                          "f40"
                        "Tall"                          "1"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "paintBackground"               "1"
                        "paintBackgroundtype"           "3"
                        "BGcolor_Override"              "Background_Bright"
                        "Pin_To_Sibling"                "Subheading_3"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Range_3"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Range_3"
                        "XPos"                          "0"
                        "YPos"                          "-2"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "7700 units"
                        "Font"                          "HudFontSmall"
                        "TextAlignment"                 "west"
                        "wrap"                          "1"
                        "FGColor"                       "m0reYellow"
                        "Pin_To_Sibling"                "Subheading_3"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Info_3"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Info_3"
                        "XPos"                          "0"
                        "YPos"                          "-5"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "15"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     ""
                        "Font"                          "HudFontSmallest"
                        "TextAlignment"                 "west"
                        "wrap"                          "1"
                        "FGColor"                       "Gray"
                        "Pin_To_Sibling"                "Range_3"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                }
                "Column_Right"
                {
                    "ControlName"                   "EditablePanel"
                    "FieldName"                     "Column_Right"
                    "xpos"                          "rs1-15"
                    "ypos"                          "35"
                    "wide"                          "p0.45"
                    "tall"                          "p0.78"
                    "proportionaltoparent"          "1"
                    "visible"                       "1"
                    "enabled"                       "1"
                    "paintbackground"               "1"
                    "bgcolor_override"              "Background_Main"
                    "SubTitle"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "SubTitle"
                        "XPos"                          "5"
                        "YPos"                          "0"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "Extra Info"
                        "Font"                          "HudFontSmallishBold"
                        "TextAlignment"                 "west"
                        "FGColor"                       "Gray"
                    }
                    "Separator"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Separator"
                        "XPos"                          "2"
                        "YPos"                          "1"
                        "ZPos"                          "0"
                        "Wide"                          "f20"
                        "Tall"                          "1"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "paintBackground"               "1"
                        "paintBackgroundtype"           "3"
                        "BGcolor_Override"              "Background_Bright"
                        "Pin_To_Sibling"                "SubTitle"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    // ILDPRUT (pinned in tempus discord general)
                    // c-tap
                    // 1x 691.86
                    // 2x 2093.50
                    // 3x 4257.14
                    // 4x 7182.79
                    //
                    "Subheading_1"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Subheading_1"
                        "XPos"                          "0"
                        "YPos"                          "1"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "Max Double Height"
                        "Font"                          "HudFontSmallBold"
                        "TextAlignment"                 "west"
                        "FGColor"                       "Gray"
                        "Pin_To_Sibling"                "Separator"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Separator_1"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Separator_1"
                        "XPos"                          "2"
                        "YPos"                          "-1"
                        "ZPos"                          "0"
                        "Wide"                          "f40"
                        "Tall"                          "1"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "paintBackground"               "1"
                        "paintBackgroundtype"           "3"
                        "BGcolor_Override"              "Background_Bright"
                        "Pin_To_Sibling"                "Subheading_1"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Range_1"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Range_1"
                        "XPos"                          "0"
                        "YPos"                          "-2"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "~2090 units"
                        "Font"                          "HudFontSmall"
                        "TextAlignment"                 "west"
                        "wrap"                          "1"
                        "FGColor"                       "White"
                        "Pin_To_Sibling"                "Subheading_1"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Subheading_2"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Subheading_2"
                        "XPos"                          "0"
                        "YPos"                          "-3"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "Max Triple Height"
                        "Font"                          "HudFontSmallBold"
                        "TextAlignment"                 "west"
                        "FGColor"                       "Gray"
                        "Pin_To_Sibling"                "Range_1"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Separator_2"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Separator_2"
                        "XPos"                          "2"
                        "YPos"                          "-1"
                        "ZPos"                          "0"
                        "Wide"                          "f40"
                        "Tall"                          "1"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "paintBackground"               "1"
                        "paintBackgroundtype"           "3"
                        "BGcolor_Override"              "Background_Bright"
                        "Pin_To_Sibling"                "Subheading_2"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Range_2"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Range_2"
                        "XPos"                          "0"
                        "YPos"                          "-2"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "~4250 units"
                        "Font"                          "HudFontSmall"
                        "TextAlignment"                 "west"
                        "wrap"                          "1"
                        "FGColor"                       "White"
                        "Pin_To_Sibling"                "Subheading_2"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Subheading_3"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Subheading_3"
                        "XPos"                          "0"
                        "YPos"                          "-3"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "Max Water Double Height"
                        "Font"                          "HudFontSmallBold"
                        "TextAlignment"                 "west"
                        "FGColor"                       "Gray"
                        "Pin_To_Sibling"                "Range_2"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Separator_3"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Separator_3"
                        "XPos"                          "2"
                        "YPos"                          "-1"
                        "ZPos"                          "0"
                        "Wide"                          "f40"
                        "Tall"                          "1"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "paintBackground"               "1"
                        "paintBackgroundtype"           "3"
                        "BGcolor_Override"              "Background_Bright"
                        "Pin_To_Sibling"                "Subheading_3"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Range_3"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Range_3"
                        "XPos"                          "0"
                        "YPos"                          "-2"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "~3100 units"
                        "Font"                          "HudFontSmall"
                        "TextAlignment"                 "west"
                        "wrap"                          "1"
                        "FGColor"                       "White"
                        "Pin_To_Sibling"                "Subheading_3"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Subheading_4"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Subheading_4"
                        "XPos"                          "0"
                        "YPos"                          "-3"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "Max Water Triple Height"
                        "Font"                          "HudFontSmallBold"
                        "TextAlignment"                 "west"
                        "FGColor"                       "Gray"
                        "Pin_To_Sibling"                "Range_3"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Separator_4"
                    {
                        "ControlName"                   "EditablePanel"
                        "FieldName"                     "Separator_4"
                        "XPos"                          "2"
                        "YPos"                          "-1"
                        "ZPos"                          "0"
                        "Wide"                          "f40"
                        "Tall"                          "1"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "paintBackground"               "1"
                        "paintBackgroundtype"           "3"
                        "BGcolor_Override"              "Background_Bright"
                        "Pin_To_Sibling"                "Subheading_4"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                    "Range_4"
                    {
                        "ControlName"                   "CExLabel"
                        "FieldName"                     "Range_4"
                        "XPos"                          "0"
                        "YPos"                          "-2"
                        "ZPos"                          "0"
                        "Wide"                          "f0"
                        "Tall"                          "20"
                        "Visible"                       "1"
                        "Enabled"                       "1"
                        "ProportionalToParent"          "1"
                        "LabelText"                     "~6700 units"
                        "Font"                          "HudFontSmall"
                        "TextAlignment"                 "west"
                        "wrap"                          "1"
                        "FGColor"                       "White"
                        "Pin_To_Sibling"                "Subheading_4"
                        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
                    }
                }
                "CloseButton"
                {
                    "ControlName"                       "CExButton"
                    "FieldName"                         "CloseButton"
                    "XPos"                              "rs1-2"
                    "YPos"                              "2"
                    "ZPos"                              "20"
                    "Wide"                              "18"
                    "Tall"                              "18"
                    "Visible"                           "1"
                    "Enabled"                           "1"
                    "ProportionalToParent"              "1"
                    "LabelText"                         "X"
                    "Font"                              "Symbols16"
                    "TextAlignment"                     "center"
                    "Command"                           "engine jh_customization_submenu_clear; hud_reloadscheme"
                    "ActionSignalLevel"                 "4"
                    "Sound_Depressed"                   "UI/buttonclick.wav"
                    "PaintBackground"                   "1"
                    "DefaultFGColor_Override"           "White"
                    "ArmedFGColor_Override"             "White"
                    "DepressedFGColor_Override"         "White"
                    "DefaultBGColor_Override"           "Button_Red"
                    "ArmedBGColor_Override"             "Button_Red_Hover"
                    "DepressedBGColor_Override"         "Button_Red_Hover"
                }
            }
        }
    }
}