"Resource/UI/custom/#Customization_Menu/HUD_Customization_Speedos_Soldier.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Resolution_Selection"
			{
				"ControlName"							"CScrollableList"
				"FieldName"								"HUD_Resolution_Selection"
				"XPos"									"cs-0.5"
				"YPos"									"cs-0.5"
				"ZPos"									"0"
				"Wide"									"f0"
				"Tall"									"f0"
				"Visible"								"0"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"PaintBackground"						"0"
				"paintBackgroundType"					"0"
				"BGColor_Override"						"Background_Darkest"

				"Scrollbar"
				{
					"XPos"								"rs1+1"
					"YPos"								"0"
					"Wide"								"6"
					"Tall"								"f0"
					"ZPos"								"1000"
					"ProportionalToParent"				"1"

					"Slider"
					{
						"PaintBackgroundType"			"0"
						"FGColor_Override"				"ScrollBar"
					}

					"nobuttons"							"1"
				}
				"Title_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title_Icon"
					"XPos"								"4"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"20"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							")"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Title"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title"
					"XPos"								"30"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"RESOLUTIONS"
					"Font"								"HudFontMediumbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
                "Restart_Warning"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Restart_Warning"
					"XPos"								"-123"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"25"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"C"
					"Font"								"Symbols20"
					"TextAlignment"						"center"
					"FGColor"							"Red"

					"Pin_To_Sibling"					"Title"
					"Pin_Corner_To_Sibling"				"PIN_CENTER_LEFT"
					"Pin_To_Sibling_Corner"				"PIN_CENTER_LEFT"
				}
				"SubTitle"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"SubTitle"
					"XPos"								"30"
					"YPos"								"22"
					"ZPos"								"0"
					"Wide"								"f0"
					"Tall"								"12"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"If your resolution is not listed, use the one with the closest Y resolution"
					"Font"								"Menu_Tiny"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
                "SubTitle2"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"SubTitle2"
					"XPos"								"30"
					"YPos"								"22+10"
					"ZPos"								"0"
					"Wide"								"f0"
					"Tall"								"12"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"(eg: if you use 3440x1440, use the button for 2560x1440)"
					"Font"								"Menu_Tiny"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_1"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_1"
					"XPos"								"3"
					"YPos"								"47"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"Separator_2"
                {
                    "ControlName"					"EditablePanel"
                    "FieldName"						"Separator_2"
                    "XPos"							"2"
                    "YPos"							"69"
                    "ZPos"							"0"
                    "Wide"							"f40"
                    "Tall"							"1"
                    "Visible"						"1"
                    "Enabled"						"1"
                    "ProportionalToParent"			"1"
                    "paintBackground"				"1"
                    "paintBackgroundtype"			"3"
                    "BGcolor_Override"				"Background_Bright"
                }
                "Res16x9"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Res16x9"
					"XPos"								"4"
					"YPos"								"53"
					"ZPos"								"20"
					"Wide"								"68"
					"Tall"								"315"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Res_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Res_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"68"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"16:9"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"center"
						"FGColor"						"Gray"
					}
					"Separator"
                    {
                        "ControlName"					"EditablePanel"
                        "FieldName"						"Separator"
                        "XPos"							"2"
                        "YPos"							"1"
                        "ZPos"							"0"
                        "Wide"							"f40"
                        "Tall"							"1"
                        "Visible"						"0"
                        "Enabled"						"1"
                        "ProportionalToParent"			"1"
                        "paintBackground"				"1"
                        "paintBackgroundtype"			"3"
                        "BGcolor_Override"				"Background_Bright"

                        "Pin_To_Sibling"				"Res_Label"
                        "Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
					"Res3840x2160"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res3840x2160"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"3840x2160"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_2160"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res2560x1440"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res2560x1440"
						"XPos"							"-2"
						"YPos"							"5+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"2560x1440"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_1440"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res1920x1080"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res1920x1080"
						"XPos"							"-2"
						"YPos"							"5+32+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"1920x1080"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_1080"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res1600x900"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res1600x900"
						"XPos"							"-2"
						"YPos"							"5+32+32+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"1600x900"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_900"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res1366x768"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res1366x768"
						"XPos"							"-2"
						"YPos"							"5+32+32+32+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"1366x768"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_768"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res1280x720"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res1280x720"
						"XPos"							"-2"
						"YPos"							"5+32+32+32+32+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"1280x720"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_720"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res1176x664"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res1176x664"
						"XPos"							"-2"
						"YPos"							"5+32+32+32+32+32+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"1176x664"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_664"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
                "Res4x3"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Res16x9"
					"XPos"								"4+68+4"
					"YPos"								"53"
					"ZPos"								"20"
					"Wide"								"68"
					"Tall"								"315"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Res_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Res_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"68"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"4:3"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"center"
						"FGColor"						"Gray"
					}
					"Separator"
                    {
                        "ControlName"					"EditablePanel"
                        "FieldName"						"Separator"
                        "XPos"							"2"
                        "YPos"							"1"
                        "ZPos"							"0"
                        "Wide"							"f40"
                        "Tall"							"1"
                        "Visible"						"0"
                        "Enabled"						"1"
                        "ProportionalToParent"			"1"
                        "paintBackground"				"1"
                        "paintBackgroundtype"			"3"
                        "BGcolor_Override"				"Background_Bright"

                        "Pin_To_Sibling"				"Res_Label"
                        "Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
                        "Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
                    }
					"Res2880x2160"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res2880x2160"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"2880x2160"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_2160"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res1920x1440"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res1920x1440"
						"XPos"							"-2"
						"YPos"							"5+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"1920x1440"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_1440"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res1600x1200"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res1600x1200"
						"XPos"							"-2"
						"YPos"							"5+32+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"1600x1200"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_1200"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res1440x1080"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res1440x1080"
						"XPos"							"-2"
						"YPos"							"5+32+32+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"1440x1080"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_1080"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res1280x1024"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res1280x1024"
						"XPos"							"-2"
						"YPos"							"5+32+32+32+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"1280x1024"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_1024"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res1280x960"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res1280x960"
						"XPos"							"-2"
						"YPos"							"5+32+32+32+32+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"1280x960"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_900"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res1152x864"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res1152x864"
						"XPos"							"-2"
						"YPos"							"5+32+32+32+32+32+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"1152x864"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_900"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res1024x768"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res1024x768"
						"XPos"							"-2"
						"YPos"							"5+32+32+32+32+32+32+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"1024x768"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_768"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
                    "Res800x600"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Res800x600"
						"XPos"							"-2"
						"YPos"							"5+32+32+32+32+32+32+32+32"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"CustomizationOptionBG"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Res_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Res_Label"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"0"
							"Font"						"HudFontSmall"
							"LabelText"					"800x600"
							"TextAlignment"				"center"
							"FGColor"					"White"
						}
						"Res_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Res_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jh_resolution_600"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
			}
		}
	}
}